!> @file maecs_maecsdo_combined.F90
!> @brief A temporary file built by combining maecs.F90 and maecs_do.F90 for documentation purposes

! @file maecs.F90 

#include "fabm_driver.h"

!> @brief This is the module registered in FABM
!> @details all the maecs_types are made available to this module
!! @todo cross-check the new units and long names of id_Rub (bulk), id_chl (bulk), id_chl2 (diag, chl:c ratio) 
module fabm_hzg_maecs
use fabm_types
use maecs_types

!implicit none

private

public type_maecs_env,type_maecs_rhs
! --- HZG model types


! standard fabm model types

!> @brief this is the model type FABM uses to create the mode
! @defgroup main main_model_members
! @name //@{ //@}
!> @details the parent type (type_maecs_base_model) was defined in maecs_types module
type,extends(type_maecs_base_model),public :: type_hzg_maecs 
 contains
  procedure :: initialize 
  procedure :: do => maecs_do
  procedure :: get_light_extinction
  procedure :: get_vertical_movement=>maecs_get_vertical_movement
end type type_hzg_maecs

!interface
  ! @brief @brief interface for the external procedure contained in maecs_main module
  ! @details phyto sinking rate depends on the nutritional state, so for each node:
  ! \n \f$ phy\%relQ \f$ obtained by calling calc_internal_states(self,phy,det,dom,zoo) 
  ! \n then \f$ phyQstat=phy\%relQ\%N * phy\%relQ\%P \f$
  ! \n finally, vsink = maecs_functions::sinking(self\%vS_phy, phyQstat, vsink)
!   subroutine maecs_get_vertical_movement(self, _ARGUMENTS_GET_VERTICAL_MOVEMENT_) 
!   import type_hzg_maecs,type_environment,rk
!   class (type_hzg_maecs),intent(in) :: self
!   _DECLARE_ARGUMENTS_GET_VERTICAL_MOVEMENT_
!   end subroutine
! end interface

!#SP0
!!----------------------------------------------------------------------
!! this code is generated by a parser  (conv_nml_fabm.c by kai wirtz)
!!----------------------------------------------------------------------
! --- HZG model types
!!--------------------------------------------------------------------

contains
!> @brief initializes the model
!! @details here the maecs namelists are read and assigned respectively in the model type (self),
!! state & diagnostic variables are registered in FABM and dependencies are imported from FABM
!>
!> **Model parameters, descriptions and corresponding symbols used in formulas:**
! initial values
!> \describepar{nutN\_initial , \mathrm{DIN} , Dissolved Inorganic Nitrogen DIN, 30.0 mmol-N/m**3}
!> \describepar{nutP\_initial , \mathrm{Phy}_\mathrm{P} , Dissolved Inorganic Phosphorus DIP, 1.2 mmol-P/m**3}
!> \describepar{nutS\_initial , \mathrm{Phy}_\mathrm{Si} , Dissolved Inorganic Silicon Si, 20. mmol-Si/m**3}
!> \describepar{phyC\_initial , \mathrm{Phy}_\mathrm{C} , Phytplankton Carbon, 10 mmol-C/m**3}
!> \describepar{phyN\_initial , \mathrm{phyN_initial} , Phytplankton Nitrogen, 0.8 mmol-N/m**3}
!> \describepar{phyP\_initial , \mathrm{phyP_initial} , Phytplankton Phosphorus, 0.08 mmol-P/m**3}
!> \describepar{phyS\_initial , \mathrm{phyS_initial} , Phytplankton Silicon, 0.8 mmol-Si/m**3}
!> \describepar{zooC\_initial , \mathrm{zooC_initial} , Zooplankton Carbon, 0.1 mmol-C/m**3}
!> \describepar{detC\_initial , \mathrm{detC_initial} , Detritus Carbon, 1 mmol-C/m**3}
!> \describepar{detN\_initial , \mathrm{detN_initial} , Detritus Nitrogen, 0.1 mmol-N/m**3}
!> \describepar{detP\_initial , \mathrm{detP_initial} , Detritus Phosphorus, 0.01 mmol-P/m**3}
!> \describepar{detS\_initial , \mathrm{detS_initial} , Detritus Silicon, 0.1 mmol-Si/m**3}
!> \describepar{domC\_initial , \mathrm{domC_initial} , Dissolved Organic Carbon, 0.1 mmol-C/m**3}
!> \describepar{domN\_initial , \mathrm{domN_initial} , Dissolved Organic Nitrogen, 0.01 mmol-N/m**3}
!> \describepar{domP\_initial , \mathrm{domP_initial} , Dissolved Organic Phosphorus, 0.001 mmol-P/m**3}
!> \describepar{frac\_Rub\_ini , f_R , fraction of Rubisco, 0.4 -}
!> \describepar{Rub          , f_R\mathrm{Phy}_\mathrm{C}, trait x biomass}
!> \describepar{frac\_chl\_ini , f_\theta\theta_C , Chl:C ratio, 0.034 mg-Chla/mmol-C}
!> \describepar{chl          , f_\theta\theta_C\mathrm{Phy}_\mathrm{C}, trait x biomass}
! other parameters
!> \describepar{P\_max        , P_\mathrm{max}        , maximum potential photosynthetic rate, 12.0 d^{-1}}
!> \describepar{alpha        , \alpha        , specific light adsorption by chloroplasts, 0.12 m2 mol-C/(muE g-CHL)}
!> \describepar{sigma        , \sigma        , Q-dependency of Rubisco activity/chloroplast ratio, 0.0 }
!> \describepar{theta\_LHC    , \theta_\mathrm{C}    , Chlorophylla-to-C ratio of LHC, 1.2 mgChl mmolC^{-1}}
!> \describepar{rel\_chloropl\_min , \mathrm{rel_chloropl_min} , chloroplast-C to phy-C ratio, 0.01 mol-C/mol-C}
!> \describepar{QN\_phy\_0     , Q_{\mathrm{N}0}     , subsistence N-quota, 0.045 mol-N/mol-C}
!> \describepar{QN\_phy\_max   , Q_\mathrm{N}^\mathrm{ref}   , maximum N-quota, 0.24 mol-N/mol-C}
!> \describepar{V\_NC\_max     , V_\mathrm{max,N}^0     , maximum N uptake rate, 0.3 mol-N/(mol-C d)}
!> \describepar{AffN         , A_\mathrm{N}^0         , N-Affinity, 0.1 m3/(mmol-C d)}
!> \describepar{zeta\_CN      , \zeta_\mathrm{CN}      , respiratory costs of N-synthesis/NO3-reduction, 2.3 mol-C/mol-N}
!> \describepar{zstoich\_PN   , \mathrm{zstoich_PN}   , P-stoichiometry of active compounds(-> P costs), 3.8 mol-N/mol-P}
!> \describepar{exud\_phy     , \mathrm{exud_phy}     , phytoplankton exudation per production, 0.0 }
!> \describepar{QP\_phy\_0     , Q_{\mathrm{P}0}     , subsistence P-quota, 0.0 mol-P/mol-C}
!> \describepar{QP\_phy\_max   , Q_\mathrm{P}^\mathrm{ref}   , subsistence P-quota, 0.02 mol-P/mol-C}
!> \describepar{V\_PC\_max     , V_\mathrm{max,P}^0     , maximum P uptake rate, 0.03 mol-P/(mol-C d)}
!> \describepar{AffP         , A_\mathrm{P}^0         , P-Affinity, 0.07 m3/(mmol-C d)}
!> \describepar{QSi\_phy\_0    , Q_{\mathrm{Si}0}    , subsistence Si-quota, 0.0 mol-Si/mol-C}
!> \describepar{QSi\_phy\_max  , Q_\mathrm{Si}^\mathrm{ref}  , subsistence Si-quota, 0.1 mol-Si/mol-C}
!> \describepar{V\_SiC\_max    , V_\mathrm{max,Si}^0    , maximum Si-uptake rate, 0.02 mol-Si/(mol-C d)}
!> \describepar{AffSi        , A_\mathrm{Si}^0        , Si-Affinity, 0.05 m3/(mmol-C d)}
!> \describepar{syn\_nut      , 1/h      , synchrony n\_queue in nutrient quota limitation, 2.0 }
!> \describepar{adap\_rub     , \delta_R     , adap\_rub, 1.0 }
!> \describepar{adap\_theta   , \delta_\theta   , adap\_theta, 1.0 }
!> \describepar{tau\_regV     , \Delta t_\mathrm{v}     , tau\_regV, 99.0 }
!> \describepar{phi\_agg      , \mathrm{phi_agg}      , quadratic aggregation rate, 5E-4 m^6 mmolN^{-2} d^{-1}}
!> \describepar{vS\_phy       , \mathrm{vS_phy}       , sinking velocity for phytoplankton, 5E-2 m d^{-1}}
!> \describepar{vS\_det       , \mathrm{vS_det}       , sinking velocity for detritus, 2. m d^{-1}}
!> \describepar{hydrol       , \mathrm{hydrol}       , hydrolysis rate, 0.03 d^{-1}}
!> \describepar{remin        , \mathrm{remin}        , pelagic remineralisation, 0.03 d^{-1}}
!> \describepar{Ae\_all       , \mathrm{Ae_all}       , Activation energy, 4500.0 ...}
!> \describepar{T\_ref        , \mathrm{T_ref}        , reference temperature, 288.0 degC}
!> \describepar{NutOrder     , \mathrm{NutOrder}     , element order of recursive scheme. lower digit: synchrony element   , 123.1 serial order number N:P:Si}
!> \describepar{const\_NC\_zoo , \mathrm{const_NC_zoo} , zooplankton N:C ratio, 0.3 mol/mol}
!> \describepar{const\_PC\_zoo , \mathrm{const_PC_zoo} , zooplankton P:C ratio, 0.025 mol/mol}
!> \describepar{g\_max        , \mathrm{g_max}        , maximum grazing rate, 1. per d}
!> \describepar{k\_grazC      , \mathrm{k_grazC}      , half saturation graing, 5.0 mmolN/m**3}
!> \describepar{yield\_zoo    , \mathrm{yield_zoo}    , yield of herbivory, 0.35 }
!> \describepar{basal\_resp\_zoo , \mathrm{basal_resp_zoo} , basal respiration, 0.04 per d}
!> \describepar{mort\_zoo     , \mathrm{mort_zoo}     , quadratic mortality, 0.035 m**3/mmolN.d}
!> \describepar{a\_water      , \mathrm{a_water}      , background attenuation coefficient, 0.01 1/m}
!> \describepar{a\_spm        , \mathrm{a_spm}        , attenuation coefficient of SPM, 0.001 m**3/m.mmolC}
!> \describepar{a\_chl        , \mathrm{a_chl}        , attenuation coefficient due to Chl absorption, 0.02 m**3/m.mgChl}
!> \describepar{frac\_PAR     , \mathrm{frac_PAR}     , photosynthetically active fraction of light, 1.0 }
!> \describepar{small        , \mathrm{small}        , lower limit for denominator in ratios; small\_finite=sqrt(small), 1e-04 }
!> \describepar{dil          , \mathrm{dil}          , dilution of all concentrations except dissolved inorganics, 0.0 }
subroutine initialize(self, configunit)

class (type_hzg_maecs), intent(inout), target :: self
integer,                  intent(in)            :: configunit
!
! !LOCAL VARIABLES:
integer    :: namlst=19
!!------- Initial values of model maecs ------- 
real(rk)  :: nutN_initial ! Dissolved Inorganic Nitrogen DIN
real(rk)  :: nutP_initial ! Dissolved Inorganic Phosphorus DIP
real(rk)  :: nutS_initial ! Dissolved Inorganic Silicon Si
real(rk)  :: phyC_initial ! Phytplankton Carbon
real(rk)  :: phyN_initial ! Phytplankton Nitrogen
real(rk)  :: phyP_initial ! Phytplankton Phosphorus
real(rk)  :: phyS_initial ! Phytplankton Silicon
real(rk)  :: zooC_initial ! Zooplankton Carbon
real(rk)  :: detC_initial ! Detritus Carbon
real(rk)  :: detN_initial ! Detritus Nitrogen
real(rk)  :: detP_initial ! Detritus Phosphorus
real(rk)  :: detS_initial ! Detritus Silicon
real(rk)  :: domC_initial ! Dissolved Organic Carbon
real(rk)  :: domN_initial ! Dissolved Organic Nitrogen
real(rk)  :: domP_initial ! Dissolved Organic Phosphorus
real(rk)  :: frac_Rub_ini ! fraction of Rubisco
real(rk)  :: Rub  ! trait times biomass
real(rk)  :: frac_chl_ini ! Chl:C ratio
real(rk)  :: chl  ! trait times biomass
!!------- Parameters from nml-list maecs_pars ------- 
real(rk)  :: P_max        ! maximum potential photosynthetic rate
real(rk)  :: alpha        ! specific light adsorption by chloroplasts
real(rk)  :: sigma        ! Q-dependency of Rubisco activity/chloroplast ratio
real(rk)  :: theta_LHC    ! Chlorophylla-to-C ratio of LHC
real(rk)  :: rel_chloropl_min ! chloroplast-C to phy-C ratio
real(rk)  :: QN_phy_0     ! subsistence N-quota
real(rk)  :: QN_phy_max   ! maximum N-quota
real(rk)  :: V_NC_max     ! maximum N uptake rate
real(rk)  :: AffN         ! N-Affinity
real(rk)  :: zeta_CN      ! respiratory costs of N-synthesis/NO3-reduction
real(rk)  :: zstoich_PN   ! P-stoichiometry of active compounds(-> P costs)
real(rk)  :: exud_phy     ! phytoplankton exudation per production
real(rk)  :: QP_phy_0     ! subsistence P-quota
real(rk)  :: QP_phy_max   ! subsistence P-quota
real(rk)  :: V_PC_max     ! maximum P uptake rate
real(rk)  :: AffP         ! P-Affinity
real(rk)  :: QSi_phy_0    ! subsistence Si-quota
real(rk)  :: QSi_phy_max  ! subsistence Si-quota
real(rk)  :: V_SiC_max    ! maximum Si-uptake rate
real(rk)  :: AffSi        ! Si-Affinity
real(rk)  :: syn_nut      ! synchrony n_queue in nutrient quota limitation
real(rk)  :: adap_rub     ! adap_rub
real(rk)  :: adap_theta   ! adap_theta
real(rk)  :: tau_regV     ! tau_regV
real(rk)  :: phi_agg      ! quadratic aggregation rate
real(rk)  :: vS_phy       ! sinking velocity for phytoplankton
real(rk)  :: vS_det       ! sinking velocity for detritus
real(rk)  :: hydrol       ! hydrolysis rate
real(rk)  :: remin        ! pelagic remineralisation
real(rk)  :: Ae_all       ! Activation energy
real(rk)  :: T_ref        ! reference temperature
real(rk)  :: NutOrder     ! element order of recursive scheme. lower digit: synchrony element   
!!------- Parameters from nml-list maecs_graz ------- 
real(rk)  :: const_NC_zoo ! zooplankton N:C ratio
real(rk)  :: const_PC_zoo ! zooplankton P:C ratio
real(rk)  :: g_max        ! maximum grazing rate
real(rk)  :: k_grazC      ! half saturation graing
real(rk)  :: yield_zoo    ! yield of herbivory
real(rk)  :: basal_resp_zoo ! basal respiration
real(rk)  :: mort_zoo     ! quadratic mortality
!!------- Parameters from nml-list maecs_env ------- 
real(rk)  :: a_water      ! background attenuation coefficient
real(rk)  :: a_spm        ! attenuation coefficient of SPM
real(rk)  :: a_chl        ! attenuation coefficient due to Chl absorption
real(rk)  :: frac_PAR     ! photosynthetically active fraction of light
real(rk)  :: small        ! lower limit for denominator in ratios; small_finite=sqrt(small)
real(rk)  :: dil          ! dilution of all concentrations except dissolved inorganics
!!------- Switches for configuring model structure -------
logical   :: RubiscoOn    ! use Rubisco- here in C-units
logical   :: PhotoacclimOn ! use Photoacclimation
logical   :: PhosphorusOn ! resolve Phosphorus cycle
logical   :: SiliconOn    ! resolve Silicon cycle
logical   :: GrazingOn    ! use Zooplankton grazing
logical   :: BioCarbochemOn ! use geochemistry module
logical   :: BioOxyOn     ! use oxygen from other FABM model
logical   :: DebugDiagOn  ! output of all diagnostics
logical   :: ChemostatOn  ! use Chemostat mode 
logical   :: UptakeLock   ! use same allocation for all uptake systems (Smith2008)
logical   :: detritus_no_river_dilution ! use riverine det import
logical   :: plankton_no_river_dilution ! use riverine det import

namelist /maecs_switch/ &
  RubiscoOn, PhotoacclimOn, PhosphorusOn, SiliconOn, GrazingOn, BioCarbochemOn, &
  BioOxyOn, DebugDiagOn, ChemostatOn, UptakeLock, detritus_no_river_dilution, &
  plankton_no_river_dilution

namelist /maecs_init/ &
  nutN_initial, nutP_initial, nutS_initial, phyC_initial, phyN_initial, &
  phyP_initial, phyS_initial, zooC_initial, detC_initial, detN_initial, &
  detP_initial, detS_initial, domC_initial, domN_initial, domP_initial, &
  frac_Rub_ini, frac_chl_ini

namelist /maecs_pars/ &
  P_max, alpha, sigma, theta_LHC, rel_chloropl_min, QN_phy_0, QN_phy_max, &
  V_NC_max, AffN, zeta_CN, zstoich_PN, exud_phy, QP_phy_0, QP_phy_max, V_PC_max, &
  AffP, QSi_phy_0, QSi_phy_max, V_SiC_max, AffSi, syn_nut, adap_rub, adap_theta, &
  tau_regV, phi_agg, vS_phy, vS_det, hydrol, remin, Ae_all, T_ref, NutOrder

namelist /maecs_graz/ &
  const_NC_zoo, const_PC_zoo, g_max, k_grazC, yield_zoo, basal_resp_zoo, &
  mort_zoo

namelist /maecs_env/ &
  a_water, a_spm, a_chl, frac_PAR, small, dil

nutN_initial = 30.0_rk            ! mmol-N/m**3
nutP_initial = 1.2_rk             ! mmol-P/m**3
nutS_initial = 20._rk             ! mmol-Si/m**3
phyC_initial = 10_rk              ! mmol-C/m**3
phyN_initial = 0.8_rk             ! mmol-N/m**3
phyP_initial = 0.08_rk            ! mmol-P/m**3
phyS_initial = 0.8_rk             ! mmol-Si/m**3
zooC_initial = 0.1_rk             ! mmol-C/m**3
detC_initial = 1_rk               ! mmol-C/m**3
detN_initial = 0.1_rk             ! mmol-N/m**3
detP_initial = 0.01_rk            ! mmol-P/m**3
detS_initial = 0.1_rk             ! mmol-Si/m**3
domC_initial = 0.1_rk             ! mmol-C/m**3
domN_initial = 0.01_rk            ! mmol-N/m**3
domP_initial = 0.001_rk           ! mmol-P/m**3
frac_Rub_ini = 0.4_rk             ! -
frac_chl_ini = 0.034_rk           ! mg-Chla/mmol-C
P_max        = 12.0_rk            ! d^{-1}
alpha        = 0.12_rk            ! m2 mol-C/(muE g-CHL)
sigma        = 0.0_rk             ! 
theta_LHC    = 1.2_rk             ! mgChl mmolC^{-1}
rel_chloropl_min = 0.01_rk            ! mol-C/mol-C
QN_phy_0     = 0.045_rk           ! mol-N/mol-C
QN_phy_max   = 0.24_rk            ! mol-N/mol-C
V_NC_max     = 0.3_rk             ! mol-N/(mol-C d)
AffN         = 0.1_rk             ! m3/(mmol-C d)
zeta_CN      = 2.3_rk             ! mol-C/mol-N
zstoich_PN   = 3.8_rk             ! mol-N/mol-P
exud_phy     = 0.0_rk             ! 
QP_phy_0     = 0.0_rk             ! mol-P/mol-C
QP_phy_max   = 0.02_rk            ! mol-P/mol-C
V_PC_max     = 0.03_rk            ! mol-P/(mol-C d)
AffP         = 0.07_rk            ! m3/(mmol-C d)
QSi_phy_0    = 0.0_rk             ! mol-Si/mol-C
QSi_phy_max  = 0.1_rk             ! mol-Si/mol-C
V_SiC_max    = 0.02_rk            ! mol-Si/(mol-C d)
AffSi        = 0.05_rk            ! m3/(mmol-C d)
syn_nut      = 2.0_rk             ! 
adap_rub     = 1.0_rk             ! 
adap_theta   = 1.0_rk             ! 
tau_regV     = 99.0_rk            ! 
phi_agg      = 5E-4_rk            ! m^6 mmolN^{-2} d^{-1}
vS_phy       = 5E-2_rk            ! m d^{-1}
vS_det       = 2._rk              ! m d^{-1}
hydrol       = 0.03_rk            ! d^{-1}
remin        = 0.03_rk            ! d^{-1}
Ae_all       = 4500.0_rk          ! ...
T_ref        = 288.0_rk           ! degC
NutOrder     = 123.1_rk           ! serial order number N:P:Si
const_NC_zoo = 0.3_rk             ! mol/mol
const_PC_zoo = 0.025_rk           ! mol/mol
g_max        = 1._rk              ! per d
k_grazC      = 5.0_rk             ! mmolN/m**3
yield_zoo    = 0.35_rk            ! 
basal_resp_zoo = 0.04_rk            ! per d
mort_zoo     = 0.035_rk           ! m**3/mmolN.d
a_water      = 0.01_rk            ! 1/m
a_spm        = 0.001_rk           ! m**3/m.mmolC
a_chl        = 0.02_rk            ! m**3/m.mgChl
frac_PAR     = 1.0_rk             ! 
small        = 1e-04_rk           ! 
dil          = 0.0_rk             ! 


!--------- read namelists --------- 
write(0,*) ' read namelists ....'
open(namlst,file='maecs_switch.nml',status='old')
read(namlst,nml=maecs_switch,err=90,end=99)
open(namlst,file='maecs_init.nml',status='old')
read(namlst,nml=maecs_init,err=91,end=100)
open(namlst,file='maecs_pars.nml',status='old')
read(namlst,nml=maecs_pars,err=92,end=101)
open(namlst,file='maecs_graz.nml',status='old')
read(namlst,nml=maecs_graz,err=93,end=102)
open(namlst,file='maecs_env.nml',status='old')
read(namlst,nml=maecs_env,err=94,end=103)
! Store parameter values in our own derived type
! NB: all rates must be provided in values per day,
! and are converted here to values per second.

!!------- logical parameters: switches  -------
call self%get_parameter(self%RubiscoOn,     'RubiscoOn',     default=RubiscoOn)
call self%get_parameter(self%PhotoacclimOn,  'PhotoacclimOn',  default=PhotoacclimOn)
call self%get_parameter(self%PhosphorusOn,  'PhosphorusOn',  default=PhosphorusOn)
call self%get_parameter(self%SiliconOn,     'SiliconOn',     default=SiliconOn)
call self%get_parameter(self%GrazingOn,     'GrazingOn',     default=GrazingOn)
call self%get_parameter(self%BioCarbochemOn,  'BioCarbochemOn',  default=BioCarbochemOn)
call self%get_parameter(self%BioOxyOn,      'BioOxyOn',      default=BioOxyOn)
call self%get_parameter(self%DebugDiagOn,   'DebugDiagOn',   default=DebugDiagOn)
call self%get_parameter(self%ChemostatOn,   'ChemostatOn',   default=ChemostatOn)
call self%get_parameter(self%UptakeLock,    'UptakeLock',    default=UptakeLock)
call self%get_parameter(self%detritus_no_river_dilution,  'detritus_no_river_dilution',  default=detritus_no_river_dilution)
call self%get_parameter(self%plankton_no_river_dilution,  'plankton_no_river_dilution',  default=plankton_no_river_dilution)

!!------- model parameters from nml-list maecs_init ------- 
call self%get_parameter(self%nutN_initial ,'nutN_initial',  default=nutN_initial)
call self%get_parameter(self%phyC_initial ,'phyC_initial',  default=phyC_initial)
call self%get_parameter(self%phyN_initial ,'phyN_initial',  default=phyN_initial)
call self%get_parameter(self%detC_initial ,'detC_initial',  default=detC_initial)
call self%get_parameter(self%detN_initial ,'detN_initial',  default=detN_initial)
call self%get_parameter(self%domC_initial ,'domC_initial',  default=domC_initial)
call self%get_parameter(self%domN_initial ,'domN_initial',  default=domN_initial)
    call self%get_parameter(self%frac_Rub_ini ,'frac_Rub_ini',  default=frac_Rub_ini)
    call self%get_parameter(self%frac_chl_ini ,'frac_chl_ini',  default=frac_chl_ini)
    call self%get_parameter(self%nutP_initial ,'nutP_initial',  default=nutP_initial)
    call self%get_parameter(self%phyP_initial ,'phyP_initial',  default=phyP_initial)
    call self%get_parameter(self%detP_initial ,'detP_initial',  default=detP_initial)
    call self%get_parameter(self%domP_initial ,'domP_initial',  default=domP_initial)
    call self%get_parameter(self%nutS_initial ,'nutS_initial',  default=nutS_initial)
    call self%get_parameter(self%phyS_initial ,'phyS_initial',  default=phyS_initial)
    call self%get_parameter(self%detS_initial ,'detS_initial',  default=detS_initial)
    call self%get_parameter(self%zooC_initial ,'zooC_initial',  default=zooC_initial)

!!------- model parameters from nml-list maecs_pars ------- 
call self%get_parameter(self%P_max        ,'P_max',         default=P_max)
call self%get_parameter(self%alpha        ,'alpha',         default=alpha)
call self%get_parameter(self%sigma        ,'sigma',         default=sigma)
call self%get_parameter(self%theta_LHC    ,'theta_LHC',     default=theta_LHC)
call self%get_parameter(self%rel_chloropl_min ,'rel_chloropl_min',  default=rel_chloropl_min)
call self%get_parameter(self%QN_phy_0     ,'QN_phy_0',      default=QN_phy_0)
call self%get_parameter(self%QN_phy_max   ,'QN_phy_max',    default=QN_phy_max)
call self%get_parameter(self%V_NC_max     ,'V_NC_max',      default=V_NC_max)
call self%get_parameter(self%AffN         ,'AffN',          default=AffN)
call self%get_parameter(self%zeta_CN      ,'zeta_CN',       default=zeta_CN)
call self%get_parameter(self%zstoich_PN   ,'zstoich_PN',    default=zstoich_PN)
call self%get_parameter(self%exud_phy     ,'exud_phy',      default=exud_phy)
call self%get_parameter(self%syn_nut      ,'syn_nut',       default=syn_nut)
call self%get_parameter(self%tau_regV     ,'tau_regV',      default=tau_regV)
call self%get_parameter(self%phi_agg      ,'phi_agg',       default=phi_agg)
call self%get_parameter(self%vS_phy       ,'vS_phy',        default=vS_phy)
call self%get_parameter(self%vS_det       ,'vS_det',        default=vS_det)
call self%get_parameter(self%hydrol       ,'hydrol',        default=hydrol)
call self%get_parameter(self%remin        ,'remin',         default=remin)
call self%get_parameter(self%Ae_all       ,'Ae_all',        default=Ae_all)
call self%get_parameter(self%T_ref        ,'T_ref',         default=T_ref)
call self%get_parameter(self%NutOrder     ,'NutOrder',      default=NutOrder)
if (RubiscoOn) then
    call self%get_parameter(self%adap_rub     ,'adap_rub',      default=adap_rub)
end if
if (PhotoacclimOn) then
    call self%get_parameter(self%adap_theta   ,'adap_theta',    default=adap_theta)
end if
if (PhosphorusOn) then
    call self%get_parameter(self%QP_phy_0     ,'QP_phy_0',      default=QP_phy_0)
    call self%get_parameter(self%QP_phy_max   ,'QP_phy_max',    default=QP_phy_max)
    call self%get_parameter(self%V_PC_max     ,'V_PC_max',      default=V_PC_max)
    call self%get_parameter(self%AffP         ,'AffP',          default=AffP)
end if
if (SiliconOn) then
    call self%get_parameter(self%QSi_phy_0    ,'QSi_phy_0',     default=QSi_phy_0)
    call self%get_parameter(self%QSi_phy_max  ,'QSi_phy_max',   default=QSi_phy_max)
    call self%get_parameter(self%V_SiC_max    ,'V_SiC_max',     default=V_SiC_max)
    call self%get_parameter(self%AffSi        ,'AffSi',         default=AffSi)
end if

!!------- model parameters from nml-list maecs_graz ------- 
call self%get_parameter(self%const_NC_zoo ,'const_NC_zoo',  default=const_NC_zoo)
if (PhosphorusOn) then
    call self%get_parameter(self%const_PC_zoo ,'const_PC_zoo',  default=const_PC_zoo)
end if
if (GrazingOn) then
    call self%get_parameter(self%g_max        ,'g_max',         default=g_max)
    call self%get_parameter(self%k_grazC      ,'k_grazC',       default=k_grazC)
    call self%get_parameter(self%yield_zoo    ,'yield_zoo',     default=yield_zoo)
    call self%get_parameter(self%basal_resp_zoo ,'basal_resp_zoo',  default=basal_resp_zoo)
    call self%get_parameter(self%mort_zoo     ,'mort_zoo',      default=mort_zoo)
end if

!!------- model parameters from nml-list maecs_env ------- 
call self%get_parameter(self%a_water      ,'a_water',       default=a_water)
call self%get_parameter(self%a_spm        ,'a_spm',         default=a_spm)
call self%get_parameter(self%a_chl        ,'a_chl',         default=a_chl)
call self%get_parameter(self%frac_PAR     ,'frac_PAR',      default=frac_PAR)
call self%get_parameter(self%small        ,'small',         default=small)
call self%get_parameter(self%dil          ,'dil',           default=dil)

!!------- derived parameters  ------- 
self%K_QN_phy     = QN_phy_max-QN_phy_0
self%iK_QN        = 1.0d0/self%K_QN_phy
self%iK_QP        = 1.0d0/(QP_phy_max-QP_phy_0)
self%iK_QSi       = 1.0d0/(QSi_phy_max-QSi_phy_0)
self%itheta_max   = 1.0d0/theta_LHC
self%aver_QN_phy  = 5.0d-1*(QN_phy_max+QN_phy_0)
self%aver_QP_phy  = 5.0d-1*(QP_phy_max+QP_phy_0)
self%small_finite  = sqrt(small)

!!------- Register state variables  ------- 
call self%register_state_variable(self%id_nutN,  'nutN','mmol-N/m**3','Dissolved Inorganic Nitrogen DIN nutN', &
   nutN_initial, minimum=_ZERO_, no_river_dilution=.true. )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_nutN)
call self%register_state_variable(self%id_phyC,  'phyC','mmol-C/m**3','Phytplankton Carbon phyC', &
   phyC_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_phyC)
call self%register_state_variable(self%id_phyN,  'phyN','mmol-N/m**3','Phytplankton Nitrogen phyN', &
   phyN_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_phyN)
call self%register_state_variable(self%id_detC,  'detC','mmol-C/m**3','Detritus Carbon detC', &
   detC_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_detC)
call self%register_state_variable(self%id_detN,  'detN','mmol-N/m**3','Detritus Nitrogen detN', &
   detN_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_detN)
call self%register_state_variable(self%id_domC,  'domC','mmol-C/m**3','Dissolved Organic Carbon domC', &
   domC_initial, minimum=_ZERO_, no_river_dilution=.true. )
call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_domC)
call self%register_state_variable(self%id_domN,  'domN','mmol-N/m**3','Dissolved Organic Nitrogen domN', &
   domN_initial, minimum=_ZERO_, no_river_dilution=.true. )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_domN)

if (RubiscoOn) then
    Rub = frac_Rub_ini * phyC_initial  ! trait times biomass
    call self%register_state_variable(self%id_Rub,   'Rub','mmol-C/m**3','Rub-C concentration', &
       Rub, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
end if

if (PhotoacclimOn) then
    chl = frac_chl_ini * phyC_initial  ! trait times biomass
    call self%register_state_variable(self%id_chl,   'chl','mg-Chla/m**3','chl-a concentration', &
       chl, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
end if

if (PhosphorusOn) then
    call self%register_state_variable(self%id_nutP,  'nutP','mmol-P/m**3','Dissolved Inorganic Phosphorus DIP nutP', &
       nutP_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_nutP)
    call self%register_state_variable(self%id_phyP,  'phyP','mmol-P/m**3','Phytplankton Phosphorus phyP', &
       phyP_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_phyP)
    call self%register_state_variable(self%id_detP,  'detP','mmol-P/m**3','Detritus Phosphorus detP', &
       detP_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_detP)
    call self%register_state_variable(self%id_domP,  'domP','mmol-P/m**3','Dissolved Organic Phosphorus domP', &
       domP_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_domP)
end if

if (SiliconOn) then
    call self%register_state_variable(self%id_nutS,  'nutS','mmol-Si/m**3','Dissolved Inorganic Silicon Si nutS', &
       nutS_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%add_to_aggregate_variable(standard_variables%total_silicate,self%id_nutS)
    call self%register_state_variable(self%id_phyS,  'phyS','mmol-Si/m**3','Phytplankton Silicon phyS', &
       phyS_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_silicate,self%id_phyS)
    call self%register_state_variable(self%id_detS,  'detS','mmol-Si/m**3','Detritus Silicon detS', &
       detS_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_silicate,self%id_detS)
end if

if (GrazingOn) then
    call self%register_state_variable(self%id_zooC,  'zooC','mmol-C/m**3','Zooplankton Carbon zooC', &
       zooC_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_zooC)
end if

!!------- Register diagnostic variables  ------- 
call self%register_diagnostic_variable(self%id_chl2,    'chl2','mgCHL/mmolC', 'phyto chl:C ratio', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_fracR,   'fracR','-', ' fracR', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_QN,      'QN','-', ' QN', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_QP,      'QP','-', ' QP', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_aVN,     'aVN','-', ' aVN', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_aVP,     'aVP','-', ' aVP', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_aVSi,    'aVSi','-', ' aVSi', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_rQSi,    'rQSi','-', ' rQSi', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_tmp,     'tmp','-', ' tmp', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_fac1,    'fac1','-', ' fac1', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_fac2,    'fac2','-', ' fac2', &
  output=output_instantaneous)

!!------- Register environmental dependencies  ------- 
call self%register_dependency(self%id_temp,varname_temp)
call self%register_dependency(self%id_par,varname_par)

! extra line included from parser var init_incl 
call maecs_init_stoichvars(self)

return

!!-------  if files are not found ...  
90 call self%fatal_error('maecs_init','Error reading namelist maecs_switch.')
91 call self%fatal_error('maecs_init','Error reading namelist maecs_init.')
92 call self%fatal_error('maecs_init','Error reading namelist maecs_pars.')
93 call self%fatal_error('maecs_init','Error reading namelist maecs_graz.')
94 call self%fatal_error('maecs_init','Error reading namelist maecs_env.')
99 call self%fatal_error('maecs_init','Namelist maecs_switch was not found in file.')
100 call self%fatal_error('maecs_init','Namelist maecs_init was not found in file.')
101 call self%fatal_error('maecs_init','Namelist maecs_pars was not found in file.')
102 call self%fatal_error('maecs_init','Namelist maecs_graz was not found in file.')
103 call self%fatal_error('maecs_init','Namelist maecs_env was not found in file.')

end subroutine initialize

!!----------------------------------------------------------------------
!!   end of section generated by parser 
!!----------------------------------------------------------------------
!#SP#


!documentation for the parser-generated initialize section could be provided here
! @fn fabm_hzg_maecs::initialize()
!


!> @brief to calculate light extinction when kc changes with depth
!> @details extinction coef=\f$ a_{\mathrm{water}} + a_{\mathrm{spm}}* (p+d+z) \f$
   subroutine get_light_extinction(self,_ARGUMENTS_GET_EXTINCTION_)
!  
! !INPUT PARAMETERS:
   class(type_hzg_maecs),intent(in)          :: self 
   _DECLARE_ARGUMENTS_GET_EXTINCTION_
   
   real(rk) :: p,d,z

   ! Enter spatial loops (if any)
   _LOOP_BEGIN_
  
   ! Retrieve current (local) state variable values.  
   _GET_(self%id_phyC,p) ! phytoplankton
   _GET_(self%id_detC,d) ! detritus
   if (self%GrazingOn) then
    _GET_(self%id_zooC, z)  ! Zooplankton Carbon in mmol-C/m**3
   else
    z=0.0_rk 
   end if
   
   ! Self-shading with explicit contribution from background phytoplankton concentration.
   _SET_EXTINCTION_(self%a_water + self%a_spm*(p+d+z))

   ! Leave spatial loops (if any)
   _LOOP_END_

   end subroutine get_light_extinction
!EOC


!> @brief a brief description to be added
!> @details some details to be added
subroutine maecs_init_stoichvars(self)
   class(type_hzg_maecs),intent(inout)          :: self 

!use maecs_types
!implicit none

!type (type_maecs_nutindex) :: ni
real(rk)    :: norder, pb
integer     :: nm

norder = self%NutOrder
nm     = 0
if (norder .gt. 1.) then
  ! --------- nitrogen -------------
  pb     = 10**floor(log10(norder))
  self%nutind%iN  = nint(norder/pb)
  norder = norder - self%nutind%iN * pb
  nm     = nm + 1
  if (norder .gt. 0.99999) then
    !  --------- phosphorus --------- 
    pb     = 10**floor(log10(norder))
    self%nutind%iP  = nint(norder/pb)
    norder = norder - self%nutind%iP * pb
    nm     = nm + 1
    if (norder .gt. 0.99999) then
      !  --------- silicon ----------- 
      pb     = 10**floor(log10(norder))
      self%nutind%iSi = nint(norder/pb)
      norder = norder - self%nutind%iSi * pb
      nm     = nm + 1
    end if
  end if  
else
 self%nutind%iN  = 1
 self%nutind%iP  = 2
 self%nutind%iSi = 3
 nm = 3
endif

! evaluate number of considered limiting nutrients  
self%nutind%nutnum = 1
if (self%PhosphorusOn) then
  self%nutind%nutnum = self%nutind%nutnum + 1
end if

! silicon
if (self%SiliconOn) then
  self%nutind%nutnum = self%nutind%nutnum + 1
end if

! special setting for synchrony dependency on relative quota: nutrient index
nh = nint(10*(self%NutOrder-floor(self%NutOrder))) 
if ( nh .gt. 0 .and. nh .le. nm) then
  self%nutind%nhi = nh  ! element number corr. to first lower digit
else
  self%nutind%nhi = 1  ! default: first element
endif

!write (*,'(A,5(I4))') 'No No N P Si:',nm,self%nutind%nutnum,self%nutind%iN,self%nutind%iP,self%nutind%iSi
 
if (self%nutind%nutnum .gt. nm) call self%fatal_error('maecs_init','Not enough nutrient indices provided by NutOrder.')


end subroutine maecs_init_stoichvars 

#include "maecs_do.F90"

! #include "fabm_driver.h"

!> @brief This is the main routine where right-hand-sides are calculated
!> @details
!> NOTE: Although this subroutine looks as if it's not a part of any module,
!! it is temporarily included in the fabm_hzg_maecs module (inside maecs.F90)
!! when compiling the documentation, such that the subroutine is documented 
!! under the 'Data Type Documentation' chapter, where the in-body docs are listed
!>
!> **Phytoplankton Equations** 
!> \n We distinguish between mass state variables 
!! (in units of carbon, nitrogen, & phosphorus) and property state variables. 
!! \lref{For a textual narration and equations, see sec.,sec:ModStr,.}\n
!>  Current 'traits' are: 
!> - nitrogen allocated to rubisco [-] (frac_Rub) 
!> - Chla content of chloroplasts [chl-a/chl-C] (theta) 
!>
!> **General code structure:**
!> 1. Calculation of quotas, internal states, potential rates
!> 2. Calculation of fluxes, mass exchange rates &  rates of change of traits variables 
!> 3. Assign mass exchange rates ('rhs(j,i)')
!> 4. Assign rates of change of 'traits' property variables
!>
!> \n **Detailed Descriptions:**
! @todo: althougth HIDE_IN_BODY_DOCS=NO, the body-documentation is not included! HAS TO BE FIXED
! @todo: add equations
! @todo: why UNIT instead of secs_pr_day? 
! @todo: 'sensitivities' does not seem to be a proper name choice. Something more intuitive?
subroutine maecs_do(self,_ARGUMENTS_DO_)

use fabm_types
use maecs_types
use maecs_functions
use maecs_primprod 
use maecs_grazing

! !INPUT PARAMETERS:
 class (type_hzg_maecs),intent(in) :: self
   _DECLARE_ARGUMENTS_DO_
type (type_maecs_rhs)    :: rhsv
type (type_maecs_phy)    :: phy   ! phytoplankton type containing state and trait information
type (type_maecs_zoo)    :: zoo   ! zooplankton type 
type (type_maecs_om)     :: dom, det, nut, uptake, exud, lossZ, floppZ, nquot 
type (type_maecs_env)    :: env
type (type_maecs_switch) :: mswitch    
type (type_maecs_traitdyn)::acclim
type (type_maecs_sensitivities) :: sens

! --- LOCAL MODEL VARIABLES:
integer  :: i, j, iz, ihour, iloop
real(rk) :: reminT, degradT       ! Temp dependent remineralisation and hydrolysis rates
! --- QUOTA and FRACTIONS
real(rk) :: phys_status, dQN_dt, dRchl_phyC_dt=0.0_rk ! []

! --- ZOOPLANKTON GRAZING, INGESTION, MORTALITY, RESPIRATION... 
real(rk) :: graz_rate   ! carbon-specific grazing rate                          [d^{-1}]
real(rk) :: zoo_respC   ! temperature dependent carbon respiration rate  [mmolC m^{-3} d^{-1}]
real(rk) :: zoo_mort
real(rk) :: secs_pr_day = 86400.0_rk
! --- AGGREGATION 
real(rk) :: aggreg_rate ! aggregation among phytoplankton and between phytoplankton & detritus [d^{-1}]    
logical  :: out = .true.
!   if(36000.eq.secondsofday .and. mod(julianday,1).eq.0 .and. outn) out=.true.    
#define _KAI_ 0
#define _MARKUS_ 1
! #define UNIT / 86400
#define UNIT *1.1574074074E-5_rk

 _LOOP_BEGIN_
! First retrieve current (local) state  variable values
!#S_GET
!---------- GET for each state variable ----------
  _GET_(self%id_nutN, nut%N)  ! Dissolved Inorganic Nitrogen DIN in mmol-N/m**3
  _GET_(self%id_phyC, phy%C)  ! Phytplankton Carbon in mmol-C/m**3
  _GET_(self%id_phyN, phy%N)  ! Phytplankton Nitrogen in mmol-N/m**3
  _GET_(self%id_detC, det%C)  ! Detritus Carbon in mmol-C/m**3
  _GET_(self%id_detN, det%N)  ! Detritus Nitrogen in mmol-N/m**3
  _GET_(self%id_domC, dom%C)  ! Dissolved Organic Carbon in mmol-C/m**3
  _GET_(self%id_domN, dom%N)  ! Dissolved Organic Nitrogen in mmol-N/m**3
if (self%RubiscoOn) then
      _GET_(self%id_Rub, phy%Rub)  ! fraction of Rubisco in -
end if
if (self%PhotoacclimOn) then
      _GET_(self%id_chl, phy%chl)  ! Chl:C ratio in mg-Chla/mmol-C
end if
if (self%PhosphorusOn) then
      _GET_(self%id_nutP, nut%P)  ! Dissolved Inorganic Phosphorus DIP in mmol-P/m**3
      _GET_(self%id_phyP, phy%P)  ! Phytplankton Phosphorus in mmol-P/m**3
      _GET_(self%id_detP, det%P)  ! Detritus Phosphorus in mmol-P/m**3
      _GET_(self%id_domP, dom%P)  ! Dissolved Organic Phosphorus in mmol-P/m**3
end if
if (self%SiliconOn) then
      _GET_(self%id_nutS, nut%Si)  ! Dissolved Inorganic Silicon Si in mmol-Si/m**3
      _GET_(self%id_phyS, phy%Si)  ! Phytplankton Silicon in mmol-Si/m**3
      _GET_(self%id_detS, det%Si)  ! Detritus Silicon in mmol-Si/m**3
end if
if (self%GrazingOn) then
      _GET_(self%id_zooC, zoo%C)  ! Zooplankton Carbon in mmol-C/m**3
end if
!#E_GET
if (.not. self%GrazingOn) then
      zoo%C = self%zooC_initial
end if

!phy%Rub = Rub
!phy%chl = chl
! Retrieve current environmental conditions.
!#S_GED
  _GET_(self%id_temp, env%temp)  ! water temperature
  _GET_(self%id_par, env%par)  ! light photosynthetically active radiation
!#E_GED


! @ingroup main
!> @fn fabm_hzg_maecs::maecs_do () 
!> 1. Calculation of quotas, internal states, potential rates
!>   - call min_mass with method=2, store phy\%C and \%N in phy\%reg 
!>   - call calc_internal_states: retrieve phy\%Q\%X, phy\%theta, phy\%frac\%X 
!>   - if PhotoacclimOn=.false., calculate: 
!>     - phy\%chl=phy\%C * self\%frac_chl_ini 
!>     - phy\%frac\%theta = self\%frac_chl_ini * self\%itheta_max
!>     - phy\%theta= self\%frac_chl_ini / (self\%frac_Rub_ini * phy\%relQ\%N**self\%sigma)
!>   - call calc_sensitivities: retrieve potential rates: @f$f_T@f$, sens\%upt\_pot\%C (=LH), sens\%upt\_pot\%X (= @f$ V_X @f$), sens\%P\_max
!> @todo: min_mass correction of phy%\C and phy\%N at this stage requires specification of threshold values. What about back-calculating phy\%reg\%N from the smooth_small corrected phy\%Q\%N?

! --- checking and correcting extremely low state values  ------------  
call min_mass(self,phy,method=2) !_KAI_ minimal reasonable Phy-C and -Nitrogen

! --- stoichiometry of autotrophs (calculating QN_phy, frac_R, theta, and QP_phy)
call calc_internal_states(self,phy,det,dom,zoo)

!write (*,'(A,2(F10.3))') 'PAR, chl=',env%par, phy%chl

if (.not. self%PhotoacclimOn) then  
   phy%chl         = phy%C * self%frac_chl_ini   ! total Chl mg-CHL/m3
   phy%frac%theta  = self%frac_chl_ini * self%itheta_max
   phy%theta       = self%frac_chl_ini /(self%frac_Rub_ini*phy%relQ%N**self%sigma)
! g-CHL/mol-C*m3
! write (*,'(A,2(F10.3))') 'theta:',phy%relQ%N**self%sigma,phy%theta   
end if 

call calc_sensitivities(self,sens,phy,env,nut)


!> @fn fabm_hzg_maecs::maecs_do ()
!> 2. Calculation of fluxes, mass exchange rates &  rates of change of traits variables 
!! & Specify rates of change of traits variables
!>   - call maecs_primprod::photosynthesis(): this is where everything happens!
!>   - if GrazingOn: 
!>     - graz\_rate=rate retrieved from call maecs_grazing::grazing()
!>     - lossZ\%X=lossZNut\%X, floppZ\%X=lossZDet\%X retrieved from call maecs_grazing::grazing_losses()
!>     - calculate graz_rate retr= graz_rate * zoo\%C and zoo_mort
!>   - calc. aggreg_rate @f$ = \mathrm{phi\_agg}*(1-e^{-0.02*\mathrm{dom\%C}}) * phy\%N *det\%N @f$
!>     - future work: aggreg_rate=f(size), \latexonly (see section \ref{sec:partagg}) \endlatexonly \n
!>   - calc. degradT=self\%hydrol * @f$ f_T @f$ and reminT=self\%remin * @f$ f_T @f$
!> @todo: specific graz_rate becomes pop. grazing rate. Do this at the rhs calculations
!> @todo: graz_rate: no temperature modification: forgotten?

! --- ALGAL GROWTH and EXUDATION RATES, physiological trait dynamics ----------------
call photosynthesis(self,sens,phy,uptake,exud,acclim)


! ----------------       grazing        -------------------------------------------
if (self%GrazingOn) then
  call grazing(self%g_max * sens%f_T,self%k_grazC,phy%C,graz_rate)
  zoo%feeding = graz_rate
  zoo_respC   = self%basal_resp_zoo * sens%f_T  !  basal respiration of grazers
  nquot       = type_maecs_om(1.0_rk, phy%Q%N, phy%Q%P, phy%Q%Si )
  mswitch     = type_maecs_switch(self%PhosphorusOn,self%SiliconOn,.true. )
! --- calculates zooplankton loss rates (excretion->Nut, floppy+egestion->Det), specific to C
  call grazing_losses(zoo,zoo_respC,nquot,lossZ,floppZ, mswitch) 
!  --- transform from specific to bulk grazing rate
  graz_rate   = graz_rate * zoo%C 
!  --- quadratic closure term
  zoo_mort    = self%mort_zoo * sens%f_T  * zoo%C

else
  graz_rate   = 0.0_rk
  zoo_mort    = 0.0_rk
  lossZ       = type_maecs_om(0.0_rk, 0.0_rk, 0.0_rk, 0.0_rk)
  floppZ      = type_maecs_om(0.0_rk, 0.0_rk, 0.0_rk, 0.0_rk)
end if

! --- phytoplankton aggregation -------------------------------------------------
! If biovolume is primarily determined by the nitrogen content, also for detritus
!aggreg_rate = self%phi_agg * dom%C * (phy%N + det%N)                    ! [d^{-1}] 

!_GET_(self%id_fracR,phys_status )  
!write (*,'(A,1(F10.3))') 'phys=',phys_status

aggreg_rate = self%phi_agg * (1.0_rk - exp(-0.02*dom%C)) * (phy%N + det%N) 
!         vS * exp(-4*phys_status )                ! [d^{-1}] 
!aggreg_rate = aggreg_rate * exp(-4*phy%rel_phys ) 

! ------------------------------------------------------------------
!  ---  hydrolysis & remineralisation rate (temp dependent)
degradT     = self%hydrol * sens%f_T
reminT      = self%remin  * sens%f_T


!> @fn fabm_hzg_maecs::maecs_do ()
!> 3. Assign mass exchange rates ('rhs(j,i)')
!>   - phyC= uptake - dil - exud - aggreg\_rate - graz\_rate
!> @todo: add the rhs equations


! right hand side of ODE (rhs)    
!  #define UNIT /self%secs_pr_day
!__________________________________________________________________________
!
! PHYTOPLANKTON C
rhsv%phyC = uptake%C              * phy%C &
           - self%dil             * phy%C &
           - exud%C               * phy%C &  !TODO: move loss rates to mu, also checking for 
           - aggreg_rate          * phy%C &  !      trait dependencies
           - graz_rate                    

! write (*,'(A,3(F9.4))') 'flxc=',uptake%C, phy%C,nut%P 
! write (*,'(A,3(F9.4))') 'c=',phy%chl,phy%Rub, phy%C

!_____________________________________________________________________________
!
! PHYTOPLANKTON N
rhsv%phyN =  uptake%N             * phy%C &
           - exud%N               * phy%C & 
           - aggreg_rate          * phy%N &
           - self%dil             * phy%N &          
           - graz_rate * phy%Q%N       
   
!rhsv%phyN = 0.0_rk

!_____________________________________________________________________________

!> @fn fabm_hzg_maecs::maecs_do ()
!> 4. Assign rates of change of 'traits' property variables
!>    - if PhotoacclimOn: rhsv%chl
!>    - if RubiscoOn: rhsv%Rub
!> @todo: add the rhs equations

if (self%PhotoacclimOn) then
! PHYTOPLANKTON CHLa
     ! note that theta*rel_chloropl in units [mg Chla (mmol C)^{-1}] 
   dQN_dt        = (rhsv%phyN * phy%reg%C - rhsv%phyC * phy%reg%N) / (phy%reg%C*phy%reg%C)
! TODO: dangerous to work with RHS instead of net uptake rates (mortality has no physiological effect)

   dRchl_phyC_dt =  acclim%dRchl_dtheta * acclim%dtheta_dt   & 
                  + acclim%dRchl_dfracR * acclim%dfracR_dt   & 
                  + acclim%dRchl_dQN    * dQN_dt 

   rhsv%chl = phy%theta * phy%frac%Rub * phy%relQ%N**self%sigma * rhsv%phyC + dRchl_phyC_dt * phy%C

!write (*,'(A,4(F10.3))') 'rhs chl=', phy%theta * phy%frac%Rub * phy%relQ%N**self%sigma * rhsv%phyC,dRchl_phyC_dt * phy%reg%C*1E1,phy%relQ%N**self%sigma,phy%theta

!_____________________________________________ _________________________________
end if 

if (self%RubiscoOn) then 
   rhsv%Rub  = acclim%dfracR_dt * phy%C + phy%Rub/phy%reg%C * rhsv%phyC 
end if 

!________________________________________________________________________________
!
! ZOOPLANKTON zoo%feeding
if (self%GrazingOn) then  
   rhsv%zooC   =  zoo%yield * graz_rate       &
                - zoo_mort          * zoo%C   &
                - self%dil          * zoo%C   &         
                - lossZ%C           * zoo%C
else
   rhsv%zooC      = 0.0_rk
end if 
!________________________________________________________________________________
!
!  --- DETRITUS C
rhsv%detC   =  floppZ%C             * zoo%C   &
             + aggreg_rate          * phy%C   &
             + zoo_mort             * zoo%C   &
             - self%dil             * det%C   &             
             - degradT              * det%C                

!________________________________________________________________________________
!
!  --- DETRITUS N
rhsv%detN   = floppZ%N              * zoo%C   &
             + aggreg_rate          * phy%N   &
             - self%dil             * det%N   &
             + zoo_mort             * zoo%N   & 
             - degradT              * det%N 
!________________________________________________________________________________
!
!  --- DOC
rhsv%domC   = exud%C                * phy%C   & 
             + degradT              * det%C   &
             - self%dil             * dom%C   &        
             - reminT               * dom%C 
!________________________________________________________________________________
!
!  --- DON
rhsv%domN   = exud%N                * phy%C   &
             + degradT              * det%N   &
             - self%dil             * dom%N   &         
             - reminT               * dom%N
!________________________________________________________________________________
!
! DIC
!if (self%BioCarbochemOn) then
!  rhsv%dic     = -uptake%grossC      * phy%C   &
!                + uptake%lossC       * phy%C   &
!                + reminT             * dom%C   & 
!                + lossZ%C            * zoo%C
!
!_SET_ODE_(self%id_dic,rhsv%dic UNIT)
!end if
!________________________________________________________________________________
!
!  --- DIN
rhsv%nutN   = -uptake%N            * phy%C    &
             + reminT              * dom%N    &
             + lossZ%N             * zoo%C    &
             + self%dil * (self%nutN_initial - nut%N)
!________________________________________________________________________________
!
if (self%PhosphorusOn) then 
  ! ---  PHYTOPLANKTON P
   rhsv%phyP = uptake%P              * phy%C    & 
              - exud%P               * phy%C    & 
              - self%dil             * phy%P    &            
              - aggreg_rate          * phy%P    & 
              - graz_rate            * phy%Q%P    
  !  --- DETRITUS P 
   rhsv%detP = floppZ%P              * zoo%C    &
              + aggreg_rate          * phy%P    &
              - self%dil             * det%P    &         
              + zoo_mort             * zoo%P    & 
              - degradT              * det%P
  !  --- DOP
   rhsv%domP = exud%P                * phy%C    &
              + degradT              * det%P    &
              - self%dil             * dom%P    &              
              - reminT               * dom%P
  !  --- DIP
   rhsv%nutP = - uptake%P            * phy%C    & 
              + reminT               * dom%P    & 
              + lossZ%P              * zoo%C    &
              + self%dil * (self%nutP_initial - nut%P)
end if 
!________________________________________________________________________________
!
if (self%SiliconOn) then 
  ! ---  PHYTOPLANKTON Si
   rhsv%phyS = uptake%Si              * phy%C    & 
              - self%dil             * phy%Si    &            
              - aggreg_rate          * phy%Si    & 
              - graz_rate            * phy%Q%Si    
  !  --- DETRITUS Si
   rhsv%detS = floppZ%Si              * zoo%C    &
              + aggreg_rate          * phy%Si    &
              - self%dil             * det%Si    &         
              - degradT              * det%Si
  !  --- Dissolved Si
   rhsv%nutS = - uptake%Si            * phy%C    & 
              + degradT              * det%Si    & 
              + lossZ%Si              * zoo%C    &
              + self%dil * (self%nutS_initial - nut%Si)

end if 

!#S_ODE
!---------- ODE for each state variable ----------
  _SET_ODE_(self%id_nutN, rhsv%nutN UNIT)
  _SET_ODE_(self%id_phyC, rhsv%phyC UNIT)
  _SET_ODE_(self%id_phyN, rhsv%phyN UNIT)
  _SET_ODE_(self%id_detC, rhsv%detC UNIT)
  _SET_ODE_(self%id_detN, rhsv%detN UNIT)
  _SET_ODE_(self%id_domC, rhsv%domC UNIT)
  _SET_ODE_(self%id_domN, rhsv%domN UNIT)
if (self%RubiscoOn) then
      _SET_ODE_(self%id_Rub, rhsv%Rub UNIT)
end if
if (self%PhotoacclimOn) then
      _SET_ODE_(self%id_chl, rhsv%chl UNIT)
end if
if (self%PhosphorusOn) then
      _SET_ODE_(self%id_nutP, rhsv%nutP UNIT)
      _SET_ODE_(self%id_phyP, rhsv%phyP UNIT)
      _SET_ODE_(self%id_detP, rhsv%detP UNIT)
      _SET_ODE_(self%id_domP, rhsv%domP UNIT)
end if
if (self%SiliconOn) then
      _SET_ODE_(self%id_nutS, rhsv%nutS UNIT)
      _SET_ODE_(self%id_phyS, rhsv%phyS UNIT)
      _SET_ODE_(self%id_detS, rhsv%detS UNIT)
end if
if (self%GrazingOn) then
      _SET_ODE_(self%id_zooC, rhsv%zooC UNIT)
end if
!#E_ODE


!________________________________________________________________________________
! set diag variables, mostly from PrimProd module ______________
!#S_DIA
  _SET_DIAGNOSTIC_(self%id_chl2, phy%theta*phy%rel_chloropl) !mgchl/mmolC, ! note that theta*rel_chloropl in units [mg Chla (mmol C)^{-1}] 
  _SET_DIAGNOSTIC_(self%id_fracR, phy%frac%Rub)             !last 
  _SET_DIAGNOSTIC_(self%id_QN, phy%Q%N)                     !last 
  _SET_DIAGNOSTIC_(self%id_QP, phy%Q%P)                     !last 
  _SET_DIAGNOSTIC_(self%id_aVN, acclim%aV%N)                !last 
  _SET_DIAGNOSTIC_(self%id_aVP, acclim%aV%P)                !last 
  _SET_DIAGNOSTIC_(self%id_aVSi, acclim%aV%Si)              !last 
  _SET_DIAGNOSTIC_(self%id_rQSi, phy%frac%NutUpt )       !+0*phy%relQ%Silast 
  _SET_DIAGNOSTIC_(self%id_tmp, acclim%tmp)                 !last 
  _SET_DIAGNOSTIC_(self%id_fac1, acclim%fac1)               !last 
  _SET_DIAGNOSTIC_(self%id_fac2, acclim%fac2)               !last 
!#E_DIA

if (self%DebugDiagOn) then
!   _SET_DIAG_(self%id_chl_diag, phy%theta * phy%rel_chloropl ) !* phy%C
!   _SET_DIAG_(self%id_fracR, phy%frac%Rub) 
!   _SET_DIAG_(self%id_fracTheta, phy%frac%theta)
!   _SET_DIAG_(self%id_fracQN, phy%Q%N)
!   _SET_DIAG_(self%id_fracQP, phy%Q%P*1.0d3)
!   _SET_DIAG_(self%id_reg_VNC, uptake%N)
!   _SET_DIAG_(self%id_fac1,uptake%P  ) acclim%fac1
!   _SET_DIAG_(self%id_fac2,exud%P )
!   _SET_DIAG_(self%id_tmp,lossZ%P ) 

!   _SET_DIAG_(self%id_flxC, uptake%C*phy%C - reminT*dom%C- self%dil*totalC - lossZ%C*zoo%C) 
!   _SET_DIAG_(self%id_flxC,rhsv%phyP ) 

!   _SET_DIAG_(self%id_totC,totalC) 
!   _SET_DIAG_(self%id_totN, totalN) 
!   _SET_DIAG_(self%id_fac1, totalN - self%budget_N) 
!   if (self%PhosphorusOn) then
!     _SET_CONSERVED_QUANTITY_(self%id_totP,dip+phy%P+det%P+dom%P+zoo%P) 
!     _SET_DIAG_(self%id_totP,totalP) 
!     _SET_DIAG_(self%id_fac2, totalP - self%budget_P) 
!     _SET_DIAG_(self%id_fac1,floppZ%P*zoo%C) 
!     _SET_DIAG_(self%id_fac2,lossZ%P*zoo%C)   end if

end if

  _LOOP_END_

end subroutine maecs_do

!> @brief handles vertical movement for depth-varying movement rates
!> @details phyto sinking rate depends on the nutritional state, so for each node:
!! \n \f$ phy\%relQ \f$ obtained by calling calc_internal_states(self,phy,det,dom,zoo) 
!! \n then \f$ phyQstat=phy\%relQ\%N * phy\%relQ\%P \f$
!! \n finally, vsink = maecs_functions::sinking(self\%vS_phy, phyQstat, vsink)
subroutine maecs_get_vertical_movement(self,_ARGUMENTS_GET_VERTICAL_MOVEMENT_)

use maecs_functions
use maecs_types

implicit none
!
! !INPUT PARAMETERS:
 class (type_hzg_maecs),intent(in) :: self
_DECLARE_ARGUMENTS_GET_VERTICAL_MOVEMENT_ 
 !   REALTYPE, intent(in)              ::vstokes 
type (type_maecs_phy):: phy !< maecs phytoplankton type
type (type_maecs_zoo) :: zoo
type (type_maecs_om):: det
type (type_maecs_om):: dom

!
! !LOCAL VARIABLES: 
REALTYPE    :: phyQstat,vsink
REALTYPE, parameter :: secs_pr_day = 86400.d0 
!EOP
!-----------------------------------------------------------------------
!BOC

_FABM_LOOP_BEGIN_
   
   ! Retrieve phtoplankton state
   
   !Retrieve the 'phyQstat' directly as a diagnostic variable: does not work yet.
   !fabm_get_bulk_diagnostic_data(self%id_phyqstat,phyQstatD) !where, phyQstat=relQ%N*relQ%P
   !_GET_(self%id_phyqstat,phyQstatD)
   
   !Calculate manually
   _GET_(self%id_phyC, phy%C)  ! Phytplankton Carbon in mmol-C/m**3
   _GET_(self%id_phyN, phy%N)  ! Phytplankton Nitrogen in mmol-N/m**3
   if (self%GrazingOn) then
     _GET_(self%id_zooC, zoo%C)  ! Zooplankton Carbon in mmol-C/m**3
   end if
   if (self%PhosphorusOn) then
     _GET_(self%id_phyP, phy%P)  ! Phytplankton Phosphorus in mmol-P/m**3
   end if

   !write (*,'(A,2(F10.3))') 'Before: phy%C, phy%N=', phy%C, phy%N
   call min_mass(self,phy,method=2) 
   !write (*,'(A,2(F10.3))') 'After: phy%C, phy%N=', phy%C, phy%N
   call calc_internal_states(self,phy,det,dom,zoo) 
   !write (*,'(A,2(F10.3))') 'phy%relQ%N, phy%relQ%P=', phy%relQ%N, phy%relQ%P
   
   !calculate Q state
   phyQstat = phy%relQ%N * phy%relQ%P 

  
   ! Calculate sinking

   call sinking(self%vS_phy, phyQstat, vsink)
   vsink = vsink / secs_pr_day
   !write (*,'(A,2(F10.3))') 'phyQstat, vsink=', phyQstat, vsink
   
   !set the rates
   _SET_VERTICAL_MOVEMENT_(self%id_detC,-1.0_rk*self%vS_det/secs_pr_day)
   _SET_VERTICAL_MOVEMENT_(self%id_detN,-1.0_rk*self%vs_det/secs_pr_day)

   _SET_VERTICAL_MOVEMENT_(self%id_phyN,vsink)
   _SET_VERTICAL_MOVEMENT_(self%id_phyC,vsink)
   if (self%PhosphorusOn) then
      _SET_VERTICAL_MOVEMENT_(self%id_phyP,vsink)
      _SET_VERTICAL_MOVEMENT_(self%id_detP,-1.0_rk*self%vs_det/secs_pr_day)
   end if
   if (self%SiliconOn) then
      _SET_VERTICAL_MOVEMENT_(self%id_phyS,vsink)
      _SET_VERTICAL_MOVEMENT_(self%id_detS,-1.0_rk*self%vs_det/secs_pr_day)
   end if
   if (self%PhotoacclimOn) then 
      _SET_VERTICAL_MOVEMENT_(self%id_chl,vsink)
      _SET_VERTICAL_MOVEMENT_(self%id_Rub,vsink)
   end if
  
_FABM_LOOP_END_
  
end subroutine maecs_get_vertical_movement
end module fabm_hzg_maecs
