!> @file maecs_types.F90
!> @brief maecs_types module
!> @author Richard Hofmeister, Kai Wirtz

#include "fabm_driver.h"

!> @brief  Data types used in fabm_hzg_maecs are defined here
!> @details 
!> todo: we should consider including parameter tables for some maecs types.
!! Parser could do it just like in the initialize subroutine. 
! by adding:
! \\describepar{model_par, symbol, : some description}
! lines before each type 
module maecs_types

use fabm_types
use fabm_expressions

public type_maecs_sensitivities, type_maecs_om, &
       type_maecs_traitdyn, type_maecs_phy, type_maecs_zoo, &
       type_maecs_allocation_fractions

type type_maecs_nutindex
   integer :: iN, iP, iSi, iFe
   integer :: nutnum, nhi   
   integer :: nfV, nSRN
end type
! standard fabm model types
type,extends(type_base_model),public :: type_maecs_base_model
type (type_maecs_nutindex) :: nutind

!#SP0
!!----------------------------------------------------------------------
!! this code is generated by a parser  (conv_nml_fabm.c by kai wirtz)
!!----------------------------------------------------------------------
! standard fabm model types
type (type_state_variable_id)        :: id_nutN,id_nutP,id_nutS,id_nutFe,id_phyC,id_phyN,id_phyP,id_phyS,id_phyFe,id_zooC,id_detC,id_detN,id_detP,id_detS,id_detFe,id_domC,id_domN,id_domP,id_RNit,id_Rub,id_chl,id_nh3,id_oxy,id_odu,id_vir
type (type_dependency_id)            :: id_temp
type (type_dependency_id)            :: id_par
type (type_dependency_id)            :: id_CO2
type (type_dependency_id)            :: id_attpar
type (type_global_dependency_id)     :: id_doy
type (type_horizontal_dependency_id) :: id_lat, id_lon
type (type_dependency_id)            :: id_sal

type (type_dependency_id)            :: id_totC
type (type_horizontal_dependency_id)            :: id_totC_vertint
type (type_dependency_id)            :: id_totN
type (type_horizontal_dependency_id)            :: id_totN_vertint
type (type_dependency_id)            :: id_vphys_dep
type (type_dependency_id)            :: id_GPPR_dep
type (type_horizontal_dependency_id)            :: id_GPPR_vertint
type (type_horizontal_diagnostic_variable_id)            :: id_GPPR_vertint_diag
type (type_dependency_id)            :: id_Denitr_dep
type (type_horizontal_dependency_id)            :: id_Denitr_vertint
type (type_horizontal_diagnostic_variable_id)            :: id_Denitr_vertint_diag
type (type_dependency_id)            :: id_totP
type (type_horizontal_dependency_id)            :: id_totP_vertint
type (type_dependency_id)            :: id_totS
type (type_horizontal_dependency_id)            :: id_totS_vertint
type (type_dependency_id)            :: id_totFe
type (type_horizontal_dependency_id)            :: id_totFe_vertint
type (type_horizontal_diagnostic_variable_id)            :: id_totC_vertint_diag
type (type_horizontal_diagnostic_variable_id)            :: id_totN_vertint_diag
type (type_horizontal_diagnostic_variable_id)            :: id_totP_vertint_diag
type (type_horizontal_diagnostic_variable_id)            :: id_totS_vertint_diag
type (type_horizontal_diagnostic_variable_id)            :: id_totFe_vertint_diag

type (type_horizontal_dependency_id)            :: id_zmax
type (type_horizontal_dependency_id) :: id_o2flux, id_oduflux
type (type_horizontal_dependency_id) :: id_tke_bot
type (type_horizontal_diagnostic_variable_id)            :: id_O2flux_diag
type (type_diagnostic_variable_id)   :: id_pPads, id_datt, id_vphys, id_GPPR, id_Denitr, id_dPAR, id_chl2C, id_Theta, id_fracR, id_fracT, id_fracNU, id_DNP, id_QNP, id_QN, id_QP, id_QSi, id_QFe, id_aVN, id_aVP, id_aVSi, id_aVFe, id_faN, id_faP, id_faSi,id_faFe, id_rQN, id_rQP, id_rQSi, id_rQFe, id_tmp, id_fac4, id_fac5, id_fac3, id_fac1, id_fac2, id_phyUR, id_phyRER, id_phyELR, id_phyALR, id_phyVLR, id_phyGLR, id_vsinkr, id_zoomort, id_qualPOM, id_qualDOM, id_no3
real(rk) ::  nutN_initial, nutP_initial, nutS_initial, nutFe_initial, phyC_initial, phyN_initial, phyP_initial, phyS_initial,phyFe_initial, zooC_initial, detC_initial, detN_initial, detP_initial, detS_initial,detFe_initial, domC_initial, domN_initial, domP_initial, RNit_initial, frac_Rub_ini, frac_chl_ini, nh3_initial, oxy_initial, odu_initial, vir_initial
real(rk) ::  P_max, alpha, sigma, theta_LHC, rel_chloropl_min, QN_phy_0, QN_phy_max, V_NC_max, AffN, zeta_CN, zstoich_PN, exud_phy, QP_phy_0, QP_phy_max, V_PC_max, AffP, QSi_phy_0, QSi_phy_max, V_SiC_max, AffSi, QFe_phy_0, QFe_phy_max, V_FeC_max, AffFe,MaxRelQ, syn_nut, adap_rub, adap_theta, tau_regV, disease, mort_ODU, decay_pigm, decay_nut, phi_agg, agg_doc, vir_loss, vir_mu, vir_infect, vir_phyC, vir_spor_r, vir_spor_C, sink_phys, vS_phy, vS_det, hydrol, remin, Nqual, remNP, denit, PON_denit, Q10, T_ref, NutOrder
real(rk) ::  const_NC_zoo, const_PC_zoo, g_max, k_grazC, yield_zoo, basal_resp_zoo, mort_zoo, zm_fa_delmax, zm_fa_inf, fT_exp_mort
real(rk) ::  a_water, a_minfr, a_spm, a_phyc, a_doc, a_fz, a_chl, rel_co2, frac_PAR, small, maxVal, dil, ex_airsea, O2_sat, N_depo, P_depo
real(rk) ::  rPAds, PAdsODU, rnit, ksO2nitri, rODUox, ksO2oduox, ksO2oxic, ksNO3denit, kinO2denit, kinNO3anox, kinO2anox, rAnammox
real(rk) ::  rq10, res0, K_QN_phy, iK_QN, iK_QP, iK_QSi, iK_QFe, itheta_max, aver_QN_phy, aver_QP_phy, small_finite
logical  ::  RubiscoOn, PhotoacclimOn, PhosphorusOn, SiliconOn, IronOn, GrazingOn, BioOxyOn, DebugDiagOn, Budget0DDiagOn, Budget2DDiagOn, BGC0DDiagOn, BGC2DDiagOn, PhysiolDiagOn, RateDiagOn, ChemostatOn, VirusOn, SwitchOn, NResOn, detritus_no_river_dilution, plankton_no_river_dilution, nutrient_no_river_dilution
integer  ::  GrazTurbOn, kwFzmaxMeth, genMeth
end type type_maecs_base_model

!
type type_maecs_env
 real(rk) :: RNit, nh3, oxy, odu,  temp,par,CO2,attpar,doy,vphys_dep,GPPR_dep,GPPR_vertint,GPPR_vertint_diag,Denitr_dep,Denitr_vertint,Denitr_vertint_diag,zmax,O2flux_diag
end type
type type_maecs_rhs
 real(rk) :: nutN,nutP,nutS,nutFe,phyC,phyN,phyP,phyS,phyFe,zooC,detC,detN,detP,detS,detFe,domC,domN,domP,RNit,Rub,chl,nh3,oxy,odu,vir
end type
! standard fabm model types
!#SP#

!!-------------------------------------------------------------------
type type_maecs_switch
   logical :: isP, isSi, isFe, isTotIng
end type


type type_maecs_om
   real(rk) :: C,N,P,Si,Fe
end type

type type_maecs_basic_traits ! traits that apply to all -planktonic- life forms
   real(rk) :: lESD, vESD
   real(rk) :: trophy
end type

type type_maecs_allocation_fractions
   real(rk) :: Rub
   real(rk) :: theta
   real(rk) :: NutUpt ! remaining nitrogen fraction for uptake and processing            [dimensionless]
   real(rk) :: TotFree ! nitrogen fraction of free/available proteins/enzymes and RNA    [dimensionless]
end type

type,extends(type_maecs_om) :: type_maecs_life
      type (type_maecs_om)            :: Q       ! quotaformer QN,QP,QPN
      type (type_maecs_basic_traits)  :: tr
      real(rk)   :: resp                         ! respiration rate 
end type type_maecs_life

type,extends(type_maecs_life) :: type_maecs_phy
      type (type_maecs_om) :: relQ   ! former rel_QN, rel_QP, rel_QNP
      type (type_maecs_om) :: reg    ! former C_reg, N_reg, P_reg
      real(rk)   :: chl, Rub
      real(rk)   :: vir
      real(rk)   :: rel_chloropl
      real(rk)   :: theta
      real(rk)   :: relax     ! relaxation at too low biomass
!      real(rk)   :: rel_phys ! physiological/energy/nutritional status 0...1
      real(rk)   :: gpp ! gross primary production
      type (type_maecs_allocation_fractions) :: frac
end type type_maecs_phy


type,extends(type_maecs_life) :: type_maecs_zoo
      real(rk)   :: yield,flopp
      real(rk)   :: feeding
end type type_maecs_zoo

! Time and Chl derivatives of trait variables
type type_maecs_traitdyn
      real(rk)   :: dtheta_dt
      real(rk)   :: dfracR_dt
      real(rk)   :: dRchl_dtheta
      real(rk)   :: dRchl_dfracR 
      real(rk)   :: dRchl_dQN
      type (type_maecs_om) :: aV !instantaneously optimized trait: activity
      type (type_maecs_om) :: fA !instantaneously optimized trait: large fA-> affinity (i.e., uptake sites) vs small fA-> Vmax (i.e., transport)
      real(rk)   :: tmp,fac1,fac2,fac3,fac4  ! for volatile diagnostics
!      type (type_maecs_om) :: dV_dfracR, dV_dtheta
end type
                                       

type type_maecs_sensitivities
   real(rk) :: f_T,f_T2       ! temperature dependency of metabolic rates
   real(rk) :: P_max_T  ! temperature dependent maximum photosynthetic rate                        [d^{-1}]
   real(rk) :: a_light  ! exponent of light limitation 'upt_pot%C'                             [dimensionless]
   type (type_maecs_om) :: upt_pot ! potential uptake rates
				   ! depending on ambient concentration incl. light limitation [dimensionless]
end type type_maecs_sensitivities

! new meta structure for pointing/looping over elements
type stoich_pointer
   real(rk),pointer  :: upt, upt_act, upt_pot
   real(rk),pointer  :: aV
   real(rk)          :: relQ, Q
   real(rk)          :: iKQ, dmudaV, dmudV
end type stoich_pointer

end module

!!----------------------------------------------------------------------
!! end of section generated by a parser 
