! @file maecs.F90 

#include "fabm_driver.h"

!> @brief This is the module registered in FABM
!> @details all the maecs_types are made available to this module
!! @todo cross-check the new units and long names of id_Rub (bulk), id_chl (bulk), id_chl2 (diag, chl:c ratio) 
module hzg_maecs
use fabm_types
use fabm_standard_variables
use maecs_types

#define _DEBUG_ 0
#define DOUTa output_time_step_averaged
!#define DOUT time_integrated
!#define DOUT output_time_step_integrated
#define DOUT output_instantaneous

!implicit none

private

public type_maecs_env,type_maecs_rhs
! --- HZG model types


! standard fabm model types

!> @brief this is the model type FABM uses to create the mode
! @defgroup main main_model_members
! @name //@{ //@}
!> @details the parent type (type_maecs_base_model) was defined in maecs_types module
type,extends(type_maecs_base_model),public :: type_hzg_maecs 
 contains
  procedure :: initialize 
  procedure :: do => maecs_do
  procedure :: do_surface => maecs_do_surface
  procedure :: get_light_extinction
  procedure :: get_vertical_movement=>maecs_get_vertical_movement
end type type_hzg_maecs

!interface
  ! @brief @brief interface for the external procedure contained in maecs_main module
  ! @details phyto sinking rate depends on the nutritional state, so for each node:
  ! \n \f$ phy\%relQ \f$ obtained by calling calc_internal_states(self,phy,det,dom,zoo) 
  ! \n then \f$ phyQstat=phy\%relQ\%N * phy\%relQ\%P \f$
  ! \n finally, vsink = maecs_functions::sinking(self\%vS_phy, phyQstat, vsink)
!   subroutine maecs_get_vertical_movement(self, _ARGUMENTS_GET_VERTICAL_MOVEMENT_) 
!   import type_hzg_maecs,type_environment,rk
!   class (type_hzg_maecs),intent(in) :: self
!   _DECLARE_ARGUMENTS_GET_VERTICAL_MOVEMENT_
!   end subroutine
! end interface

!#SP0
!!----------------------------------------------------------------------
!! this code is generated by a parser  (conv_nml_fabm.c by kai wirtz)
!!----------------------------------------------------------------------
! --- HZG model types
!!--------------------------------------------------------------------

contains
!> @brief initializes the model
!! @details here the maecs namelists are read and assigned respectively in the model type (self),
!! state & diagnostic variables are registered in FABM and dependencies are imported from FABM
!>
!> **Model parameters, descriptions and corresponding symbols used in formulas:**
! initial values
!> \describepar{nutN\_initial , \mathrm{nutN_initial} , Dissolved Inorganic Nitrogen DIN, 30 mmol-N/m**3}
!> \describepar{nutP\_initial , \mathrm{nutP_initial} , Dissolved Inorganic Phosphorus DIP, 1.4 mmol-P/m**3}
!> \describepar{nutS\_initial , \mathrm{nutS_initial} , Dissolved Inorganic Silicon Si, 140 mmol-Si/m**3}
!> \describepar{phyC\_initial , \mathrm{phyC_initial} , Phytplankton Carbon, 5 mmol-C/m**3}
!> \describepar{phyN\_initial , \mathrm{phyN_initial} , Phytplankton Nitrogen, 1 mmol-N/m**3}
!> \describepar{phyP\_initial , \mathrm{phyP_initial} , Phytplankton Phosphorus, 0.1 mmol-P/m**3}
!> \describepar{phyS\_initial , \mathrm{phyS_initial} , Phytplankton Silicon, 2. mmol-Si/m**3}
!> \describepar{zooC\_initial , \mathrm{zooC_initial} , Zooplankton Carbon, 1. mmol-C/m**3}
!> \describepar{detC\_initial , \mathrm{detC_initial} , Detritus Carbon, 1. mmol-C/m**3}
!> \describepar{detN\_initial , \mathrm{detN_initial} , Detritus Nitrogen, 0.1 mmol-N/m**3}
!> \describepar{detP\_initial , \mathrm{detP_initial} , Detritus Phosphorus, 0.01 mmol-P/m**3}
!> \describepar{detS\_initial , \mathrm{detS_initial} , Detritus Silicon, 0. mmol-Si/m**3}
!> \describepar{domC\_initial , \mathrm{domC_initial} , Dissolved Organic Carbon, 1.0 mmol-C/m**3}
!> \describepar{domN\_initial , \mathrm{domN_initial} , Dissolved Organic Nitrogen, 0.1 mmol-N/m**3}
!> \describepar{domP\_initial , \mathrm{domP_initial} , Dissolved Organic Phosphorus, 0.01 mmol-P/m**3}
!> \describepar{RNit\_initial , \mathrm{RNit_initial} , N-reservoir, 0. mmol-N/m**3}
!> \describepar{frac\_Rub\_ini , \mathrm{frac_Rub_ini} , fraction of Rubisco, 0.5 -}
!> \describepar{Rub          , \mathrm{frac_Rub_ini}\mathrm{phyC_initial}, trait x biomass}
!> \describepar{frac\_chl\_ini , \mathrm{frac_chl_ini} , Chl, 0.25 mg-Chl/m**3}
!> \describepar{chl          , \mathrm{frac_chl_ini}\mathrm{phyC_initial}, trait x biomass}
!> \describepar{nh3\_initial  , \mathrm{nh3_initial}  , dissolved ammonium, 0. mmolN/m**3}
!> \describepar{oxy\_initial  , \mathrm{oxy_initial}  , dissolved oxygen, 300. mmolO2/m**3}
!> \describepar{odu\_initial  , \mathrm{odu_initial}  , dissolved reduced substances, 0. mmolO2/m**3}
!> \describepar{vir\_initial  , \mathrm{vir_initial}  , Virus C density in cells, 0. -}
!> \describepar{vir          , \mathrm{vir_initial}\mathrm{phyC_initial}, trait x biomass}
! other parameters
!> \describepar{P\_max        , P_\mathrm{max}        , maximum potential photosynthetic rate, 9. d^{-1}}
!> \describepar{alpha        , \alpha        , specific light adsorption by chloroplasts , 0.2 m2 mol-C/(muE g-CHL)}
!> \describepar{sigma        , \sigma        , Q-dependency of Rubisco activity/chloroplast ratio, 1.0 }
!> \describepar{theta\_LHC    , \theta_\mathrm{C}    , chlorophyll a-to-C ratio of LHC, 0.8 mgChl mmolC^{-1}}
!> \describepar{rel\_chloropl\_min , \mathrm{rel_chloropl_min} , chloroplast-C to phy-C ratio, 0.02 mol-C/mol-C}
!> \describepar{QN\_phy\_0     , Q_{\mathrm{N}0}     , subsistence N-quota, 0.04 mol-N/mol-C}
!> \describepar{QN\_phy\_max   , Q_\mathrm{N}^\mathrm{ref}   , maximum N-quota, 0.18 mol-N/mol-C}
!> \describepar{V\_NC\_max     , V_\mathrm{max,N}^0     , maximum N uptake rate, 0.7 mmol-N/(m3 d)}
!> \describepar{AffN         , A_\mathrm{N}^0         , N-Affinity, 0.5 m3/(mmol-N d)}
!> \describepar{zeta\_CN      , \zeta_\mathrm{CN}      , respiratory costs of N-synthesis/NO3-reduction, 4 mol-C/mol-N}
!> \describepar{zstoich\_PN   , \mathrm{zstoich_PN}   , P-stoichiometry of active compounds(-> P costs), 6 mol-N/mol-P}
!> \describepar{exud\_phy     , \mathrm{exud_phy}     , phytoplankton exudation per production, 0. }
!> \describepar{QP\_phy\_0     , Q_{\mathrm{P}0}     , subsistence P-quota, 0.00 mol-P/mol-C}
!> \describepar{QP\_phy\_max   , Q_\mathrm{P}^\mathrm{ref}   , subsistence P-quota, 0.008 mol-P/mol-C}
!> \describepar{V\_PC\_max     , V_\mathrm{max,P}^0     , maximum P uptake rate, 0.2 mol-P/(mol-C d)}
!> \describepar{AffP         , A_\mathrm{P}^0         , P-Affinity, 0.2 m3/(mmol-C d)}
!> \describepar{QSi\_phy\_0    , Q_{\mathrm{Si}0}    , subsistence Si-quota, 0.02 mol-Si/mol-C}
!> \describepar{QSi\_phy\_max  , Q_\mathrm{Si}^\mathrm{ref}  , subsistence Si-quota, 0.2 mol-Si/mol-C}
!> \describepar{V\_SiC\_max    , V_\mathrm{max,Si}^0    , maximum Si-uptake rate, 0.7 mol-Si/(mol-C d)}
!> \describepar{AffSi        , A_\mathrm{Si}^0        , Si-Affinity, 0.3 m3/(mmol-C d)}
!> \describepar{MaxRelQ      , \mathrm{max}q      , upper bound for relative quota, 3. }
!> \describepar{syn\_nut      , 1/h      , synchrony nqueue in nutrient quota limitation, -4. }
!> \describepar{adap\_rub     , \delta_R     , adap_rub, 1.0 }
!> \describepar{adap\_theta   , \delta_\theta   , adap_theta, 1.0 }
!> \describepar{tau\_regV     , \Delta t_\mathrm{v}     , tau-regV, 15.0 }
!> \describepar{disease      , \mathrm{disease}      , parasites/disease mortality rate ; TODO:not implemented yet, 0 d^{-1}}
!> \describepar{mort\_ODU     , \mathrm{mort_ODU}     , toxic stress due to H2S , 0.0 m3/mmol-ODU.d}
!> \describepar{decay\_pigm   , \mathrm{decay_pigm}   , pigment decay rate , 0.0 1/d}
!> \describepar{decay\_nut    , \mathrm{decay_nut}    , non-carbon structure decay rate , 0.1 1/d}
!> \describepar{phi\_agg      , \mathrm{phi_agg}      , quadratic aggregation rate, 0.001 m^6 mmol-N^{-2} d^{-1}}
!> \describepar{agg\_doc      , \mathrm{agg_doc}      , DOC multiplier in coagulation term, 0.004 m^-3 mmol-C}
!> \describepar{vir\_loss     , \mathrm{vir_loss}     , specific loss/exudation rate of infected phy, 2. - }
!> \describepar{vir\_mu       , \mathrm{vir_mu}       , viral growth rate (=vir_loss), 2. 1/d}
!> \describepar{vir\_infect   , \mathrm{vir_infect}   , specific infection rate rate (not used), 0.0 m3/d.mol-C}
!> \describepar{vir\_phyC     , \mathrm{vir_phyC}     , phy conc where infection diversity = 1 , 1. mmol-C/m3}
!> \describepar{vir\_spor\_r   , \mathrm{vir_spor_r}   , death and spore building rate of virus, 0.2 -}
!> \describepar{vir\_spor\_C   , \mathrm{vir_spor_C}   , virus concentration with max spore building  , 0.0002 -}
!> \describepar{sink\_phys    , \mathrm{sink_phys}    , sinking sensitivity on physiological status, 4. }
!> \describepar{vS\_phy       , \mathrm{vS_phy}       , sinking velocity for phytoplankton, 2.3 m d^{-1}}
!> \describepar{vS\_det       , \mathrm{vS_det}       , sinking velocity for detritus, 12. m d^{-1}}
!> \describepar{hydrol       , \mathrm{hydrol}       , degradation rate of most refractory POM, 0.001 d^{-1}}
!> \describepar{remin        , \mathrm{remin}        , pel.remineralisation rate of most refractory DOM, 0.002 d^{-1}}
!> \describepar{Nqual        , \mathrm{Nqual}        , quality increase with ON/OC (0:no effect; 1: full linearity), 0.95 }
!> \describepar{remNP        , \mathrm{remNP}        , relative P-stoichiometry in preferential (high N) remin, -0.001 }
!> \describepar{denit        , \mathrm{denit}        , DIN removal by denitrification  , 0. d^{-1}}
!> \describepar{PON\_denit    , \mathrm{PON_denit}    , critical PON for denitrification  , 5 mmol-N/m3 }
!> \describepar{Q10          , \mathrm{Q10}          , Q10 factor, 1.5 }
!> \describepar{T\_ref        , \mathrm{T_ref}        , reference Kelvin temperature, 289.0 K}
!> \describepar{NutOrder     , \mathrm{NutOrder}     , element order of recursive scheme. lower digit: synchrony element , 123.2 serial order number N:P:Si}
!> \describepar{const\_NC\_zoo , \mathrm{const_NC_zoo} , zooplankton N:C ratio, 0.25 mol/mol}
!> \describepar{const\_PC\_zoo , \mathrm{const_PC_zoo} , zooplankton P:C ratio, 0.02 mol/mol}
!> \describepar{g\_max        , \mathrm{g_max}        , maximum grazing rate, 1. per d}
!> \describepar{k\_grazC      , \mathrm{k_grazC}      , half saturation graing, 10.0 mmolN/m**3}
!> \describepar{yield\_zoo    , \mathrm{yield_zoo}    , yield of herbivory, 0.35 }
!> \describepar{basal\_resp\_zoo , \mathrm{basal_resp_zoo} , basal respiration, 0.05 per d}
!> \describepar{mort\_zoo     , \mathrm{mort_zoo}     , quadratic mortality, 0.023 m**3/mmolN.d}
!> \describepar{zm\_fa\_delmax , \mathrm{zm_fa_delmax} , max.increase factor in attenuation-dependent mort.rate (only active if mort_zoo<0), 3.5 m**3/mmolN.d}
!> \describepar{zm\_fa\_inf    , \mathrm{zm_fa_inf}    , infliction point of the att. function of mort.rate (only active if mort_zoo<0), 0.07 - }
!> \describepar{fT\_exp\_mort  , \mathrm{fT_exp_mort}  , exponent temperature dep. mortality (1: standard), 3. m**3/mmolN.d}
!> \describepar{a\_water      , \mathrm{a_water}      , background attenuation coefficient, 0.4 1/m}
!> \describepar{a\_minfr      , \mathrm{a_minfr}      , heuristic depth-dep attenuation, 0.2 -}
!> \describepar{a\_spm        , \mathrm{a_spm}        , attenuation coefficient of SPM, 0.005 m**3/m.mmolC}
!> \describepar{a\_phyc       , \mathrm{a_phyc}       , attenuation coefficient of PhyC, 0.005 m**3/m.mmolC}
!> \describepar{a\_doc        , \mathrm{a_doc}        , attenuation coefficient of DOC, 0.0 m**3/m.mmolC}
!> \describepar{a\_fz         , \mathrm{a_fz}         , depth dependent turbidity gradient, 7.55 -}
!> \describepar{a\_chl        , \mathrm{a_chl}        , attenuation coefficient due to Chl absorption, 0.005 m**3/m.mgChl}
!> \describepar{rel\_co2      , \mathrm{rel_co2}      , relative CO2 conc in sea water , -1 -}
!> \describepar{frac\_PAR     , \mathrm{frac_PAR}     , photosynthetically active fraction of light, 1.0 }
!> \describepar{small        , \mathrm{small}        , lower limit for denominator in ratios; small_finite=sqrt(small), 1e-6 }
!> \describepar{maxVal       , \mathrm{maxVal}       , upper limit for trait variables; <0: also no mininum check, -12.0000 }
!> \describepar{dil          , \mathrm{dil}          , dilution of all concentrations except dissolved inorganics, 0.0 1/d}
!> \describepar{ex\_airsea    , \mathrm{ex_airsea}    , diffusivity coefficient (m2/s) divided by boundary layer thickness, 3e-5 m/s}
!> \describepar{O2\_sat       , \mathrm{O2_sat}       , oxygen concentration in air-sea boundary layer, 300. mmol-O2/m2.d}
!> \describepar{N\_depo       , \mathrm{N_depo}       , DIN deposition rate 0.5  6-21mg/m2.d Grieken2007 - , 0.0 mmol-N/m2.d}
!> \describepar{P\_depo       , \mathrm{P_depo}       , DIP deposition rate , 0.0 mmol-P/m2.d}
!> \describepar{rPAds        , \mathrm{rPAds}        , Adsorption coeff phosphorus, 0.0 }
!> \describepar{PAdsODU      , \mathrm{PAdsODU}      , PO4-Fe dissolution threshold in terms of [FeS]/ODU, 12. }
!> \describepar{rnit         , \mathrm{rnit}         , Max nitrification rate, 12. 1/d}
!> \describepar{ksO2nitri    , \mathrm{ksO2nitri}    , half-sat O2 in nitrification, 20. umolO2/m3}
!> \describepar{rODUox       , \mathrm{rODUox}       , Max rate oxidation of ODU, 0. 1/d}
!> \describepar{ksO2oduox    , \mathrm{ksO2oduox}    , half-sat O2 in oxidation of ODU, 0.333 mmolO2/m3}
!> \describepar{ksO2oxic     , \mathrm{ksO2oxic}     , half-sat O2 in oxic mineralis, 3. mmolO2/m3}
!> \describepar{ksNO3denit   , \mathrm{ksNO3denit}   , half-sat NO3 in denitrif, 30. mmolNO3/m3}
!> \describepar{kinO2denit   , \mathrm{kinO2denit}   , half-sat O2 inhib denitrif, 1. mmolO2/m3}
!> \describepar{kinNO3anox   , \mathrm{kinNO3anox}   , half-sat NO3 inhib anoxic min, 1. mmolNO3/m3}
!> \describepar{kinO2anox    , \mathrm{kinO2anox}    , half-sat O2 inhib anoxic min, 1. mmolO2/m3}
!> \describepar{rAnammox     , \mathrm{rAnammox}     , anammox rate, 0.025 1/d}
subroutine initialize(self, configunit)

class (type_hzg_maecs), intent(inout), target :: self
integer,                  intent(in)            :: configunit
!
! !LOCAL VARIABLES:
integer    :: namlst=19
!!------- Initial values of model maecs ------- 
real(rk)  :: nutN_initial ! Dissolved Inorganic Nitrogen DIN
real(rk)  :: nutP_initial ! Dissolved Inorganic Phosphorus DIP
real(rk)  :: nutS_initial ! Dissolved Inorganic Silicon Si
real(rk)  :: nutFe_initial ! Dissolved Inorganic Iron Fe
real(rk)  :: phyC_initial ! Phytplankton Carbon
real(rk)  :: phyN_initial ! Phytplankton Nitrogen
real(rk)  :: phyP_initial ! Phytplankton Phosphorus
real(rk)  :: phyS_initial ! Phytplankton Silicon
real(rk)  :: phyFe_initial ! Phytplankton Iron
real(rk)  :: zooC_initial ! Zooplankton Carbon
real(rk)  :: detC_initial ! Detritus Carbon
real(rk)  :: detN_initial ! Detritus Nitrogen
real(rk)  :: detP_initial ! Detritus Phosphorus
real(rk)  :: detS_initial ! Detritus Silicon
real(rk)  :: detFe_initial ! Detritus Iron
real(rk)  :: domC_initial ! Dissolved Organic Carbon
real(rk)  :: domN_initial ! Dissolved Organic Nitrogen
real(rk)  :: domP_initial ! Dissolved Organic Phosphorus
real(rk)  :: RNit_initial ! N-reservoir
real(rk)  :: frac_Rub_ini ! fraction of Rubisco
real(rk)  :: Rub  ! trait times biomass
real(rk)  :: frac_chl_ini ! Chl
real(rk)  :: chl  ! trait times biomass
real(rk)  :: nh3_initial  ! dissolved ammonium
real(rk)  :: oxy_initial  ! dissolved oxygen
real(rk)  :: odu_initial  ! dissolved reduced substances
real(rk)  :: vir_initial  ! Virus C density in cells
real(rk)  :: vir  ! trait times biomass
!!------- Parameters from nml-list maecs_pars ------- 
real(rk)  :: P_max        ! maximum potential photosynthetic rate
real(rk)  :: alpha        ! specific light adsorption by chloroplasts 
real(rk)  :: sigma        ! Q-dependency of Rubisco activity/chloroplast ratio
real(rk)  :: theta_LHC    ! chlorophyll a-to-C ratio of LHC
real(rk)  :: rel_chloropl_min ! chloroplast-C to phy-C ratio
real(rk)  :: QN_phy_0     ! subsistence N-quota
real(rk)  :: QN_phy_max   ! maximum N-quota
real(rk)  :: V_NC_max     ! maximum N uptake rate
real(rk)  :: AffN         ! N-Affinity
real(rk)  :: zeta_CN      ! respiratory costs of N-synthesis/NO3-reduction
real(rk)  :: zstoich_PN   ! P-stoichiometry of active compounds(-> P costs)
real(rk)  :: exud_phy     ! phytoplankton exudation per production
real(rk)  :: QP_phy_0     ! subsistence P-quota
real(rk)  :: QP_phy_max   ! subsistence P-quota
real(rk)  :: V_PC_max     ! maximum P uptake rate
real(rk)  :: AffP         ! P-Affinity
real(rk)  :: QSi_phy_0    ! subsistence Si-quota
real(rk)  :: QSi_phy_max  ! subsistence Si-quota
real(rk)  :: V_SiC_max    ! maximum Si-uptake rate
real(rk)  :: AffSi        ! Si-Affinity
real(rk)  :: QFe_phy_0    ! subsistence Fe-quota
real(rk)  :: QFe_phy_max  ! subsistence Fe-quota
real(rk)  :: V_FeC_max    ! maximum Fe-uptake rate
real(rk)  :: AffFe        ! Fe-Affinity
real(rk)  :: MaxRelQ      ! upper bound for relative quota
real(rk)  :: syn_nut      ! synchrony nqueue in nutrient quota limitation
real(rk)  :: adap_rub     ! adap_rub
real(rk)  :: adap_theta   ! adap_theta
real(rk)  :: tau_regV     ! tau-regV
real(rk)  :: disease      ! parasites/disease mortality rate ; TODO:not implemented yet
real(rk)  :: mort_ODU     ! toxic stress due to H2S 
real(rk)  :: decay_pigm   ! pigment decay rate 
real(rk)  :: decay_nut    ! non-carbon structure decay rate 
real(rk)  :: phi_agg      ! quadratic aggregation rate
real(rk)  :: agg_doc      ! DOC multiplier in coagulation term
real(rk)  :: vir_loss     ! specific loss/exudation rate of infected phy
real(rk)  :: vir_mu       ! viral growth rate (=vir_loss)
real(rk)  :: vir_infect   ! specific infection rate rate (not used)
real(rk)  :: vir_phyC     ! phy conc where infection diversity = 1 
real(rk)  :: vir_spor_r   ! death and spore building rate of virus
real(rk)  :: vir_spor_C   ! virus concentration with max spore building  
real(rk)  :: sink_phys    ! sinking sensitivity on physiological status
real(rk)  :: vS_phy       ! sinking velocity for phytoplankton
real(rk)  :: vS_det       ! sinking velocity for detritus
real(rk)  :: hydrol       ! degradation rate of most refractory POM
real(rk)  :: remin        ! pel.remineralisation rate of most refractory DOM
real(rk)  :: Nqual        ! quality increase with ON/OC (0:no effect; 1: full linearity)
real(rk)  :: remNP        ! relative P-stoichiometry in preferential (high N) remin
real(rk)  :: denit        ! DIN removal by denitrification  
real(rk)  :: PON_denit    ! critical PON for denitrification  
real(rk)  :: Q10          ! Q10 factor
real(rk)  :: T_ref        ! reference Kelvin temperature
real(rk)  :: NutOrder     ! element order of recursive scheme. lower digit: synchrony element 
!!------- Parameters from nml-list maecs_graz ------- 
real(rk)  :: const_NC_zoo ! zooplankton N:C ratio
real(rk)  :: const_PC_zoo ! zooplankton P:C ratio
real(rk)  :: g_max        ! maximum grazing rate
real(rk)  :: k_grazC      ! half saturation graing
real(rk)  :: yield_zoo    ! yield of herbivory
real(rk)  :: basal_resp_zoo ! basal respiration
real(rk)  :: mort_zoo     ! quadratic mortality
real(rk)  :: zm_fa_delmax ! max.increase factor in attenuation-dependent mort.rate (only active if mort_zoo<0)
real(rk)  :: zm_fa_inf    ! infliction point of the att. function of mort.rate (only active if mort_zoo<0)
real(rk)  :: fT_exp_mort  ! exponent temperature dep. mortality (1: standard)
!!------- Parameters from nml-list maecs_env ------- 
real(rk)  :: a_water      ! background attenuation coefficient
real(rk)  :: a_minfr      ! heuristic depth-dep attenuation
real(rk)  :: a_spm        ! attenuation coefficient of SPM
real(rk)  :: a_phyc       ! attenuation coefficient of PhyC
real(rk)  :: a_doc        ! attenuation coefficient of DOC
real(rk)  :: a_fz         ! depth dependent turbidity gradient
real(rk)  :: a_chl        ! attenuation coefficient due to Chl absorption
real(rk)  :: rel_co2      ! relative CO2 conc in sea water 
real(rk)  :: frac_PAR     ! photosynthetically active fraction of light
real(rk)  :: small        ! lower limit for denominator in ratios; small_finite=sqrt(small)
real(rk)  :: maxVal       ! upper limit for trait variables; <0: also no mininum check
real(rk)  :: dil          ! dilution of all concentrations except dissolved inorganics
real(rk)  :: ex_airsea    ! diffusivity coefficient (m2/s) divided by boundary layer thickness
real(rk)  :: O2_sat       ! oxygen concentration in air-sea boundary layer
real(rk)  :: N_depo       ! DIN deposition rate 0.5  6-21mg/m2.d Grieken2007 - 
real(rk)  :: P_depo       ! DIP deposition rate 
!!------- Parameters from nml-list maecs_omex ------- 
real(rk)  :: rPAds        ! Adsorption coeff phosphorus
real(rk)  :: PAdsODU      ! PO4-Fe dissolution threshold in terms of [FeS]/ODU
real(rk)  :: rnit         ! Max nitrification rate
real(rk)  :: ksO2nitri    ! half-sat O2 in nitrification
real(rk)  :: rODUox       ! Max rate oxidation of ODU
real(rk)  :: ksO2oduox    ! half-sat O2 in oxidation of ODU
real(rk)  :: ksO2oxic     ! half-sat O2 in oxic mineralis
real(rk)  :: ksNO3denit   ! half-sat NO3 in denitrif
real(rk)  :: kinO2denit   ! half-sat O2 inhib denitrif
real(rk)  :: kinNO3anox   ! half-sat NO3 inhib anoxic min
real(rk)  :: kinO2anox    ! half-sat O2 inhib anoxic min
real(rk)  :: rAnammox     ! anammox rate
!!------- Switches for configuring model structure -------
logical   :: RubiscoOn    =.false.! use Rubisco- here in C-units
logical   :: PhotoacclimOn =.false.! use Photoacclimation
logical   :: PhosphorusOn =.false.! resolve Phosphorus cycle
logical   :: SiliconOn    =.false.! resolve Silicon cycle
logical   :: IronOn    =.false.! resolve Iron cycle
logical   :: GrazingOn    =.false.! use Zooplankton grazing
logical   :: BioOxyOn     =.false.! use oxygen&ODU from OMEXDIA
logical   :: DebugDiagOn  =.false.! output of volatile diagnostics for debugging
logical   :: Budget0DDiagOn =.false.! output of elemental budgets (totX)
logical   :: Budget2DDiagOn =.false.! output of vertical budget integrals (totX_vertint/diag)
logical   :: BGC0DDiagOn  =.false.! output of local rates (GPP, Denit,...) and states (NO3)
logical   :: BGC2DDiagOn  =.false.! output of BGC fluxes (O,C,N)
logical   :: PhysiolDiagOn =.false.! output of ecophysiological/allocation/acclimation variables
logical   :: RateDiagOn   =.false.! output of phytoplankton growth and loss rate contributions
logical   :: ChemostatOn  =.false.! use Chemostat mode 
logical   :: VirusOn      =.false.! use dynamic virus variable
logical   :: SwitchOn     =.false.! use experimental mode 1
integer   :: GrazTurbOn   =0! > 0 use water clarity as proxy for top-predation 
logical   :: NResOn       =.false.! use long-term N-reservoir
integer   :: kwFzmaxMeth  =0! background extinction method
integer   :: genMeth      =0! dummy method switch
logical   :: detritus_no_river_dilution =.false.! use riverine det import
logical   :: plankton_no_river_dilution =.false.! use riverine phy import
logical   :: nutrient_no_river_dilution =.false.! use riverine nut import

namelist /maecs_switch/ &
  RubiscoOn, PhotoacclimOn, PhosphorusOn, SiliconOn, IronOn, GrazingOn, BioOxyOn, &
  DebugDiagOn, Budget0DDiagOn, Budget2DDiagOn, BGC0DDiagOn, BGC2DDiagOn, &
  PhysiolDiagOn, RateDiagOn, ChemostatOn, VirusOn, SwitchOn, GrazTurbOn, &
  NResOn, kwFzmaxMeth, genMeth, detritus_no_river_dilution, plankton_no_river_dilution, &
  nutrient_no_river_dilution

namelist /maecs_init/ &
  nutN_initial, nutP_initial, nutS_initial, nutFe_initial, phyC_initial, phyN_initial, &
  phyP_initial, phyS_initial, phyFe_initial, zooC_initial, detC_initial, detN_initial, &
  detP_initial, detS_initial, detFe_initial, domC_initial, domN_initial, domP_initial, &
  RNit_initial, frac_Rub_ini, frac_chl_ini, nh3_initial, oxy_initial, &
  odu_initial, vir_initial

namelist /maecs_pars/ &
  P_max, alpha, sigma, theta_LHC, rel_chloropl_min, QN_phy_0, QN_phy_max, &
  V_NC_max, AffN, zeta_CN, zstoich_PN, exud_phy, QP_phy_0, QP_phy_max, V_PC_max, &
  AffP, QSi_phy_0, QSi_phy_max, V_SiC_max, AffSi, QFe_phy_0, QFe_phy_max,&
  V_FeC_max, AffFe, MaxRelQ, syn_nut, adap_rub, &
  adap_theta, tau_regV, disease, mort_ODU, decay_pigm, decay_nut, phi_agg, &
  agg_doc, vir_loss, vir_mu, vir_infect, vir_phyC, vir_spor_r, vir_spor_C, &
  sink_phys, vS_phy, vS_det, hydrol, remin, Nqual, remNP, denit, PON_denit, Q10, &
  T_ref, NutOrder

namelist /maecs_graz/ &
  const_NC_zoo, const_PC_zoo, g_max, k_grazC, yield_zoo, basal_resp_zoo, &
  mort_zoo, zm_fa_delmax, zm_fa_inf, fT_exp_mort

namelist /maecs_env/ &
  a_water, a_minfr, a_spm, a_phyc, a_doc, a_fz, a_chl, rel_co2, frac_PAR, small, &
  maxVal, dil, ex_airsea, O2_sat, N_depo, P_depo

namelist /maecs_omex/ &
  rPAds, PAdsODU, rnit, ksO2nitri, rODUox, ksO2oduox, ksO2oxic, ksNO3denit, &
  kinO2denit, kinNO3anox, kinO2anox, rAnammox

nutN_initial = 30_rk              ! mmol-N/m**3
nutP_initial = 1.4_rk             ! mmol-P/m**3
nutS_initial = 140_rk             ! mmol-Si/m**3
nutFe_initial = 0.001_rk          ! mmol-Fe/m**3
phyC_initial = 5_rk               ! mmol-C/m**3
phyN_initial = 1_rk               ! mmol-N/m**3
phyP_initial = 0.1_rk             ! mmol-P/m**3
phyS_initial = 2._rk              ! mmol-Si/m**3
phyFe_initial = 0.001_rk          ! mmol-Fe/m**3
zooC_initial = 1._rk              ! mmol-C/m**3
detC_initial = 1._rk              ! mmol-C/m**3
detN_initial = 0.1_rk             ! mmol-N/m**3
detP_initial = 0.01_rk            ! mmol-P/m**3
detS_initial = 0._rk              ! mmol-Si/m**3
detFe_initial = 0._rk             ! mmol-Fe/m**3
domC_initial = 1.0_rk             ! mmol-C/m**3
domN_initial = 0.1_rk             ! mmol-N/m**3
domP_initial = 0.01_rk            ! mmol-P/m**3
RNit_initial = 0._rk              ! mmol-N/m**3
frac_Rub_ini = 0.5_rk             ! -
frac_chl_ini = 0.25_rk            ! mg-Chl/m**3
nh3_initial  = 0._rk              ! mmolN/m**3
oxy_initial  = 300._rk            ! mmolO2/m**3
odu_initial  = 0._rk              ! mmolO2/m**3
vir_initial  = 0._rk              ! -
P_max        = 9._rk              ! d^{-1}
alpha        = 0.2_rk             ! m2 mol-C/(muE g-CHL)
sigma        = 1.0_rk             ! 
theta_LHC    = 0.8_rk             ! mgChl mmolC^{-1}
rel_chloropl_min = 0.02_rk            ! mol-C/mol-C
QN_phy_0     = 0.04_rk            ! mol-N/mol-C
QN_phy_max   = 0.18_rk            ! mol-N/mol-C
V_NC_max     = 0.7_rk             ! mmol-N/(m3 d)
AffN         = 0.5_rk             ! m3/(mmol-N d)
zeta_CN      = 4_rk               ! mol-C/mol-N
zstoich_PN   = 6_rk               ! mol-N/mol-P
exud_phy     = 0._rk              ! 
QP_phy_0     = 0.00_rk            ! mol-P/mol-C
QP_phy_max   = 0.008_rk           ! mol-P/mol-C
V_PC_max     = 0.2_rk             ! mol-P/(mol-C d)
AffP         = 0.2_rk             ! m3/(mmol-C d)
QSi_phy_0    = 0.02_rk            ! mol-Si/mol-C
QSi_phy_max  = 0.2_rk             ! mol-Si/mol-C
V_SiC_max    = 0.7_rk             ! mol-Si/(mol-C d)
AffSi        = 0.3_rk             ! m3/(mmol-C d)
QFe_phy_0    = 0.00001_rk            ! mol-Fe/mol-C
QFe_phy_max  = 0.0001_rk             ! mol-Fe/mol-C
V_FeC_max    = 000.7_rk             ! mol-Fe/(mol-C d)
AffFe        = 0.3_rk             ! m3/(mmol-C d)
MaxRelQ      = 3._rk              ! 
syn_nut      = -4._rk             ! 
adap_rub     = 1.0_rk             ! 
adap_theta   = 1.0_rk             ! 
tau_regV     = 15.0_rk            ! 
disease      = 0_rk               ! d^{-1}
mort_ODU     = 0.0_rk             ! m3/mmol-ODU.d
decay_pigm   = 0.0_rk             ! 1/d
decay_nut    = 0.1_rk             ! 1/d
phi_agg      = 0.001_rk           ! m^6 mmol-N^{-2} d^{-1}
agg_doc      = 0.004_rk           ! m^-3 mmol-C
vir_loss     = 2._rk              ! - 
vir_mu       = 2._rk              ! 1/d
vir_infect   = 0.0_rk             ! m3/d.mol-C
vir_phyC     = 1._rk              ! mmol-C/m3
vir_spor_r   = 0.2_rk             ! -
vir_spor_C   = 0.0002_rk          ! -
sink_phys    = 4._rk              ! 
vS_phy       = 2.3_rk             ! m d^{-1}
vS_det       = 12._rk             ! m d^{-1}
hydrol       = 0.001_rk           ! d^{-1}
remin        = 0.002_rk           ! d^{-1}
Nqual        = 0.95_rk            ! 
remNP        = -0.001_rk          ! 
denit        = 0._rk              ! d^{-1}
PON_denit    = 5_rk               ! mmol-N/m3 
Q10          = 1.5_rk             ! 
T_ref        = 289.0_rk           ! K
!NutOrder     = 123.2_rk          ! serial order number N:P:Si
NutOrder     = 1234.2_rk          ! serial order number N:P:Fe:Si
const_NC_zoo = 0.25_rk            ! mol/mol
const_PC_zoo = 0.02_rk            ! mol/mol
g_max        = 1._rk              ! per d
k_grazC      = 10.0_rk            ! mmolN/m**3
yield_zoo    = 0.35_rk            ! 
basal_resp_zoo = 0.05_rk            ! per d
mort_zoo     = 0.023_rk           ! m**3/mmolN.d
zm_fa_delmax = 3.5_rk             ! m**3/mmolN.d
zm_fa_inf    = 0.07_rk            ! - 
fT_exp_mort  = 3._rk              ! m**3/mmolN.d
a_water      = 0.4_rk             ! 1/m
a_minfr      = 0.2_rk             ! -
a_spm        = 0.005_rk           ! m**3/m.mmolC
a_phyc       = 0.005_rk           ! m**3/m.mmolC
a_doc        = 0.0_rk             ! m**3/m.mmolC
a_fz         = 7.55_rk            ! -
a_chl        = 0.005_rk           ! m**3/m.mgChl
rel_co2      = -1_rk              ! -
frac_PAR     = 1.0_rk             ! 
small        = 1e-6_rk            ! 
maxVal       = -12.0000_rk        ! 
dil          = 0.0_rk             ! 1/d
ex_airsea    = 3e-5_rk            ! m/s
O2_sat       = 300._rk            ! mmol-O2/m2.d
N_depo       = 0.0_rk             ! mmol-N/m2.d
P_depo       = 0.0_rk             ! mmol-P/m2.d
rPAds        = 0.0_rk             ! 
PAdsODU      = 12._rk             ! 
rnit         = 12._rk             ! 1/d
ksO2nitri    = 20._rk             ! umolO2/m3
rODUox       = 0._rk              ! 1/d
ksO2oduox    = 0.333_rk           ! mmolO2/m3
ksO2oxic     = 3._rk              ! mmolO2/m3
ksNO3denit   = 30._rk             ! mmolNO3/m3
kinO2denit   = 1._rk              ! mmolO2/m3
kinNO3anox   = 1._rk              ! mmolNO3/m3
kinO2anox    = 1._rk              ! mmolO2/m3
rAnammox     = 0.025_rk           ! 1/d


!--------- read namelists --------- 
write(0,*) ' read namelists ....'
open(namlst,file='maecs_switch.nml',status='old')
read(namlst,nml=maecs_switch,err=90,end=99)
open(namlst,file='maecs_init.nml',status='old')
read(namlst,nml=maecs_init,err=91,end=100)
open(namlst,file='maecs_pars.nml',status='old')
read(namlst,nml=maecs_pars,err=92,end=101)
open(namlst,file='maecs_graz.nml',status='old')
read(namlst,nml=maecs_graz,err=93,end=102)
open(namlst,file='maecs_env.nml',status='old')
read(namlst,nml=maecs_env,err=94,end=103)
open(namlst,file='maecs_omex.nml',status='old')
read(namlst,nml=maecs_omex,err=95,end=104)
! Store parameter values in our own derived type
! NB: all rates must be provided in values per day,
! and are converted here to values per second.

!!------- logical parameters: switches  -------
call self%get_parameter(self%RubiscoOn,     'RubiscoOn',     default=RubiscoOn)
call self%get_parameter(self%PhotoacclimOn,  'PhotoacclimOn',  default=PhotoacclimOn)
call self%get_parameter(self%PhosphorusOn,  'PhosphorusOn',  default=PhosphorusOn)
call self%get_parameter(self%SiliconOn,     'SiliconOn',     default=SiliconOn)
call self%get_parameter(self%IronOn,        'IronOn',     default=IronOn)
call self%get_parameter(self%GrazingOn,     'GrazingOn',     default=GrazingOn)
call self%get_parameter(self%BioOxyOn,      'BioOxyOn',      default=BioOxyOn)
call self%get_parameter(self%DebugDiagOn,   'DebugDiagOn',   default=DebugDiagOn)
call self%get_parameter(self%Budget0DDiagOn,  'Budget0DDiagOn',  default=Budget0DDiagOn)
call self%get_parameter(self%Budget2DDiagOn,  'Budget2DDiagOn',  default=Budget2DDiagOn)
call self%get_parameter(self%BGC0DDiagOn,   'BGC0DDiagOn',   default=BGC0DDiagOn)
call self%get_parameter(self%BGC2DDiagOn,   'BGC2DDiagOn',   default=BGC2DDiagOn)
call self%get_parameter(self%PhysiolDiagOn,  'PhysiolDiagOn',  default=PhysiolDiagOn)
call self%get_parameter(self%RateDiagOn,    'RateDiagOn',    default=RateDiagOn)
call self%get_parameter(self%ChemostatOn,   'ChemostatOn',   default=ChemostatOn)
call self%get_parameter(self%VirusOn,       'VirusOn',       default=VirusOn)
call self%get_parameter(self%SwitchOn,      'SwitchOn',      default=SwitchOn)
call self%get_parameter(self%GrazTurbOn,    'GrazTurbOn',    default=GrazTurbOn)
call self%get_parameter(self%NResOn,        'NResOn',        default=NResOn)
call self%get_parameter(self%kwFzmaxMeth,   'kwFzmaxMeth',   default=kwFzmaxMeth)
call self%get_parameter(self%genMeth,       'genMeth',       default=genMeth)
call self%get_parameter(self%detritus_no_river_dilution,  'detritus_no_river_dilution',  default=detritus_no_river_dilution)
call self%get_parameter(self%plankton_no_river_dilution,  'plankton_no_river_dilution',  default=plankton_no_river_dilution)
call self%get_parameter(self%nutrient_no_river_dilution,  'nutrient_no_river_dilution',  default=nutrient_no_river_dilution)

!!------- model parameters from nml-list maecs_init ------- 
call self%get_parameter(self%nutN_initial ,'nutN_initial',  default=nutN_initial)
call self%get_parameter(self%phyC_initial ,'phyC_initial',  default=phyC_initial)
call self%get_parameter(self%phyN_initial ,'phyN_initial',  default=phyN_initial)
call self%get_parameter(self%detC_initial ,'detC_initial',  default=detC_initial)
call self%get_parameter(self%detN_initial ,'detN_initial',  default=detN_initial)
call self%get_parameter(self%domC_initial ,'domC_initial',  default=domC_initial)
call self%get_parameter(self%domN_initial ,'domN_initial',  default=domN_initial)
call self%get_parameter(self%frac_Rub_ini ,'frac_Rub_ini',  default=frac_Rub_ini)
call self%get_parameter(self%frac_chl_ini ,'frac_chl_ini',  default=frac_chl_ini)
call self%get_parameter(self%nutP_initial ,'nutP_initial',  default=nutP_initial)
call self%get_parameter(self%phyP_initial ,'phyP_initial',  default=phyP_initial)
call self%get_parameter(self%detP_initial ,'detP_initial',  default=detP_initial)
call self%get_parameter(self%domP_initial ,'domP_initial',  default=domP_initial)
call self%get_parameter(self%nutS_initial ,'nutS_initial',  default=nutS_initial)
call self%get_parameter(self%phyS_initial ,'phyS_initial',  default=phyS_initial)
call self%get_parameter(self%detS_initial ,'detS_initial',  default=detS_initial)
call self%get_parameter(self%nutFe_initial ,'nutFe_initial',  default=nutFe_initial)
call self%get_parameter(self%phyFe_initial ,'phyFe_initial',  default=phyFe_initial)
call self%get_parameter(self%detFe_initial ,'detFe_initial',  default=detFe_initial)
call self%get_parameter(self%zooC_initial ,'zooC_initial',  default=zooC_initial)
call self%get_parameter(self%nh3_initial  ,'nh3_initial',   default=nh3_initial)
call self%get_parameter(self%oxy_initial  ,'oxy_initial',   default=oxy_initial)
call self%get_parameter(self%odu_initial  ,'odu_initial',   default=odu_initial)
call self%get_parameter(self%vir_initial  ,'vir_initial',   default=vir_initial)
call self%get_parameter(self%RNit_initial ,'RNit_initial',  default=RNit_initial)

!!------- model parameters from nml-list maecs_pars ------- 
call self%get_parameter(self%P_max        ,'P_max',         default=P_max)
call self%get_parameter(self%alpha        ,'alpha',         default=alpha)
call self%get_parameter(self%sigma        ,'sigma',         default=sigma)
call self%get_parameter(self%theta_LHC    ,'theta_LHC',     default=theta_LHC)
call self%get_parameter(self%rel_chloropl_min ,'rel_chloropl_min',  default=rel_chloropl_min)
call self%get_parameter(self%QN_phy_0     ,'QN_phy_0',      default=QN_phy_0)
call self%get_parameter(self%QN_phy_max   ,'QN_phy_max',    default=QN_phy_max)
call self%get_parameter(self%V_NC_max     ,'V_NC_max',      default=V_NC_max)
call self%get_parameter(self%AffN         ,'AffN',          default=AffN)
call self%get_parameter(self%zeta_CN      ,'zeta_CN',       default=zeta_CN)
call self%get_parameter(self%zstoich_PN   ,'zstoich_PN',    default=zstoich_PN)
call self%get_parameter(self%exud_phy     ,'exud_phy',      default=exud_phy)
call self%get_parameter(self%MaxRelQ      ,'MaxRelQ',       default=MaxRelQ)
call self%get_parameter(self%syn_nut      ,'syn_nut',       default=syn_nut)
call self%get_parameter(self%tau_regV     ,'tau_regV',      default=tau_regV)
call self%get_parameter(self%disease      ,'disease',       default=disease)
call self%get_parameter(self%decay_nut    ,'decay_nut',     default=decay_nut)
call self%get_parameter(self%phi_agg      ,'phi_agg',       default=phi_agg)
call self%get_parameter(self%agg_doc      ,'agg_doc',       default=agg_doc)
call self%get_parameter(self%vir_loss     ,'vir_loss',      default=vir_loss)
call self%get_parameter(self%vir_mu       ,'vir_mu',        default=vir_mu)
call self%get_parameter(self%vir_infect   ,'vir_infect',    default=vir_infect)
call self%get_parameter(self%vir_phyC     ,'vir_phyC',      default=vir_phyC)
call self%get_parameter(self%vir_spor_r   ,'vir_spor_r',    default=vir_spor_r)
call self%get_parameter(self%vir_spor_C   ,'vir_spor_C',    default=vir_spor_C)
call self%get_parameter(self%sink_phys    ,'sink_phys',     default=sink_phys)
call self%get_parameter(self%vS_phy       ,'vS_phy',        default=vS_phy)
call self%get_parameter(self%vS_det       ,'vS_det',        default=vS_det)
call self%get_parameter(self%hydrol       ,'hydrol',        default=hydrol)
call self%get_parameter(self%remin        ,'remin',         default=remin)
call self%get_parameter(self%Nqual        ,'Nqual',         default=Nqual)
call self%get_parameter(self%remNP        ,'remNP',         default=remNP)
call self%get_parameter(self%denit        ,'denit',         default=denit)
call self%get_parameter(self%PON_denit    ,'PON_denit',     default=PON_denit)
call self%get_parameter(self%Q10          ,'Q10',           default=Q10)
call self%get_parameter(self%T_ref        ,'T_ref',         default=T_ref)
call self%get_parameter(self%NutOrder     ,'NutOrder',      default=NutOrder)
if (self%PhotoacclimOn) then
    call self%get_parameter(self%adap_rub     ,'adap_rub',      default=adap_rub)
    call self%get_parameter(self%adap_theta   ,'adap_theta',    default=adap_theta)
    call self%get_parameter(self%decay_pigm   ,'decay_pigm',    default=decay_pigm)
end if
if (self%PhosphorusOn) then
    call self%get_parameter(self%QP_phy_0     ,'QP_phy_0',      default=QP_phy_0)
    call self%get_parameter(self%QP_phy_max   ,'QP_phy_max',    default=QP_phy_max)
    call self%get_parameter(self%V_PC_max     ,'V_PC_max',      default=V_PC_max)
    call self%get_parameter(self%AffP         ,'AffP',          default=AffP)
end if
if (self%SiliconOn) then
    call self%get_parameter(self%QSi_phy_0    ,'QSi_phy_0',     default=QSi_phy_0)
    call self%get_parameter(self%QSi_phy_max  ,'QSi_phy_max',   default=QSi_phy_max)
    call self%get_parameter(self%V_SiC_max    ,'V_SiC_max',     default=V_SiC_max)
    call self%get_parameter(self%AffSi        ,'AffSi',         default=AffSi)
end if
if (self%IronOn) then
    call self%get_parameter(self%QFe_phy_0    ,'QFe_phy_0',     default=QFe_phy_0)
    call self%get_parameter(self%QFe_phy_max  ,'QFe_phy_max',   default=QFe_phy_max)
    call self%get_parameter(self%V_FeC_max    ,'V_FeC_max',     default=V_FeC_max)
    call self%get_parameter(self%AffFe        ,'AffFe',         default=AffFe)
end if
!if (self%BioOxyOn) then
    call self%get_parameter(self%mort_ODU     ,'mort_ODU',      default=mort_ODU)
!end if

!!------- model parameters from nml-list maecs_graz ------- 
call self%get_parameter(self%const_NC_zoo ,'const_NC_zoo',  default=const_NC_zoo)
if (self%PhosphorusOn) then
    call self%get_parameter(self%const_PC_zoo ,'const_PC_zoo',  default=const_PC_zoo)
end if
if (self%GrazingOn) then
    call self%get_parameter(self%g_max        ,'g_max',         default=g_max)
    call self%get_parameter(self%k_grazC      ,'k_grazC',       default=k_grazC)
    call self%get_parameter(self%yield_zoo    ,'yield_zoo',     default=yield_zoo)
    call self%get_parameter(self%basal_resp_zoo ,'basal_resp_zoo',  default=basal_resp_zoo)
    call self%get_parameter(self%mort_zoo     ,'mort_zoo',      default=mort_zoo)
    call self%get_parameter(self%zm_fa_delmax ,'zm_fa_delmax',  default=zm_fa_delmax)
    call self%get_parameter(self%zm_fa_inf    ,'zm_fa_inf',     default=zm_fa_inf)
    call self%get_parameter(self%fT_exp_mort  ,'fT_exp_mort',   default=fT_exp_mort)
end if

!!------- model parameters from nml-list maecs_env ------- 
call self%get_parameter(self%a_water      ,'a_water',       default=a_water)
call self%get_parameter(self%a_minfr      ,'a_minfr',       default=a_minfr)
call self%get_parameter(self%a_spm        ,'a_spm',         default=a_spm)
call self%get_parameter(self%a_phyc       ,'a_phyc',        default=a_phyc)
call self%get_parameter(self%a_doc        ,'a_doc',         default=a_doc)
call self%get_parameter(self%a_fz         ,'a_fz',          default=a_fz)
call self%get_parameter(self%a_chl        ,'a_chl',         default=a_chl)
call self%get_parameter(self%rel_co2      ,'rel_co2',       default=rel_co2)
call self%get_parameter(self%frac_PAR     ,'frac_PAR',      default=frac_PAR)
call self%get_parameter(self%small        ,'small',         default=small)
call self%get_parameter(self%maxVal       ,'maxVal',        default=maxVal)
call self%get_parameter(self%dil          ,'dil',           default=dil)
call self%get_parameter(self%N_depo       ,'N_depo',        default=N_depo)
call self%get_parameter(self%P_depo       ,'P_depo',        default=P_depo)
if (self%BioOxyOn) then
    call self%get_parameter(self%ex_airsea    ,'ex_airsea',     default=ex_airsea)
    call self%get_parameter(self%O2_sat       ,'O2_sat',        default=O2_sat)
end if

!!------- model parameters from nml-list maecs_omex ------- 
if (self%BioOxyOn) then
    call self%get_parameter(self%rPAds        ,'rPAds',         default=rPAds)
    call self%get_parameter(self%PAdsODU      ,'PAdsODU',       default=PAdsODU)
    call self%get_parameter(self%rnit         ,'rnit',          default=rnit)
    call self%get_parameter(self%ksO2nitri    ,'ksO2nitri',     default=ksO2nitri)
    call self%get_parameter(self%rODUox       ,'rODUox',        default=rODUox)
    call self%get_parameter(self%ksO2oduox    ,'ksO2oduox',     default=ksO2oduox)
    call self%get_parameter(self%ksO2oxic     ,'ksO2oxic',      default=ksO2oxic)
    call self%get_parameter(self%ksNO3denit   ,'ksNO3denit',    default=ksNO3denit)
    call self%get_parameter(self%kinO2denit   ,'kinO2denit',    default=kinO2denit)
    call self%get_parameter(self%kinNO3anox   ,'kinNO3anox',    default=kinNO3anox)
    call self%get_parameter(self%kinO2anox    ,'kinO2anox',     default=kinO2anox)
    call self%get_parameter(self%rAnammox     ,'rAnammox',      default=rAnammox)
end if

!!------- derived parameters  ------- 
self%rq10         = Q10
self%res0         = 0.25d0*V_NC_max*zeta_CN
self%K_QN_phy     = QN_phy_max-QN_phy_0
self%iK_QN        = 1.0d0/self%K_QN_phy
self%iK_QP        = 1.0d0/(QP_phy_max-QP_phy_0)
self%iK_QSi       = 1.0d0/(QSi_phy_max-QSi_phy_0)
self%iK_QFe       = 1.0d0/(QFe_phy_max-QFe_phy_0)
self%itheta_max   = 1.0d0/theta_LHC
self%aver_QN_phy  = 5.0d-1*(QN_phy_max+QN_phy_0)
self%aver_QP_phy  = 5.0d-1*(QP_phy_max+QP_phy_0)
self%small_finite  = sqrt(small)

!!------- Register state variables  ------- 
call self%register_state_variable(self%id_nutN,  'nutN','mmol-N/m**3','Dissolved Inorganic Nitrogen DIN nutN', &
   nutN_initial, minimum=_ZERO_, no_river_dilution=nutrient_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_nutN)
call self%register_state_variable(self%id_phyC,  'phyC','mmol-C/m**3','Phytplankton Carbon phyC', &
   phyC_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_phyC)
call self%register_state_variable(self%id_phyN,  'phyN','mmol-N/m**3','Phytplankton Nitrogen phyN', &
   phyN_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_phyN)
call self%register_state_variable(self%id_detC,  'detC','mmol-C/m**3','Detritus Carbon detC', &
   detC_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_detC)
call self%register_state_variable(self%id_detN,  'detN','mmol-N/m**3','Detritus Nitrogen detN', &
   detN_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_detN)
call self%register_state_variable(self%id_domC,  'domC','mmol-C/m**3','Dissolved Organic Carbon domC', &
   domC_initial, minimum=_ZERO_, no_river_dilution=.false. )
call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_domC)
call self%register_state_variable(self%id_domN,  'domN','mmol-N/m**3','Dissolved Organic Nitrogen domN', &
   domN_initial, minimum=_ZERO_, no_river_dilution=.false. )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_domN)

if (self%RubiscoOn) then
    Rub = frac_Rub_ini * phyC_initial  ! trait times biomass
    call self%register_state_variable(self%id_Rub,   'Rub','-','fraction of Rubisco Rub', &
       Rub, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
end if

if (self%PhotoacclimOn) then
    chl = frac_chl_ini * phyC_initial  ! trait times biomass
    call self%register_state_variable(self%id_chl,   'chl','mg-Chl/m**3','Chl chl', &
       chl, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
end if

if (self%PhosphorusOn) then
    call self%register_state_variable(self%id_nutP,  'nutP','mmol-P/m**3','Dissolved Inorganic Phosphorus DIP nutP', &
       nutP_initial, minimum=_ZERO_, no_river_dilution=nutrient_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_nutP)
    call self%register_state_variable(self%id_phyP,  'phyP','mmol-P/m**3','Phytplankton Phosphorus phyP', &
       phyP_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_phyP)
    call self%register_state_variable(self%id_detP,  'detP','mmol-P/m**3','Detritus Phosphorus detP', &
       detP_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_detP)
    call self%register_state_variable(self%id_domP,  'domP','mmol-P/m**3','Dissolved Organic Phosphorus domP', &
       domP_initial, minimum=_ZERO_, no_river_dilution=.false. )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_domP)
end if

if (self%SiliconOn) then
    call self%register_state_variable(self%id_nutS,  'nutS','mmol-Si/m**3','Dissolved Inorganic Silicon Si nutS', &
       nutS_initial, minimum=_ZERO_, no_river_dilution=nutrient_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_silicate,self%id_nutS)
    call self%register_state_variable(self%id_phyS,  'phyS','mmol-Si/m**3','Phytplankton Silicon phyS', &
       phyS_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_silicate,self%id_phyS)
    call self%register_state_variable(self%id_detS,  'detS','mmol-Si/m**3','Detritus Silicon detS', &
       detS_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_silicate,self%id_detS)
 end if

 if (self%IronOn) then
    call self%register_state_variable(self%id_nutFe,  'nutFe','mmol-Fe/m**3','Dissolved Inorganic Iron Fe nutFe', &
       nutFe_initial, minimum=_ZERO_, no_river_dilution=nutrient_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_iron,self%id_nutFe)
    call self%register_state_variable(self%id_phyFe,  'phyFe','mmol-Fe/m**3','Phytplankton Iron phyFe', &
       phyFe_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_iron,self%id_phyFe)
    call self%register_state_variable(self%id_detFe,  'detFe','mmol-Fe/m**3','Detritus Iron detFe', &
       detFe_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_iron,self%id_detFe)
end if

if (self%GrazingOn) then
    call self%register_state_variable(self%id_zooC,  'zooC','mmol-C/m**3','Zooplankton Carbon zooC', &
       zooC_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_zooC)
end if

if (self%BioOxyOn) then
    call self%register_state_variable(self%id_nh3,   'nh3','mmolN/m**3','dissolved ammonium nh3', &
       nh3_initial, minimum=_ZERO_, no_river_dilution=.false. )
    call self%register_state_variable(self%id_oxy,   'oxy','mmolO2/m**3','dissolved oxygen oxy', &
       oxy_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%register_state_variable(self%id_odu,   'odu','mmolO2/m**3','dissolved reduced substances odu', &
       odu_initial, minimum=_ZERO_, no_river_dilution=.true. )
end if

if (self%VirusOn) then
    vir = vir_initial * phyC_initial  ! trait times biomass
    call self%register_state_variable(self%id_vir,   'vir','-','Virus C density in cells vir', &
       vir, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
end if

if (self%NResOn) then
    call self%register_state_variable(self%id_RNit,  'RNit','mmol-N/m**3','N-reservoir RNit', &
       RNit_initial, minimum=_ZERO_, no_river_dilution=.false. )
end if

!!------- Register diagnostic variables  ------- 
call self%register_diagnostic_variable(self%id_datt,    'datt','1/m', ' datt', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_vphys,   'vphys','-', ' vphys', &
  output=DOUT)

call self%register_diagnostic_variable(self%id_pPads,   'pPads','-', 'pPads', output=DOUT)

if (self%DebugDiagOn) then
call self%register_diagnostic_variable(self%id_tmp,     'tmp','-', 'Temporary_diagnostic_ tmp', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_fac4,    'fac4','-', 'Auxiliary_diagnostic_ fac4', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_fac5,    'fac5','-', 'Auxiliary_diagnostic_ fac5', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_fac3,    'fac3','-', 'Auxiliary_diagnostic_ fac3', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_fac1,    'fac1','-', 'dtheta_dt_due_to_flex_theta_ fac1', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_fac2,    'fac2','-', 'dtheta_dt_due_to_grad_theta_ fac2', &
  output=DOUT)
end if

if (self%BGC0DDiagOn) then
call self%register_diagnostic_variable(self%id_GPPR,    'GPPR','mmolC/m**3/d', 'gross_primary_production_ GPPR', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_Denitr,  'Denitr','mmol-N/m**3/d', 'denitrification_rate_ Denitr', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_dPAR,    'dPAR','W/m**2', 'Photosynthetically_Active_Radiation_ dPAR', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_DNP,     'DNP','-', 'DIN:DIP_ratio_ DNP', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_QNP,     'QNP','-', 'N:P_ratio_ QNP', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_qualPOM, 'qualPOM','-', 'Quality_of_POM_ qualPOM', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_qualDOM, 'qualDOM','-', 'Quality_of_DOM_ qualDOM', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_no3,     'no3','mmol-N/m**3', 'Nitrate_ no3', &
  output=DOUT)
end if

if (self%PhysiolDiagOn) then
call self%register_diagnostic_variable(self%id_chl2C,   'chl2C','gCHL/gC', 'chlC_ chl2C', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_Theta,   'Theta','-', 'Theta_ Theta', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_fracR,   'fracR','-', 'Rubisco_fract._allocation_ fracR', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_fracT,   'fracT','-', 'LHC_fract._allocation_ fracT', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_fracNU,  'fracNU','-', 'Nut._Uptake_fract._allocation_ fracNU', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_QN,      'QN','-', 'N:C_ratio_ QN', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_QP,      'QP','-', 'P:C_ratio_ QP', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_QSi,     'QSi','-', 'Si:C_ratio_ QSi', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_QFe,     'QFe','-', 'Fe:C_ratio_ QFe', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_aVN,     'aVN','-', 'N-uptake_activity_ aVN', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_aVP,     'aVP','-', 'P-uptake_activity_ aVP', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_aVSi,    'aVSi','-', 'Si-uptake_activity_ aVSi', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_aVFe,    'aVFe','-', 'Fe-uptake_activity_ aVFe', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_faN,     'faN','-', 'N-uptake_affinity_allocation_ faN', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_faP,     'faP','-', 'P-uptake_affinity_allocation_ faP', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_faSi,    'faSi','-', 'Si-uptake_affinity_allocation_ faSi', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_faFe,    'faFe','-', 'Fe-uptake_affinity_allocation_ faFe', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_rQN,     'rQN','-', 'Relative_N-Quota_ rQN', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_rQP,     'rQP','-', 'Relative_P-Quota_ rQP', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_rQSi,    'rQSi','-', 'Relative_Si-Quota_ rQSi', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_rQFe,    'rQFe','-', 'Relative_Fe-Quota_ rQFe', &
  output=DOUT)
end if

if (self%RateDiagOn) then
call self%register_diagnostic_variable(self%id_phyUR,   'phyUR','1/d', 'Phytoplankton_C_Uptake_Rate_ phyUR', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_phyRER,  'phyRER','1/d', 'Phytoplankton_Respiration_Rate_ phyRER', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_phyELR,  'phyELR','1/d', 'Phytoplankton_Exudation_Loss_Rate_ phyELR', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_phyALR,  'phyALR','1/d', 'Phytoplankton_Aggregation_Loss_Rate_ phyALR', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_phyVLR,  'phyVLR','1/d', 'Phytoplankton_Viral_Loss_Rate_ phyVLR', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_phyGLR,  'phyGLR','1/d', 'Phytoplankton_Grazing_Loss_Rate_ phyGLR', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_vsinkr,  'vsinkr','-', 'Relative_Sinking_Rate_ vsinkr', &
  output=DOUT)
call self%register_diagnostic_variable(self%id_zoomort, 'zoomort','1/d', 'Zooplankton_Mortality_Rate_ zoomort', &
  output=DOUT)
end if

! ------ check dependencies in diag switches -------
if (self%BGC2DDiagOn .and. .not. self%BGC0DDiagOn) call self%fatal_error('maecs_init','BGC2DDiagOn=TRUE requires BGC0DDiagOn=TRUE')
if (self%Budget2DDiagOn .and. .not. self%Budget0DDiagOn) call self%fatal_error('maecs_init','Budget2DDiagOn=TRUE requires Budget0DDiagOn=TRUE')
if (self%PhysiolDiagOn .and. .not. self%PhotoacclimOn) call self%fatal_error('maecs_init','PhysiolDiagOn=TRUE requires PhotoacclimOn=TRUE')
if (self%BGC0DDiagOn .and. .not. self%PhosphorusOn) call self%fatal_error('maecs_init','BGC0DDiagOn=TRUE requires PhosphorusOn=TRUE')
if (self%BGC0DDiagOn .and. .not. self%BioOxyOn) call self%fatal_error('maecs_init','BGC0DDiagOn=TRUE requires BioOxyOn=TRUE')

!!------- Register environmental dependencies  ------- 
call self%register_dependency(self%id_temp,standard_variables%temperature)
call self%register_dependency(self%id_par,standard_variables%downwelling_photosynthetic_radiative_flux)
call self%register_dependency(self%id_attpar,standard_variables%attenuation_coefficient_of_photosynthetic_radiative_flux)
call self%register_global_dependency(self%id_doy,standard_variables%number_of_days_since_start_of_the_year)
call self%register_dependency(self%id_vphys_dep,'vphys','','physiological_state_of_sinking_cells')
call self%register_horizontal_dependency(self%id_zmax,standard_variables%bottom_depth)

!call self%register_dependency(self%id_o2flux, standard_variable=type_horizontal_standard_variable('dissolved_oxygen_upward_flux_at_soil_surface','mmolO2 m-2','dissolved_oxygen_upward_flux_at_soil_surface'))
!call self%register_dependency(self%id_oduflux, standard_variable=type_horizontal_standard_variable('dissolved_reduced_substances_upward_flux_at_soil_surface','mmolO2 m-2','dissolved_reduced_substances_upward_flux_at_soil_surface'))
!!call self%register_dependency(self%id_tke_bot, standard_variable=type_horizontal_standard_variable('turbulent_kinetic_energy_at_soil_surface','m3','turbulent_kinetic_energy_at_soil_surface'))

call self%register_horizontal_dependency(self%id_lat,standard_variables%latitude)
call self%register_horizontal_dependency(self%id_lon,standard_variables%longitude)
call self%register_dependency(self%id_sal,standard_variables%practical_salinity)


if (self%Budget0DDiagOn) then
    call self%register_dependency(self%id_totC,standard_variables%total_carbon)
    call self%register_dependency(self%id_totN,standard_variables%total_nitrogen)
    call self%register_dependency(self%id_totP,standard_variables%total_phosphorus)
    call self%register_dependency(self%id_totS,standard_variables%total_silicate)
    call self%register_dependency(self%id_totFe,standard_variables%total_iron)
end if

if (self%Budget2DDiagOn) then
    call self%register_dependency(self%id_totC_vertint,vertical_integral(self%id_totC))
    call self%register_dependency(self%id_totN_vertint,vertical_integral(self%id_totN))
    call self%register_dependency(self%id_totP_vertint,vertical_integral(self%id_totP))
    call self%register_dependency(self%id_totS_vertint,vertical_integral(self%id_totS))
    call self%register_dependency(self%id_totFe_vertint,vertical_integral(self%id_totFe))
    call self%register_horizontal_diagnostic_variable(self%id_totC_vertint_diag,'totC_vertint','mmol-C/m**2','vertical_integral_total_carbon', output=DOUT)
    call self%register_horizontal_diagnostic_variable(self%id_totN_vertint_diag,'totN_vertint','mmol-N/m**2','vertical_integral_total_nitrogen', output=DOUT)
    call self%register_horizontal_diagnostic_variable(self%id_totP_vertint_diag,'totP_vertint','mmol-P/m**2','vertical_integral_total_phosphorus', output=DOUT)
    call self%register_horizontal_diagnostic_variable(self%id_totS_vertint_diag,'totS_vertint','mmol-Si/m**2','vertical_integral_total_silicate',output=DOUT)
    call self%register_horizontal_diagnostic_variable(self%id_totFe_vertint_diag,'totFe_vertint','mmol-Fe/m**2','vertical_integral_total_iron', output=DOUT)
end if

if (self%BGC2DDiagOn) then
    call self%register_dependency(self%id_GPPR_dep,'GPPR','mmol-C/m**3/d','Gross_Primary_Production_Rate')
    call self%register_dependency(self%id_GPPR_vertint,vertical_integral(self%id_GPPR_dep))
    call self%register_horizontal_diagnostic_variable(self%id_GPPR_vertint_diag,'GPPR_vertint','mmol-C/m**2/d','vertical_integral_gross_primary_production', output=DOUT)
    call self%register_dependency(self%id_Denitr_dep,'Denitr')
    call self%register_dependency(self%id_Denitr_vertint,vertical_integral(self%id_Denitr_dep))
    call self%register_horizontal_diagnostic_variable(self%id_Denitr_vertint_diag,'Denitr_vertint','mmol-N/m**2/d','vertical_integral_Denitrification', output=DOUT)
    call self%register_horizontal_diagnostic_variable(self%id_O2flux_diag,'O2flux','mmol-O2/m**2/d','oxygen_flux_between_sea_water_and_air', output=DOUT)
end if

if (self%ChemostatOn) then
    call self%register_dependency(self%id_CO2,standard_variables%practical_salinity)
end if

! extra lines included from maecs_incl.lst 
! complete N&P budgeting including components with fixed stoichiometry such as ZooC
if (self%GrazingOn) then
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_zooC,scale_factor=const_NC_zoo)
   if (self%PhosphorusOn) then
      call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_zooC,scale_factor=const_PC_zoo)
   end if 
end if

! special initialization of generic maecs structures
call maecs_init_stoichvars(self)




return

!!-------  if files are not found ...  
90 call self%fatal_error('maecs_init','Error reading namelist maecs_switch.')
91 call self%fatal_error('maecs_init','Error reading namelist maecs_init.')
92 call self%fatal_error('maecs_init','Error reading namelist maecs_pars.')
93 call self%fatal_error('maecs_init','Error reading namelist maecs_graz.')
94 call self%fatal_error('maecs_init','Error reading namelist maecs_env.')
95 call self%fatal_error('maecs_init','Error reading namelist maecs_omex.')
99 call self%fatal_error('maecs_init','Namelist maecs_switch was not found in file.')
100 call self%fatal_error('maecs_init','Namelist maecs_init was not found in file.')
101 call self%fatal_error('maecs_init','Namelist maecs_pars was not found in file.')
102 call self%fatal_error('maecs_init','Namelist maecs_graz was not found in file.')
103 call self%fatal_error('maecs_init','Namelist maecs_env was not found in file.')
104 call self%fatal_error('maecs_init','Namelist maecs_omex was not found in file.')

end subroutine initialize

!!----------------------------------------------------------------------
!!   end of section generated by parser 
!!----------------------------------------------------------------------
!#SP#


!documentation for the parser-generated initialize section could be provided here
! @fn fabm_hzg_maecs::initialize()
!


!> @brief to calculate light extinction when kc changes with depth
!> @details extinction coef=\f$ a_{\mathrm{water}} + a_{\mathrm{spm}}* (p+d+z) \f$
!> if &maecs_env/kwFzmaxMeth==0: a_{\mathrm{water}}=constant
!> if &maecs_env/kwFzmaxMeth==1: a_{\mathrm{water}}=a_w*f1(z); f1(z) is exponential
!> if &maecs_env/kwFzmaxMeth==2: a_{\mathrm{water}}=a_w*f2(z); f2(z) is sigmoidal
!> if &maecs_env/kwFzmaxMeth==3: a_{\mathrm{water}}=a_w*f2(z)f(t); f(t) is unimodal

   subroutine get_light_extinction(self,_ARGUMENTS_GET_EXTINCTION_)
!  
! !INPUT PARAMETERS:
   class(type_hzg_maecs),intent(in)          :: self 
   _DECLARE_ARGUMENTS_GET_EXTINCTION_
   
   real(rk) :: p,z,poc,doc,chl,kw,zmax,doy,fz,ft,A,B,L,fz1,fz2,attv,lo,la,ya,xa,tke_bot
   real(rk), PARAMETER ::  Pi = 3.1415927_rk
   
   ! Enter spatial loops (if any)
   _LOOP_BEGIN_

#if _DEBUG_
 write(*,'(A)') 'begin light_ext'
#endif
   ! Retrieve current (local) state variable values.  
   _GET_(self%id_phyC,p) ! phytoplankton
   _GET_(self%id_detC,poc) ! particulate organic carbon
   _GET_(self%id_domC,doc) ! dissolved organic carbon
   if (self%GrazingOn) then
    _GET_(self%id_zooC, z)  ! Zooplankton Carbon in mmol-C/m**3
   else
     z=0.0_rk 
   end if
   if (self%PhotoacclimOn .and. self%a_chl .gt. 0.d0) then
      _GET_(self%id_chl, chl)  ! Chl in mg-Chla/mmol-C
   else
     chl=0.0_rk 
   end if

   !default: 
   fz=1.0_rk 
   ft=1.0_rk 
   !if (self%kwFzmaxMeth .eq. 0) then
     !constant bg attenuation. Do nothing     select case (self%kwFzmaxMeth)

   if (self%kwFzmaxMeth .eq. 1) then
     _GET_HORIZONTAL_(self%id_zmax, zmax)  ! max depth
     !f(z) exponential convergence to the 10% of 'self%a_water' with depth
     fz=self%a_minfr + (1-self%a_minfr)*exp(-zmax/11.0)
   else if (self%kwFzmaxMeth .ge. 2) then
     _GET_HORIZONTAL_(self%id_zmax, zmax)  ! max depth
     !f(z)=sigmoidal function of depth with an upper plateau (100%) at 0-10 m and a lower (10%) for 30+
     fz1 = (1.0-self%a_minfr)*(1.0-1.0/(1.0+exp(-zmax*0.5_rk+self%a_fz)))
     fz=self%a_minfr+fz1
     if (self%kwFzmaxMeth .ge. 3) then
       _GET_GLOBAL_ (self%id_doy,doy) !day of year
      !f(t)=sinusoidal function of day of year with minimum occuring during summer
      !parameters below were fitted by J.Maerz using the scanfish data from the German Bight
      A=8.036
      B=9.78
      L=72.42
      ft= 0.05*(A*sin(2.0*doy*Pi/365.0 +2.0*L*Pi/365.0)+B)
      !write (*,'(A, F7.6)') 'ft term: ',0.05*(A*sin(2.0*doy*Pi/365.0 +2.0*L*Pi/365.0)+B)
     end if
     kw=self%a_water*fz*ft
   endif
! additional extras in turbidity calculation
   if (self%kwFzmaxMeth .eq. 4) then
    !!_GET_HORIZONTAL_(self%id_tke_bot,tke_bot) ! Latitude  [degN]
    !f(z)=sigmoidal function of depth with an upper plateau (100%) at 0-10 m and a lower (10%) for 30+
    fz = self%a_minfr+fz1*(ft+sqrt(tke_bot*750))*0.5
    !write (*,'(A, F7.6)') 'fz term: ',(1.0-self%a_minfr)*(1.0-1.0/(1.0+exp(-zmax*0.5+10))) 
    kw = self%a_water*fz
   else if (self%kwFzmaxMeth .gt. 4) then  ! emulate turbid East Anglia plume
 !!    write (*,'(L2)'),_AVAILABLE_(self%id_lon)
     _GET_HORIZONTAL_(self%id_lon,lo)! Longitude [degE]
     _GET_HORIZONTAL_(self%id_lat,la) ! Latitude  [degN]
    ! _GET_(self%id_sal,ft) ! Latitude  [degN]
     xa=0.7
     ya=52.5
 !    write (*,'(A, 2(F9.3))') 'sal depth: ',ft,zmax
!     ft= sin((doy-60)*Pi/365)**2
     fz=exp(-3*(fz-self%a_minfr))*0.25*(self%kwFzmaxMeth-4) *exp(-(((la-ya+xa*lo)/2-xa*lo)**2+((la-ya+xa*lo)/2+ya-la)**2)/3-(xa*(lo-2))**2/10) !-(y-53)**2/8
 !    write (*,'(A, 4(F9.3))') 'lo,la: ',lo,la,((la-ya+xa*lo)/2-xa*lo)**2+((la-ya+xa*lo)/2+ya-la)**2,fz
     kw=kw+self%a_water*fz
   end if
   
   ! Attenuation as a result of background turbidity and self-shading of phytoplankton.
   attv =  kw + self%a_spm*(poc+z)+ self%a_doc*doc+ self%a_phyc*p + self%a_chl*chl

   if (attv .gt. 15.) then
      attv = 15.0_rk
   end if

   _SET_EXTINCTION_(attv)
   
#if _DEBUG_
!write (*,'(A, 2(F5.2), I4, 3(F5.2))') 'zmax,t,meth,fz,ft,kw: ',zmax,doy,self%kwFzmaxMeth,fz,ft,kw
write(*,'(A)') 'end light_ext'
#endif
   ! Leave spatial loops (if any)
   _LOOP_END_

   end subroutine get_light_extinction
!EOC


!> @brief a brief description to be added
!> @details some details to be added
subroutine maecs_init_stoichvars(self)
   class(type_hzg_maecs),intent(inout)          :: self 

!use maecs_types
!implicit none 

!type (type_maecs_nutindex) :: ni
real(rk)    :: norder, pb
integer     :: nm

norder = self%NutOrder
nm     = 0
if (norder .gt. 1.) then
  ! --------- nitrogen -------------
  pb     = 10**floor(log10(norder))
  self%nutind%iN  = nint(norder/pb)
  norder = norder -  self%nutind%iN * pb
  nm     = nm + 1
  if (norder .gt. 0.99999) then
    !  --------- phosphorus --------- 
    pb     = 10**floor(log10(norder))
    self%nutind%iP  = nint(norder/pb)
    norder = norder - self%nutind%iP * pb
    nm     = nm + 1
    if (norder .gt. 0.99999) then
        !  ---------iron ----------- 
        pb     = 10**floor(log10(norder))
        self%nutind%iFe = nint(norder/pb)
        norder = norder - self%nutind%iFe * pb
        nm     = nm + 1
        if (norder .gt. 0.99999) then
          !  --------- silicon ----------- 
          pb     = 10**floor(log10(norder))
          self%nutind%iSi = nint(norder/pb)
          norder = norder - self%nutind%iSi * pb
          nm     = nm + 1
       end if
    end if
  end if  
else
 self%nutind%iN  = 1
 self%nutind%iP  = 2
 self%nutind%iFe = 3
 self%nutind%iSi = 4
!nm = 3
 nm = 4
endif

! evaluate number of considered limiting nutrients  
self%nutind%nutnum = 2 ! N and C are mandatory
if (self%PhosphorusOn) then
  self%nutind%nutnum = self%nutind%nutnum + 1
end if

! Iron
if (self%IronOn) then
  self%nutind%nutnum = self%nutind%nutnum + 1
end if

! silicon
if (self%SiliconOn) then
  self%nutind%nutnum = self%nutind%nutnum + 1
end if


! special setting for synchrony dependency on relative quota: nutrient index
nh = nint(10*(self%NutOrder-floor(self%NutOrder))) 
if ( nh .gt. 0 .and. nh .le. nm) then
  self%nutind%nhi = nh  ! element number corr. to first lower digit
else
  self%nutind%nhi = 1  ! default: first element
endif

!write (*,'(A,5(I4))') 'No No N P Si
!Fe:',nm,self%nutind%nutnum,self%nutind%iN,self%nutind%iP,self%nutind%iSi,self%nutind%iFe
 
if (self%nutind%nutnum-1 .gt. nm) call self%fatal_error('maecs_init','Not enough nutrient indices provided by NutOrder.')

! build exponents from par value for experimental reshaping of synchrony function
!if (self%maxVal .lt. -9.5d0) then 
!  nm = nint(-self%maxVal) - 10
!  self%nutind%nfV  = floor(nm*0.5d0)
!  self%nutind%nSRN = mod(nm,2)
!  write (*,'(A,1(F7.2),3(I4))') 'syn exp: ',self%maxVal,nm,self%nutind%nfV, self%nutind%nSRN
!else
!  self%nutind%nfV  = 1
!  self%nutind%nSRN = 1
!endif

end subroutine maecs_init_stoichvars 

#include "maecs_do.F90"

end module hzg_maecs
