#include "fabm_driver.h"
module maecs_types

use fabm_types

public type_maecs_sensitivities, type_maecs_om, &
       type_maecs_traitdyn, type_maecs_phy, type_maecs_zoo, &
       type_maecs_allocation_fractions, &
       type_maecs_base_model

<<<<<<< HEAD
! the maecs base type containing parameters and variables id's

!  Original author(s): Richard Hofmeister & Kai Wirtz

!#SP0
!!----------------------------------------------------------------------
!! this code is generated by a parser  (conv_nml_fabm.c by kai wirtz)
!!----------------------------------------------------------------------
type type_maecs_env
 real(rk) :: temp,par
end type
type type_maecs_rhs
 real(rk) :: nutN,nutP,phyC,phyN,phyP,zooC,detC,detN,detP,domC,domN,domP,Rub,chl
end type
! standard fabm model types
type,extends(type_base_model),public :: type_maecs_base_model
type (type_state_variable_id)        :: id_nutN,id_nutP,id_phyC,id_phyN,id_phyP,id_zooC,id_detC,id_detN,id_detP,id_domC,id_domN,id_domP,id_Rub,id_chl
type (type_dependency_id)            :: id_temp
type (type_dependency_id)            :: id_par
type (type_diagnostic_variable_id)   :: id_chl2, id_fracR, id_rhs_nutN, id_rhs_nutP, id_rhs_phyC, id_rhs_phyN, id_rhs_phyP, id_rhs_zooC, id_rhs_detC, id_rhs_detN, id_rhs_detP, id_rhs_domC, id_rhs_domN, id_rhs_domP, id_rhs_Rub, id_rhs_chl
=======
type,extends(type_base_model),public :: type_maecs_base_model
! the maecs base type containing parameters and variables id's

type (type_state_variable_id)        :: id_nutN,id_nutP,id_phyC,id_phyN,id_phyP,id_zooC,id_detC,id_detN,id_detP,id_domC,id_domN,id_domP,id_Rub2,id_chl
type (type_dependency_id)            :: id_temp
type (type_dependency_id)            :: id_par
type (type_diagnostic_variable_id)   :: id_chl2, id_fracR, id_tmp
>>>>>>> 560e3dbbe7b9557d60044e0e8f65e141e09252ce
type (type_conserved_quantity_id)    :: id_totC, id_totN, id_totP
real(rk) ::  nutN_initial, nutP_initial, phyC_initial, phyN_initial, phyP_initial, zooC_initial, detC_initial, detN_initial, detP_initial, domC_initial, domN_initial, domP_initial, frac_Rub_ini, frac_chl_ini
real(rk) ::  P_max, alpha, sigma, theta_LHC, rel_chloropl_min, QN_phy_0, QN_phy_max, V_NC_max, AffN, zeta_CN, exud_phy, QP_phy_0, QP_phy_max, V_PC_max, AffP, adap_rub, adap_theta, tau_regV, phi_agg, vS_phy, vS_det, hydrol, remin, Ae_all, T_ref
real(rk) ::  const_NC_zoo, const_PC_zoo, g_max, k_grazC, yield_zoo, basal_resp_zoo, mort_zoo
real(rk) ::  a_water, a_spm, a_chl, frac_PAR, small, dil
real(rk) ::  K_QN_phy, iK_QN, iK_QP, itheta_max, aver_QN_phy, aver_QP_phy, small_finite
logical  ::  RubiscoOn, PhotoacclimOn, PhosphorusOn, GrazingOn, BioCarbochemOn, BioOxyOn, DebugDiagOn, ChemostatOn
<<<<<<< HEAD
end type type_maecs_base_model

!
!#SP#

!!-------------------------------------------------------------------
=======

end type type_maecs_base_model

type type_maecs_env
 real(rk) :: temp,par
end type

type  type_maecs_rhs
 real(rk) :: nutN,nutP,phyC,phyN,phyP,zooC,detC,detN,detP,domC,domN,domP,Rub2,chl
end type

!  Original author(s): Richard Hofmeister & Kai Wirtz
!#SP0
!!----------------------------------------------------------------------
!! this code is generated by a parser  (conv_nml_fabm.c by kai wirtz)
!!----------------------------------------------------------------------

>>>>>>> 560e3dbbe7b9557d60044e0e8f65e141e09252ce
type type_maecs_om
   real(rk) :: C,N,P
end type

type type_maecs_allocation_fractions
   real(rk) :: Rub
   real(rk) :: theta
   real(rk) :: NutUpt ! remaining nitrogen fraction for uptake and processing            [dimensionless]
   real(rk) :: TotFree ! nitrogen fraction of free/available proteins/enzymes and RNA    [dimensionless]
   real(rk) :: rel_phys ! physiological(=energetical&nutritional) status 0...1
end type

type type_maecs_phy
      real(rk)   :: C,N,P
      real(rk)   :: C_reg, N_reg, P_reg
      real(rk)   :: chl, Rub
      real(rk)   :: rel_chloropl
      real(rk)   :: rel_QN, rel_QP, rel_QNP
      real(rk)   :: QN,QP,QPN,theta
      type (type_maecs_allocation_fractions) :: frac
end type

type type_maecs_zoo
      real(rk)   :: C,N,P
      real(rk)   :: yield,flopp
      real(rk)   :: QN,QP
      real(rk)   :: feeding
end type

! Time and Chl derivatives of trait variables
type type_maecs_traitdyn
      real(rk)   :: dtheta_dt
      real(rk)   :: dfracR_dt
      real(rk)   :: dRchl_dtheta
      real(rk)   :: dRchl_dfracR 
      real(rk)   :: dRchl_dQN
      real(rk)   :: tmp,fac1,fac2  ! for volatile diagnostics
end type


! TODO generalize matter structure C,N,P,QN,QP

type type_maecs_derivative
   real(rk) :: dregV
   real(rk) :: dtheta
   real(rk) :: dfracR
   real(rk) :: dfracP
   real(rk) :: dQN
end type

type type_maecs_sensitivities
   real(rk) :: func_T   ! temperature dependency of metabolic rates
   real(rk) :: P_max_T  ! temperature dependent maximum photosynthetic rate                        [d^{-1}]
   real(rk) :: a_light  ! exponent of light limitation 'S_phot'                             [dimensionless]
   real(rk) :: S_phot   ! light limitation                                                  [dimensionless]
   real(rk) :: up_NC    ! C specific N-uptake
   real(rk) :: up_PC    ! C specific P-uptake	
end type


end module

!!----------------------------------------------------------------------
!! end of section generated by a parser 
!!----------------------------------------------------------------------

