!> @file maecs_types.F90
!> @brief maecs_types module
!> @author Richard Hofmeister, Kai Wirtz, Onur Kerimoglu
!> @copyright HZG
!  HZG 2011-2014

#include "fabm_driver.h"

!> @brief  Data types used in fabm_hzg_maecs are defined here
!> @details 
!> @todo: !!! documentation is interfering with the parser !!!
module maecs_types

use fabm_types

public type_maecs_sensitivities, type_maecs_om, &
       type_maecs_traitdyn, type_maecs_phy, type_maecs_zoo, &
       type_maecs_allocation_fractions, &
       type_maecs_base_model



!#SP0
!!----------------------------------------------------------------------
!! this code is generated by a parser  (conv_nml_fabm.c by kai wirtz)
!!----------------------------------------------------------------------
!> @brief stores environmental dependencies
type type_maecs_env
 real(rk) :: temp,par
end type

!> @brief stores right hand sides
!> @todo: need for a parameter list?
type type_maecs_rhs
 real(rk) :: nutN,nutP,nutS,phyC,phyN,phyP,phyS,zooC,detC,detN,detP,detS,domC,domN,domP,Rub,chl
end type

!> @brief stores standard fabm model types and self-parameters
!> @details this model type parents the FABM-recognized type_maecs_base_model 
!> \n Model parameters, descriptions and corresponding symbols used in formulas:
!> \describepar{P\_max, P_{max}, : phyto max. growth rate}
!> @todo: complete the parameter list
type,extends(type_base_model),public :: type_maecs_base_model
type (type_state_variable_id)        :: id_nutN,id_nutP,id_nutS,id_phyC,id_phyN,id_phyP,id_phyS,id_zooC,id_detC,id_detN,id_detP,id_detS,id_domC,id_domN,id_domP,id_Rub,id_chl
type (type_dependency_id)            :: id_temp
type (type_dependency_id)            :: id_par
type (type_diagnostic_variable_id)   :: id_chl2, id_fracR, id_QN, id_QP, id_aVN, id_aVP, id_aVSi, id_rQSi, id_tmp, id_fac1, id_fac2
real(rk) ::  nutN_initial, nutP_initial, nutS_initial, phyC_initial, phyN_initial, phyP_initial, phyS_initial, zooC_initial, detC_initial, detN_initial, detP_initial, detS_initial, domC_initial, domN_initial, domP_initial, frac_Rub_ini, frac_chl_ini
real(rk) ::  P_max, alpha, sigma, theta_LHC, rel_chloropl_min, QN_phy_0, QN_phy_max, V_NC_max, AffN, zeta_CN, zstoich_PN, exud_phy, QP_phy_0, QP_phy_max, V_PC_max, AffP, QSi_phy_0, QSi_phy_max, V_SiC_max, AffSi, syn_nut, adap_rub, adap_theta, tau_regV, phi_agg, vS_phy, vS_det, hydrol, remin, Ae_all, T_ref
real(rk) ::  const_NC_zoo, const_PC_zoo, g_max, k_grazC, yield_zoo, basal_resp_zoo, mort_zoo
real(rk) ::  a_water, a_spm, a_chl, frac_PAR, small, dil
real(rk) ::  K_QN_phy, iK_QN, iK_QP, iK_QSi, itheta_max, aver_QN_phy, aver_QP_phy, small_finite
logical  ::  RubiscoOn, PhotoacclimOn, PhosphorusOn, SiliconOn, GrazingOn, BioCarbochemOn, BioOxyOn, DebugDiagOn, ChemostatOn, UptakeLock, detritus_no_river_dilution, plankton_no_river_dilution
end type type_maecs_base_model

!
!#SP#

!!-------------------------------------------------------------------

type type_maecs_switch
   logical :: isP, isSi, isTotIng
end type

type type_maecs_om
   real(rk) :: C,N,P,Si
end type

type type_maecs_basic_traits ! traits that apply to all -planktonic- life forms
   real(rk) :: lESD, vESD
   real(rk) :: trophy
end type

type type_maecs_allocation_fractions
   real(rk) :: Rub
   real(rk) :: theta
   real(rk) :: NutUpt ! remaining nitrogen fraction for uptake and processing            [dimensionless]
   real(rk) :: TotFree ! nitrogen fraction of free/available proteins/enzymes and RNA    [dimensionless]
end type

type,extends(type_maecs_om) :: type_maecs_life
      type (type_maecs_om)            :: Q       ! quotaformer QN,QP,QPN
      type (type_maecs_basic_traits)  :: tr
end type type_maecs_life

type,extends(type_maecs_life) :: type_maecs_phy
      type (type_maecs_om) :: relQ   ! former rel_QN, rel_QP, rel_QNP
      type (type_maecs_om) :: reg    ! former C_reg, N_reg, P_reg
      real(rk)   :: chl, Rub
      real(rk)   :: rel_chloropl
      real(rk)   :: theta
      real(rk)   :: rel_phys ! physiological/energy/nutritional status 0...1
      type (type_maecs_allocation_fractions) :: frac
end type type_maecs_phy


type,extends(type_maecs_life) :: type_maecs_zoo
      real(rk)   :: yield,flopp
      real(rk)   :: feeding
end type type_maecs_zoo

! Time and Chl derivatives of trait variables
type type_maecs_traitdyn
      real(rk)   :: dtheta_dt
      real(rk)   :: dfracR_dt
      real(rk)   :: dRchl_dtheta
      real(rk)   :: dRchl_dfracR 
      real(rk)   :: dRchl_dQN
      type (type_maecs_om) :: aV
      real(rk)   :: tmp,fac1,fac2  ! for volatile diagnostics
!      type (type_maecs_om) :: dV_dfracR, dV_dtheta
end type
                                       

type type_maecs_sensitivities
   real(rk) :: f_T       ! temperature dependency of metabolic rates
   real(rk) :: P_max_T  ! temperature dependent maximum photosynthetic rate                        [d^{-1}]
   real(rk) :: a_light  ! exponent of light limitation 'upt_pot%C'                             [dimensionless]
   type (type_maecs_om) :: upt_pot ! potential uptake rates
				   ! depending on ambient concentration incl. light limitation [dimensionless]
end type type_maecs_sensitivities

! new meta structure for pointing/looping over elements
type stoichiometry_pointer
   real(rk),pointer  :: upt, upt_act, upt_pot
   real(rk),pointer  :: aV
   real(rk)          :: relQ, Q
   real(rk)          :: iKQ
end type stoichiometry_pointer

end module

!!----------------------------------------------------------------------
!! end of section generated by a parser 
