#include "fabm_driver.h"
module maecs_types

use fabm_types

public type_maecs_sensitivities, type_maecs_om, &
       type_maecs_traitdyn, type_maecs_phy, type_maecs_zoo, &
       type_maecs_allocation_fractions

!  Original author(s): Richard Hofmeister & Kai Wirtz
!#SP0
!!----------------------------------------------------------------------
!! this code is generated by a parser  (conv_nml_fabm.c by kai wirtz)
!!----------------------------------------------------------------------

type type_maecs_om
   REALTYPE :: C,N,P
end type

type type_maecs_allocation_fractions
   REALTYPE :: Rub
   REALTYPE :: theta
   REALTYPE :: NutUpt ! remaining nitrogen fraction for uptake and processing            [dimensionless]
   REALTYPE :: TotFree ! nitrogen fraction of free/available proteins/enzymes and RNA    [dimensionless]
end type

type type_maecs_phy
      REALTYPE   :: C,N,P
      REALTYPE   :: C_reg, N_reg, P_reg
      REALTYPE   :: Chl, Rub
      REALTYPE   :: rel_chloropl
      REALTYPE   :: rel_QN, rel_QP, rel_QNP
      REALTYPE   :: QN,QP,QPN,theta
      type (type_maecs_allocation_fractions) :: frac
end type

type type_maecs_zoo
      REALTYPE   :: C,N,P
      REALTYPE   :: yield,flopp
      REALTYPE   :: QN,QP
      REALTYPE   :: feeding
end type

! Time and Chl derivatives of trait variables
type type_maecs_traitdyn
      REALTYPE   :: dtheta_dt
      REALTYPE   :: dfracR_dt
      REALTYPE   :: dRchl_dtheta
      REALTYPE   :: dRchl_dfracR 
      REALTYPE   :: dRchl_dQN
      REALTYPE   :: tmp,fac1,fac2  ! for volatile diagnostics
      REALTYPE   :: bal_C,bal_N,bal_P  ! for mass balancing
end type


! TODO generalize matter structure C,N,P,QN,QP

type type_maecs_derivative
   REALTYPE :: dregV
   REALTYPE :: dtheta
   REALTYPE :: dfracR
   REALTYPE :: dfracP
   REALTYPE :: dQN
end type

type type_maecs_sensitivities
   REALTYPE :: func_T   ! temperature dependency of metabolic rates
   REALTYPE :: P_max_T  ! temperature dependent maximum photosynthetic rate                        [d^{-1}]
   REALTYPE :: a_light  ! exponent of light limitation 'S_phot'                             [dimensionless]
   REALTYPE :: S_phot   ! light limitation                                                  [dimensionless]
   REALTYPE :: up_NC    ! C specific N-uptake
   REALTYPE :: up_PC    ! C specific P-uptake	
end type

type type_maecs_limitation_factors
   REALTYPE :: fac_PN_colim
   REALTYPE :: lim_P, lim_N
end type

end module

!!----------------------------------------------------------------------
!! end of section generated by a parser 
!!----------------------------------------------------------------------

