! @file maecs.F90 

#include "fabm_driver.h"

!> @brief This is the module registered in FABM
!> @details all the maecs_types are made available to this module
!! @todo looking at the rhs calculations in maecs_do, id_Rub and id_chl are set (correctly) as bulk variables (X*phyC).
!! however from the units, it looks as if they are registered (wrongly) as property variables (X)??
module fabm_hzg_maecs
use fabm_types
use maecs_types

!implicit none

private

public type_maecs_env,type_maecs_rhs
! --- HZG model types


! standard fabm model types

!> @brief this is the model type FABM uses to create the mode
! @defgroup main main_model_members
! @name //@{ //@}
!> @details the parent type (type_maecs_base_model) was defined in maecs_types module
type,extends(type_maecs_base_model),public :: type_hzg_maecs 
 contains
  procedure :: initialize
  procedure :: do => maecs_do
  procedure :: get_light_extinction
  procedure :: get_vertical_movement=>maecs_get_vertical_movement
end type type_hzg_maecs

!interface
  ! @brief @brief interface for the external procedure contained in maecs_main module
  ! @details phyto sinking rate depends on the nutritional state, so for each node:
  ! \n \f$ phy\%relQ \f$ obtained by calling calc_internal_states(self,phy,det,dom,zoo) 
  ! \n then \f$ phyQstat=phy\%relQ\%N * phy\%relQ\%P \f$
  ! \n finally, vsink = maecs_functions::sinking(self\%vS_phy, phyQstat, vsink)
!   subroutine maecs_get_vertical_movement(self, _ARGUMENTS_GET_VERTICAL_MOVEMENT_) 
!   import type_hzg_maecs,type_environment,rk
!   class (type_hzg_maecs),intent(in) :: self
!   _DECLARE_ARGUMENTS_GET_VERTICAL_MOVEMENT_
!   end subroutine
! end interface

!#SP0
!!----------------------------------------------------------------------
!! this code is generated by a parser  (conv_nml_fabm.c by kai wirtz)
!!----------------------------------------------------------------------
! --- HZG model types
!!--------------------------------------------------------------------

contains
!> @brief initializes the model
!! @details here the maecs namelists are read and assigned respectively in the model type (self),
!! state & diagnostic variables are registered in FABM and dependencies are imported from FABM
!>
!> **Model parameters, descriptions and corresponding symbols used in formulas:**
! initial values
!> \describepar{nutN\_initial , \mathrm{DIN} , Dissolved Inorganic Nitrogen DIN, 30.0 mmol-N/m**3}
!> \describepar{nutP\_initial , \mathrm{Phy}_\mathrm{P} , Dissolved Inorganic Phosphorus DIP, 1.2 mmol-P/m**3}
!> \describepar{nutS\_initial , \mathrm{Phy}_\mathrm{Si} , Dissolved Inorganic Silicon Si, 20. mmol-Si/m**3}
!> \describepar{phyC\_initial , \mathrm{Phy}_\mathrm{C} , Phytplankton Carbon, 10 mmol-C/m**3}
!> \describepar{phyN\_initial , \mathrm{phyN_initial} , Phytplankton Nitrogen, 0.8 mmol-N/m**3}
!> \describepar{phyP\_initial , \mathrm{phyP_initial} , Phytplankton Phosphorus, 0.08 mmol-P/m**3}
!> \describepar{phyS\_initial , \mathrm{phyS_initial} , Phytplankton Silicon, 0.8 mmol-Si/m**3}
!> \describepar{zooC\_initial , \mathrm{zooC_initial} , Zooplankton Carbon, 0.1 mmol-C/m**3}
!> \describepar{detC\_initial , \mathrm{detC_initial} , Detritus Carbon, 1 mmol-C/m**3}
!> \describepar{detN\_initial , \mathrm{detN_initial} , Detritus Nitrogen, 0.1 mmol-N/m**3}
!> \describepar{detP\_initial , \mathrm{detP_initial} , Detritus Phosphorus, 0.01 mmol-P/m**3}
!> \describepar{detS\_initial , \mathrm{detS_initial} , Detritus Silicon, 0.1 mmol-Si/m**3}
!> \describepar{domC\_initial , \mathrm{domC_initial} , Dissolved Organic Carbon, 0.1 mmol-C/m**3}
!> \describepar{domN\_initial , \mathrm{domN_initial} , Dissolved Organic Nitrogen, 0.01 mmol-N/m**3}
!> \describepar{domP\_initial , \mathrm{domP_initial} , Dissolved Organic Phosphorus, 0.001 mmol-P/m**3}
!> \describepar{frac\_Rub\_ini , f_R , fraction of Rubisco, 0.4 -}
!> \describepar{Rub          , f_R\mathrm{Phy}_\mathrm{C}, trait x biomass}
!> \describepar{frac\_chl\_ini , f_\theta\theta_C , Chl:C ratio, 0.034 mg-Chla/mmol-C}
!> \describepar{chl          , f_\theta\theta_C\mathrm{Phy}_\mathrm{C}, trait x biomass}
! other parameters
!> \describepar{P\_max        , P_\mathrm{max}        , maximum potential photosynthetic rate, 12.0 d^{-1}}
!> \describepar{alpha        , \alpha        , specific light adsorption by chloroplasts, 0.12 m2 mol-C/(muE g-CHL)}
!> \describepar{sigma        , \sigma        , Q-dependency of Rubisco activity/chloroplast ratio, 0.0 }
!> \describepar{theta\_LHC    , \theta_\mathrm{C}    , Chlorophylla-to-C ratio of LHC, 1.2 mgChl mmolC^{-1}}
!> \describepar{rel\_chloropl\_min , \mathrm{rel_chloropl_min} , chloroplast-C to phy-C ratio, 0.01 mol-C/mol-C}
!> \describepar{QN\_phy\_0     , Q_{\mathrm{N}0}     , subsistence N-quota, 0.045 mol-N/mol-C}
!> \describepar{QN\_phy\_max   , Q_\mathrm{N}^\mathrm{ref}   , maximum N-quota, 0.24 mol-N/mol-C}
!> \describepar{V\_NC\_max     , V_\mathrm{max,N}^0     , maximum N uptake rate, 0.3 mol-N/(mol-C d)}
!> \describepar{AffN         , A_\mathrm{N}^0         , N-Affinity, 0.1 m3/(mmol-C d)}
!> \describepar{zeta\_CN      , \zeta_\mathrm{CN}      , respiratory costs of N-synthesis/NO3-reduction, 2.3 mol-C/mol-N}
!> \describepar{zstoich\_PN   , \mathrm{zstoich_PN}   , P-stoichiometry of active compounds(-> P costs), 3.8 mol-N/mol-P}
!> \describepar{exud\_phy     , \mathrm{exud_phy}     , phytoplankton exudation per production, 0.0 }
!> \describepar{QP\_phy\_0     , Q_{\mathrm{P}0}     , subsistence P-quota, 0.0 mol-P/mol-C}
!> \describepar{QP\_phy\_max   , Q_\mathrm{P}^\mathrm{ref}   , subsistence P-quota, 0.02 mol-P/mol-C}
!> \describepar{V\_PC\_max     , V_\mathrm{max,P}^0     , maximum P uptake rate, 0.03 mol-P/(mol-C d)}
!> \describepar{AffP         , A_\mathrm{P}^0         , P-Affinity, 0.07 m3/(mmol-C d)}
!> \describepar{QSi\_phy\_0    , Q_{\mathrm{Si}0}    , subsistence Si-quota, 0.0 mol-Si/mol-C}
!> \describepar{QSi\_phy\_max  , Q_\mathrm{Si}^\mathrm{ref}  , subsistence Si-quota, 0.1 mol-Si/mol-C}
!> \describepar{V\_SiC\_max    , V_\mathrm{max,Si}^0    , maximum Si-uptake rate, 0.02 mol-Si/(mol-C d)}
!> \describepar{AffSi        , A_\mathrm{Si}^0        , Si-Affinity, 0.05 m3/(mmol-C d)}
!> \describepar{syn\_nut      , 1/h      , synchrony n\_queue in nutrient quota limitation, 2.0 }
!> \describepar{adap\_rub     , \delta_R     , adap\_rub, 1.0 }
!> \describepar{adap\_theta   , \delta_\theta   , adap\_theta, 1.0 }
!> \describepar{tau\_regV     , \Delta t_\mathrm{v}     , tau\_regV, 99.0 }
!> \describepar{phi\_agg      , \mathrm{phi_agg}      , quadratic aggregation rate, 5E-4 m^6 mmolN^{-2} d^{-1}}
!> \describepar{vS\_phy       , \mathrm{vS_phy}       , sinking velocity for phytoplankton, 5E-2 m d^{-1}}
!> \describepar{vS\_det       , \mathrm{vS_det}       , sinking velocity for detritus, 2. m d^{-1}}
!> \describepar{hydrol       , \mathrm{hydrol}       , hydrolysis rate, 0.03 d^{-1}}
!> \describepar{remin        , \mathrm{remin}        , pelagic remineralisation, 0.03 d^{-1}}
!> \describepar{Ae\_all       , \mathrm{Ae_all}       , Activation energy, 4500.0 ...}
!> \describepar{T\_ref        , \mathrm{T_ref}        , reference temperature, 288.0 degC}
!> \describepar{NutOrder     , \mathrm{NutOrder}     , element order of recursive scheme. lower digit: synchrony element   , 123.1 serial order number N:P:Si}
!> \describepar{const\_NC\_zoo , \mathrm{const_NC_zoo} , zooplankton N:C ratio, 0.3 mol/mol}
!> \describepar{const\_PC\_zoo , \mathrm{const_PC_zoo} , zooplankton P:C ratio, 0.025 mol/mol}
!> \describepar{g\_max        , \mathrm{g_max}        , maximum grazing rate, 1. per d}
!> \describepar{k\_grazC      , \mathrm{k_grazC}      , half saturation graing, 5.0 mmolN/m**3}
!> \describepar{yield\_zoo    , \mathrm{yield_zoo}    , yield of herbivory, 0.35 }
!> \describepar{basal\_resp\_zoo , \mathrm{basal_resp_zoo} , basal respiration, 0.04 per d}
!> \describepar{mort\_zoo     , \mathrm{mort_zoo}     , quadratic mortality, 0.035 m**3/mmolN.d}
!> \describepar{a\_water      , \mathrm{a_water}      , background attenuation coefficient, 0.01 1/m}
!> \describepar{a\_spm        , \mathrm{a_spm}        , attenuation coefficient of SPM, 0.001 m**3/m.mmolC}
!> \describepar{a\_chl        , \mathrm{a_chl}        , attenuation coefficient due to Chl absorption, 0.02 m**3/m.mgChl}
!> \describepar{frac\_PAR     , \mathrm{frac_PAR}     , photosynthetically active fraction of light, 1.0 }
!> \describepar{small        , \mathrm{small}        , lower limit for denominator in ratios; small\_finite=sqrt(small), 1e-04 }
!> \describepar{dil          , \mathrm{dil}          , dilution of all concentrations except dissolved inorganics, 0.0 }
subroutine initialize(self, configunit)

class (type_hzg_maecs), intent(inout), target :: self
integer,                  intent(in)            :: configunit
!
! !LOCAL VARIABLES:
integer    :: namlst=19
!!------- Initial values of model maecs ------- 
real(rk)  :: nutN_initial ! Dissolved Inorganic Nitrogen DIN
real(rk)  :: nutP_initial ! Dissolved Inorganic Phosphorus DIP
real(rk)  :: nutS_initial ! Dissolved Inorganic Silicon Si
real(rk)  :: phyC_initial ! Phytplankton Carbon
real(rk)  :: phyN_initial ! Phytplankton Nitrogen
real(rk)  :: phyP_initial ! Phytplankton Phosphorus
real(rk)  :: phyS_initial ! Phytplankton Silicon
real(rk)  :: zooC_initial ! Zooplankton Carbon
real(rk)  :: detC_initial ! Detritus Carbon
real(rk)  :: detN_initial ! Detritus Nitrogen
real(rk)  :: detP_initial ! Detritus Phosphorus
real(rk)  :: detS_initial ! Detritus Silicon
real(rk)  :: domC_initial ! Dissolved Organic Carbon
real(rk)  :: domN_initial ! Dissolved Organic Nitrogen
real(rk)  :: domP_initial ! Dissolved Organic Phosphorus
real(rk)  :: frac_Rub_ini ! fraction of Rubisco
real(rk)  :: Rub  ! trait times biomass
real(rk)  :: frac_chl_ini ! Chl:C ratio
real(rk)  :: chl  ! trait times biomass
!!------- Parameters from nml-list maecs_pars ------- 
real(rk)  :: P_max        ! maximum potential photosynthetic rate
real(rk)  :: alpha        ! specific light adsorption by chloroplasts
real(rk)  :: sigma        ! Q-dependency of Rubisco activity/chloroplast ratio
real(rk)  :: theta_LHC    ! Chlorophylla-to-C ratio of LHC
real(rk)  :: rel_chloropl_min ! chloroplast-C to phy-C ratio
real(rk)  :: QN_phy_0     ! subsistence N-quota
real(rk)  :: QN_phy_max   ! maximum N-quota
real(rk)  :: V_NC_max     ! maximum N uptake rate
real(rk)  :: AffN         ! N-Affinity
real(rk)  :: zeta_CN      ! respiratory costs of N-synthesis/NO3-reduction
real(rk)  :: zstoich_PN   ! P-stoichiometry of active compounds(-> P costs)
real(rk)  :: exud_phy     ! phytoplankton exudation per production
real(rk)  :: QP_phy_0     ! subsistence P-quota
real(rk)  :: QP_phy_max   ! subsistence P-quota
real(rk)  :: V_PC_max     ! maximum P uptake rate
real(rk)  :: AffP         ! P-Affinity
real(rk)  :: QSi_phy_0    ! subsistence Si-quota
real(rk)  :: QSi_phy_max  ! subsistence Si-quota
real(rk)  :: V_SiC_max    ! maximum Si-uptake rate
real(rk)  :: AffSi        ! Si-Affinity
real(rk)  :: syn_nut      ! synchrony n_queue in nutrient quota limitation
real(rk)  :: adap_rub     ! adap_rub
real(rk)  :: adap_theta   ! adap_theta
real(rk)  :: tau_regV     ! tau_regV
real(rk)  :: phi_agg      ! quadratic aggregation rate
real(rk)  :: vS_phy       ! sinking velocity for phytoplankton
real(rk)  :: vS_det       ! sinking velocity for detritus
real(rk)  :: hydrol       ! hydrolysis rate
real(rk)  :: remin        ! pelagic remineralisation
real(rk)  :: Ae_all       ! Activation energy
real(rk)  :: T_ref        ! reference temperature
real(rk)  :: NutOrder     ! element order of recursive scheme. lower digit: synchrony element   
!!------- Parameters from nml-list maecs_graz ------- 
real(rk)  :: const_NC_zoo ! zooplankton N:C ratio
real(rk)  :: const_PC_zoo ! zooplankton P:C ratio
real(rk)  :: g_max        ! maximum grazing rate
real(rk)  :: k_grazC      ! half saturation graing
real(rk)  :: yield_zoo    ! yield of herbivory
real(rk)  :: basal_resp_zoo ! basal respiration
real(rk)  :: mort_zoo     ! quadratic mortality
!!------- Parameters from nml-list maecs_env ------- 
real(rk)  :: a_water      ! background attenuation coefficient
real(rk)  :: a_spm        ! attenuation coefficient of SPM
real(rk)  :: a_chl        ! attenuation coefficient due to Chl absorption
real(rk)  :: frac_PAR     ! photosynthetically active fraction of light
real(rk)  :: small        ! lower limit for denominator in ratios; small_finite=sqrt(small)
real(rk)  :: dil          ! dilution of all concentrations except dissolved inorganics
!!------- Switches for configuring model structure -------
logical   :: RubiscoOn    ! use Rubisco- here in C-units
logical   :: PhotoacclimOn ! use Photoacclimation
logical   :: PhosphorusOn ! resolve Phosphorus cycle
logical   :: SiliconOn    ! resolve Silicon cycle
logical   :: GrazingOn    ! use Zooplankton grazing
logical   :: BioCarbochemOn ! use geochemistry module
logical   :: BioOxyOn     ! use oxygen from other FABM model
logical   :: DebugDiagOn  ! output of all diagnostics
logical   :: ChemostatOn  ! use Chemostat mode 
logical   :: UptakeLock   ! use same allocation for all uptake systems (Smith2008)
logical   :: detritus_no_river_dilution ! use riverine det import
logical   :: plankton_no_river_dilution ! use riverine det import

namelist /maecs_switch/ &
  RubiscoOn, PhotoacclimOn, PhosphorusOn, SiliconOn, GrazingOn, BioCarbochemOn, &
  BioOxyOn, DebugDiagOn, ChemostatOn, UptakeLock, detritus_no_river_dilution, &
  plankton_no_river_dilution

namelist /maecs_init/ &
  nutN_initial, nutP_initial, nutS_initial, phyC_initial, phyN_initial, &
  phyP_initial, phyS_initial, zooC_initial, detC_initial, detN_initial, &
  detP_initial, detS_initial, domC_initial, domN_initial, domP_initial, &
  frac_Rub_ini, frac_chl_ini

namelist /maecs_pars/ &
  P_max, alpha, sigma, theta_LHC, rel_chloropl_min, QN_phy_0, QN_phy_max, &
  V_NC_max, AffN, zeta_CN, zstoich_PN, exud_phy, QP_phy_0, QP_phy_max, V_PC_max, &
  AffP, QSi_phy_0, QSi_phy_max, V_SiC_max, AffSi, syn_nut, adap_rub, adap_theta, &
  tau_regV, phi_agg, vS_phy, vS_det, hydrol, remin, Ae_all, T_ref, NutOrder

namelist /maecs_graz/ &
  const_NC_zoo, const_PC_zoo, g_max, k_grazC, yield_zoo, basal_resp_zoo, &
  mort_zoo

namelist /maecs_env/ &
  a_water, a_spm, a_chl, frac_PAR, small, dil

nutN_initial = 30.0_rk            ! mmol-N/m**3
nutP_initial = 1.2_rk             ! mmol-P/m**3
nutS_initial = 20._rk             ! mmol-Si/m**3
phyC_initial = 10_rk              ! mmol-C/m**3
phyN_initial = 0.8_rk             ! mmol-N/m**3
phyP_initial = 0.08_rk            ! mmol-P/m**3
phyS_initial = 0.8_rk             ! mmol-Si/m**3
zooC_initial = 0.1_rk             ! mmol-C/m**3
detC_initial = 1_rk               ! mmol-C/m**3
detN_initial = 0.1_rk             ! mmol-N/m**3
detP_initial = 0.01_rk            ! mmol-P/m**3
detS_initial = 0.1_rk             ! mmol-Si/m**3
domC_initial = 0.1_rk             ! mmol-C/m**3
domN_initial = 0.01_rk            ! mmol-N/m**3
domP_initial = 0.001_rk           ! mmol-P/m**3
frac_Rub_ini = 0.4_rk             ! -
frac_chl_ini = 0.034_rk           ! mg-Chla/mmol-C
P_max        = 12.0_rk            ! d^{-1}
alpha        = 0.12_rk            ! m2 mol-C/(muE g-CHL)
sigma        = 0.0_rk             ! 
theta_LHC    = 1.2_rk             ! mgChl mmolC^{-1}
rel_chloropl_min = 0.01_rk            ! mol-C/mol-C
QN_phy_0     = 0.045_rk           ! mol-N/mol-C
QN_phy_max   = 0.24_rk            ! mol-N/mol-C
V_NC_max     = 0.3_rk             ! mol-N/(mol-C d)
AffN         = 0.1_rk             ! m3/(mmol-C d)
zeta_CN      = 2.3_rk             ! mol-C/mol-N
zstoich_PN   = 3.8_rk             ! mol-N/mol-P
exud_phy     = 0.0_rk             ! 
QP_phy_0     = 0.0_rk             ! mol-P/mol-C
QP_phy_max   = 0.02_rk            ! mol-P/mol-C
V_PC_max     = 0.03_rk            ! mol-P/(mol-C d)
AffP         = 0.07_rk            ! m3/(mmol-C d)
QSi_phy_0    = 0.0_rk             ! mol-Si/mol-C
QSi_phy_max  = 0.1_rk             ! mol-Si/mol-C
V_SiC_max    = 0.02_rk            ! mol-Si/(mol-C d)
AffSi        = 0.05_rk            ! m3/(mmol-C d)
syn_nut      = 2.0_rk             ! 
adap_rub     = 1.0_rk             ! 
adap_theta   = 1.0_rk             ! 
tau_regV     = 99.0_rk            ! 
phi_agg      = 5E-4_rk            ! m^6 mmolN^{-2} d^{-1}
vS_phy       = 5E-2_rk            ! m d^{-1}
vS_det       = 2._rk              ! m d^{-1}
hydrol       = 0.03_rk            ! d^{-1}
remin        = 0.03_rk            ! d^{-1}
Ae_all       = 4500.0_rk          ! ...
T_ref        = 288.0_rk           ! degC
NutOrder     = 123.1_rk           ! serial order number N:P:Si
const_NC_zoo = 0.3_rk             ! mol/mol
const_PC_zoo = 0.025_rk           ! mol/mol
g_max        = 1._rk              ! per d
k_grazC      = 5.0_rk             ! mmolN/m**3
yield_zoo    = 0.35_rk            ! 
basal_resp_zoo = 0.04_rk            ! per d
mort_zoo     = 0.035_rk           ! m**3/mmolN.d
a_water      = 0.01_rk            ! 1/m
a_spm        = 0.001_rk           ! m**3/m.mmolC
a_chl        = 0.02_rk            ! m**3/m.mgChl
frac_PAR     = 1.0_rk             ! 
small        = 1e-04_rk           ! 
dil          = 0.0_rk             ! 


!--------- read namelists --------- 
write(0,*) ' read namelists ....'
open(namlst,file='maecs_switch.nml',status='old')
read(namlst,nml=maecs_switch,err=90,end=99)
open(namlst,file='maecs_init.nml',status='old')
read(namlst,nml=maecs_init,err=91,end=100)
open(namlst,file='maecs_pars.nml',status='old')
read(namlst,nml=maecs_pars,err=92,end=101)
open(namlst,file='maecs_graz.nml',status='old')
read(namlst,nml=maecs_graz,err=93,end=102)
open(namlst,file='maecs_env.nml',status='old')
read(namlst,nml=maecs_env,err=94,end=103)
! Store parameter values in our own derived type
! NB: all rates must be provided in values per day,
! and are converted here to values per second.

!!------- logical parameters: switches  -------
call self%get_parameter(self%RubiscoOn,     'RubiscoOn',     default=RubiscoOn)
call self%get_parameter(self%PhotoacclimOn,  'PhotoacclimOn',  default=PhotoacclimOn)
call self%get_parameter(self%PhosphorusOn,  'PhosphorusOn',  default=PhosphorusOn)
call self%get_parameter(self%SiliconOn,     'SiliconOn',     default=SiliconOn)
call self%get_parameter(self%GrazingOn,     'GrazingOn',     default=GrazingOn)
call self%get_parameter(self%BioCarbochemOn,  'BioCarbochemOn',  default=BioCarbochemOn)
call self%get_parameter(self%BioOxyOn,      'BioOxyOn',      default=BioOxyOn)
call self%get_parameter(self%DebugDiagOn,   'DebugDiagOn',   default=DebugDiagOn)
call self%get_parameter(self%ChemostatOn,   'ChemostatOn',   default=ChemostatOn)
call self%get_parameter(self%UptakeLock,    'UptakeLock',    default=UptakeLock)
call self%get_parameter(self%detritus_no_river_dilution,  'detritus_no_river_dilution',  default=detritus_no_river_dilution)
call self%get_parameter(self%plankton_no_river_dilution,  'plankton_no_river_dilution',  default=plankton_no_river_dilution)

!!------- model parameters from nml-list maecs_init ------- 
call self%get_parameter(self%nutN_initial ,'nutN_initial',  default=nutN_initial)
call self%get_parameter(self%phyC_initial ,'phyC_initial',  default=phyC_initial)
call self%get_parameter(self%phyN_initial ,'phyN_initial',  default=phyN_initial)
call self%get_parameter(self%detC_initial ,'detC_initial',  default=detC_initial)
call self%get_parameter(self%detN_initial ,'detN_initial',  default=detN_initial)
call self%get_parameter(self%domC_initial ,'domC_initial',  default=domC_initial)
call self%get_parameter(self%domN_initial ,'domN_initial',  default=domN_initial)
    call self%get_parameter(self%frac_Rub_ini ,'frac_Rub_ini',  default=frac_Rub_ini)
    call self%get_parameter(self%frac_chl_ini ,'frac_chl_ini',  default=frac_chl_ini)
    call self%get_parameter(self%nutP_initial ,'nutP_initial',  default=nutP_initial)
    call self%get_parameter(self%phyP_initial ,'phyP_initial',  default=phyP_initial)
    call self%get_parameter(self%detP_initial ,'detP_initial',  default=detP_initial)
    call self%get_parameter(self%domP_initial ,'domP_initial',  default=domP_initial)
    call self%get_parameter(self%nutS_initial ,'nutS_initial',  default=nutS_initial)
    call self%get_parameter(self%phyS_initial ,'phyS_initial',  default=phyS_initial)
    call self%get_parameter(self%detS_initial ,'detS_initial',  default=detS_initial)
    call self%get_parameter(self%zooC_initial ,'zooC_initial',  default=zooC_initial)

!!------- model parameters from nml-list maecs_pars ------- 
call self%get_parameter(self%P_max        ,'P_max',         default=P_max)
call self%get_parameter(self%alpha        ,'alpha',         default=alpha)
call self%get_parameter(self%sigma        ,'sigma',         default=sigma)
call self%get_parameter(self%theta_LHC    ,'theta_LHC',     default=theta_LHC)
call self%get_parameter(self%rel_chloropl_min ,'rel_chloropl_min',  default=rel_chloropl_min)
call self%get_parameter(self%QN_phy_0     ,'QN_phy_0',      default=QN_phy_0)
call self%get_parameter(self%QN_phy_max   ,'QN_phy_max',    default=QN_phy_max)
call self%get_parameter(self%V_NC_max     ,'V_NC_max',      default=V_NC_max)
call self%get_parameter(self%AffN         ,'AffN',          default=AffN)
call self%get_parameter(self%zeta_CN      ,'zeta_CN',       default=zeta_CN)
call self%get_parameter(self%zstoich_PN   ,'zstoich_PN',    default=zstoich_PN)
call self%get_parameter(self%exud_phy     ,'exud_phy',      default=exud_phy)
call self%get_parameter(self%syn_nut      ,'syn_nut',       default=syn_nut)
call self%get_parameter(self%tau_regV     ,'tau_regV',      default=tau_regV)
call self%get_parameter(self%phi_agg      ,'phi_agg',       default=phi_agg)
call self%get_parameter(self%vS_phy       ,'vS_phy',        default=vS_phy)
call self%get_parameter(self%vS_det       ,'vS_det',        default=vS_det)
call self%get_parameter(self%hydrol       ,'hydrol',        default=hydrol)
call self%get_parameter(self%remin        ,'remin',         default=remin)
call self%get_parameter(self%Ae_all       ,'Ae_all',        default=Ae_all)
call self%get_parameter(self%T_ref        ,'T_ref',         default=T_ref)
call self%get_parameter(self%NutOrder     ,'NutOrder',      default=NutOrder)
if (RubiscoOn) then
    call self%get_parameter(self%adap_rub     ,'adap_rub',      default=adap_rub)
end if
if (PhotoacclimOn) then
    call self%get_parameter(self%adap_theta   ,'adap_theta',    default=adap_theta)
end if
if (PhosphorusOn) then
    call self%get_parameter(self%QP_phy_0     ,'QP_phy_0',      default=QP_phy_0)
    call self%get_parameter(self%QP_phy_max   ,'QP_phy_max',    default=QP_phy_max)
    call self%get_parameter(self%V_PC_max     ,'V_PC_max',      default=V_PC_max)
    call self%get_parameter(self%AffP         ,'AffP',          default=AffP)
end if
if (SiliconOn) then
    call self%get_parameter(self%QSi_phy_0    ,'QSi_phy_0',     default=QSi_phy_0)
    call self%get_parameter(self%QSi_phy_max  ,'QSi_phy_max',   default=QSi_phy_max)
    call self%get_parameter(self%V_SiC_max    ,'V_SiC_max',     default=V_SiC_max)
    call self%get_parameter(self%AffSi        ,'AffSi',         default=AffSi)
end if

!!------- model parameters from nml-list maecs_graz ------- 
call self%get_parameter(self%const_NC_zoo ,'const_NC_zoo',  default=const_NC_zoo)
if (PhosphorusOn) then
    call self%get_parameter(self%const_PC_zoo ,'const_PC_zoo',  default=const_PC_zoo)
end if
if (GrazingOn) then
    call self%get_parameter(self%g_max        ,'g_max',         default=g_max)
    call self%get_parameter(self%k_grazC      ,'k_grazC',       default=k_grazC)
    call self%get_parameter(self%yield_zoo    ,'yield_zoo',     default=yield_zoo)
    call self%get_parameter(self%basal_resp_zoo ,'basal_resp_zoo',  default=basal_resp_zoo)
    call self%get_parameter(self%mort_zoo     ,'mort_zoo',      default=mort_zoo)
end if

!!------- model parameters from nml-list maecs_env ------- 
call self%get_parameter(self%a_water      ,'a_water',       default=a_water)
call self%get_parameter(self%a_spm        ,'a_spm',         default=a_spm)
call self%get_parameter(self%a_chl        ,'a_chl',         default=a_chl)
call self%get_parameter(self%frac_PAR     ,'frac_PAR',      default=frac_PAR)
call self%get_parameter(self%small        ,'small',         default=small)
call self%get_parameter(self%dil          ,'dil',           default=dil)

!!------- derived parameters  ------- 
self%K_QN_phy     = QN_phy_max-QN_phy_0
self%iK_QN        = 1.0d0/self%K_QN_phy
self%iK_QP        = 1.0d0/(QP_phy_max-QP_phy_0)
self%iK_QSi       = 1.0d0/(QSi_phy_max-QSi_phy_0)
self%itheta_max   = 1.0d0/theta_LHC
self%aver_QN_phy  = 5.0d-1*(QN_phy_max+QN_phy_0)
self%aver_QP_phy  = 5.0d-1*(QP_phy_max+QP_phy_0)
self%small_finite  = sqrt(small)

!!------- Register state variables  ------- 
call self%register_state_variable(self%id_nutN,  'nutN','mmol-N/m**3','Dissolved Inorganic Nitrogen DIN nutN', &
   nutN_initial, minimum=_ZERO_, no_river_dilution=.true. )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_nutN)
call self%register_state_variable(self%id_phyC,  'phyC','mmol-C/m**3','Phytplankton Carbon phyC', &
   phyC_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_phyC)
call self%register_state_variable(self%id_phyN,  'phyN','mmol-N/m**3','Phytplankton Nitrogen phyN', &
   phyN_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_phyN)
call self%register_state_variable(self%id_detC,  'detC','mmol-C/m**3','Detritus Carbon detC', &
   detC_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_detC)
call self%register_state_variable(self%id_detN,  'detN','mmol-N/m**3','Detritus Nitrogen detN', &
   detN_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_detN)
call self%register_state_variable(self%id_domC,  'domC','mmol-C/m**3','Dissolved Organic Carbon domC', &
   domC_initial, minimum=_ZERO_, no_river_dilution=.true. )
call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_domC)
call self%register_state_variable(self%id_domN,  'domN','mmol-N/m**3','Dissolved Organic Nitrogen domN', &
   domN_initial, minimum=_ZERO_, no_river_dilution=.true. )
call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_domN)

if (RubiscoOn) then
    Rub = frac_Rub_ini * phyC_initial  ! trait times biomass
    call self%register_state_variable(self%id_Rub,   'Rub','-','fraction of Rubisco Rub', &
       Rub, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
end if

if (PhotoacclimOn) then
    chl = frac_chl_ini * phyC_initial  ! trait times biomass
    call self%register_state_variable(self%id_chl,   'chl','mg-Chla/mmol-C','Chl:C ratio chl', &
       chl, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
end if

if (PhosphorusOn) then
    call self%register_state_variable(self%id_nutP,  'nutP','mmol-P/m**3','Dissolved Inorganic Phosphorus DIP nutP', &
       nutP_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_nutP)
    call self%register_state_variable(self%id_phyP,  'phyP','mmol-P/m**3','Phytplankton Phosphorus phyP', &
       phyP_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_phyP)
    call self%register_state_variable(self%id_detP,  'detP','mmol-P/m**3','Detritus Phosphorus detP', &
       detP_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_detP)
    call self%register_state_variable(self%id_domP,  'domP','mmol-P/m**3','Dissolved Organic Phosphorus domP', &
       domP_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%add_to_aggregate_variable(standard_variables%total_phosphorus,self%id_domP)
end if

if (SiliconOn) then
    call self%register_state_variable(self%id_nutS,  'nutS','mmol-Si/m**3','Dissolved Inorganic Silicon Si nutS', &
       nutS_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%add_to_aggregate_variable(standard_variables%total_silicate,self%id_nutS)
    call self%register_state_variable(self%id_phyS,  'phyS','mmol-Si/m**3','Phytplankton Silicon phyS', &
       phyS_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_silicate,self%id_phyS)
    call self%register_state_variable(self%id_detS,  'detS','mmol-Si/m**3','Detritus Silicon detS', &
       detS_initial, minimum=_ZERO_, no_river_dilution=detritus_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_silicate,self%id_detS)
end if

if (GrazingOn) then
    call self%register_state_variable(self%id_zooC,  'zooC','mmol-C/m**3','Zooplankton Carbon zooC', &
       zooC_initial, minimum=_ZERO_, no_river_dilution=plankton_no_river_dilution )
    call self%add_to_aggregate_variable(standard_variables%total_carbon,self%id_zooC)
end if

!!------- Register diagnostic variables  ------- 
call self%register_diagnostic_variable(self%id_chl2,    'chl2','gCHL/m**3', 'bulk chlorophyll concentration chl2', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_fracR,   'fracR','-', ' fracR', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_QN,      'QN','-', ' QN', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_QP,      'QP','-', ' QP', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_aVN,     'aVN','-', ' aVN', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_aVP,     'aVP','-', ' aVP', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_aVSi,    'aVSi','-', ' aVSi', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_rQSi,    'rQSi','-', ' rQSi', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_tmp,     'tmp','-', ' tmp', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_fac1,    'fac1','-', ' fac1', &
  output=output_instantaneous)
call self%register_diagnostic_variable(self%id_fac2,    'fac2','-', ' fac2', &
  output=output_instantaneous)

!!------- Register environmental dependencies  ------- 
call self%register_dependency(self%id_temp,varname_temp)
call self%register_dependency(self%id_par,varname_par)

! extra line included from parser var init_incl 
call maecs_init_stoichvars(self)

return

!!-------  if files are not found ...  
90 call self%fatal_error('maecs_init','Error reading namelist maecs_switch.')
91 call self%fatal_error('maecs_init','Error reading namelist maecs_init.')
92 call self%fatal_error('maecs_init','Error reading namelist maecs_pars.')
93 call self%fatal_error('maecs_init','Error reading namelist maecs_graz.')
94 call self%fatal_error('maecs_init','Error reading namelist maecs_env.')
99 call self%fatal_error('maecs_init','Namelist maecs_switch was not found in file.')
100 call self%fatal_error('maecs_init','Namelist maecs_init was not found in file.')
101 call self%fatal_error('maecs_init','Namelist maecs_pars was not found in file.')
102 call self%fatal_error('maecs_init','Namelist maecs_graz was not found in file.')
103 call self%fatal_error('maecs_init','Namelist maecs_env was not found in file.')

end subroutine initialize

!!----------------------------------------------------------------------
!!   end of section generated by parser 
!!----------------------------------------------------------------------
!#SP#


!documentation for the parser-generated initialize section
!> @fn fabm_hzg_maecs::initialize()
!> @todo from the rhsv argument of the SET_ODE's in maecs_do, it looks as if id_chl
!! and id_Rub are (correctly) handled as bulk variables (-phyC multiplied traits). however
!! registered names, units and description of these variables looks as if they are (wrongly)
!! handled as property variables?? So we should change the units, names and desc's ?


!> @brief to calculate light extinction when kc changes with depth
!> @details extinction coef=\f$ a_{\mathrm{water}} + a_{\mathrm{spm}}* (p+d+z) \f$
   subroutine get_light_extinction(self,_ARGUMENTS_GET_EXTINCTION_)
!  
! !INPUT PARAMETERS:
   class(type_hzg_maecs),intent(in)          :: self 
   _DECLARE_ARGUMENTS_GET_EXTINCTION_
   
   real(rk) :: p,d,z

   ! Enter spatial loops (if any)
   _LOOP_BEGIN_
  
   ! Retrieve current (local) state variable values.  
   _GET_(self%id_phyC,p) ! phytoplankton
   _GET_(self%id_detC,d) ! detritus
   if (self%GrazingOn) then
    _GET_(self%id_zooC, z)  ! Zooplankton Carbon in mmol-C/m**3
   else
    z=0.0_rk 
   end if
   
   ! Self-shading with explicit contribution from background phytoplankton concentration.
   _SET_EXTINCTION_(self%a_water + self%a_spm*(p+d+z))

   ! Leave spatial loops (if any)
   _LOOP_END_

   end subroutine get_light_extinction
!EOC


!> @brief a brief description to be added
!> @details some details to be added
subroutine maecs_init_stoichvars(self)
   class(type_hzg_maecs),intent(inout)          :: self 

!use maecs_types
!implicit none

!type (type_maecs_nutindex) :: ni
real(rk)    :: norder, pb
integer     :: nm

norder = self%NutOrder
nm     = 0
if (norder .gt. 1.) then
  ! --------- nitrogen -------------
  pb     = 10**floor(log10(norder))
  self%nutind%iN  = nint(norder/pb)
  norder = norder - self%nutind%iN * pb
  nm     = nm + 1
  if (norder .gt. 0.99999) then
    !  --------- phosphorus --------- 
    pb     = 10**floor(log10(norder))
    self%nutind%iP  = nint(norder/pb)
    norder = norder - self%nutind%iP * pb
    nm     = nm + 1
    if (norder .gt. 0.99999) then
      !  --------- silicon ----------- 
      pb     = 10**floor(log10(norder))
      self%nutind%iSi = nint(norder/pb)
      norder = norder - self%nutind%iSi * pb
      nm     = nm + 1
    end if
  end if  
else
 self%nutind%iN  = 1
 self%nutind%iP  = 2
 self%nutind%iSi = 3
 nm = 3
endif

! evaluate number of considered limiting nutrients  
self%nutind%nutnum = 1
if (self%PhosphorusOn) then
  self%nutind%nutnum = self%nutind%nutnum + 1
end if

! silicon
if (self%SiliconOn) then
  self%nutind%nutnum = self%nutind%nutnum + 1
end if

! special setting for synchrony dependency on relative quota: nutrient index
nh = nint(10*(self%NutOrder-floor(self%NutOrder))) 
if ( nh .gt. 0 .and. nh .le. nm) then
  self%nutind%nhi = nh  ! element number corr. to first lower digit
else
  self%nutind%nhi = 1  ! default: first element
endif

!write (*,'(A,5(I4))') 'No No N P Si:',nm,self%nutind%nutnum,self%nutind%iN,self%nutind%iP,self%nutind%iSi
 
if (self%nutind%nutnum .gt. nm) call self%fatal_error('maecs_init','Not enough nutrient indices provided by NutOrder.')


end subroutine maecs_init_stoichvars 

#include "maecs_do.F90"

end module fabm_hzg_maecs